#!/bin/sh

cat <<EOF
#------------------------------------------------------------
# Upgrade database schema
#------------------------------------------------------------
EOF
cd ${OPENSHIFT_REPO_DIR}
PYTHONPATH=. scripts/upgrade_db.py --database "${OPENSHIFT_POSTGRESQL_DB_URL}"
echo 'DONE'
