#!/bin/sh

curl https://app.getsentry.com/api/hooks/release/builtin/93959/c25097566bd00119ccdd76f93bcd168fe095fa503f3ba4fa1354ff3671bcd9e9/ \
  -X POST \
  -H 'Content-Type: application/json' \
  -d "{"'"'"version"'"'": "'"'"$(date +'%d %b %Y %H:%M:%S')"'"'"}"
