#!/bin/sh

GIT_DIR="$(find . -name "*.git" 2>/dev/null)"
REF="$(cd $GIT_DIR && git log -1 --pretty=%h)"
VERSION="$(cd $GIT_DIR && git log -1 --pretty=%cd --date=format:%Y.%m.%d.%H%M%S)"
echo ""
echo "[SENTRY]: $REF $VERSION"
curl https://app.getsentry.com/api/hooks/release/builtin/93959/c25097566bd00119ccdd76f93bcd168fe095fa503f3ba4fa1354ff3671bcd9e9/ \
  -X POST \
  -v \
  -H 'Content-Type: application/json' \
  -d "{"'"'"version"'"'": "'"'"$VERSION"'"'", "'"'"ref"'"'": "'"'"$REF"'"'"}"
