version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"

  web:
    build:
      context: .
      dockerfile: dev/web.Dockerfile
    command: /code/runweb.py --host 0.0.0.0 --port 5000
    volumes:
    - .:/code
    working_dir: /code
    ports:
    - "80:5000"
    links:
    - postgres
    environment:
      DEBUG:
      FLASK_SECRET_KEY:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
