/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <new>
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
struct NimStringDesc;
struct TGenericSeq;
struct tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q;
struct tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ;
struct tySequence_phjbYJtsbOIAYa9be34hhZg;
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct tySequence_5nQuE8Alerr1wffkYjQ9bGg;
struct TNimType;
struct TNimNode;
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
struct Exception;
struct RootObj;
struct tySequence_uB9b75OUPRENsBAu4AnoePA;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA;
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
struct tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ {
tySequence_phjbYJtsbOIAYa9be34hhZg* rows;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cols;
tySequence_5nQuE8Alerr1wffkYjQ9bGg* types;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA;
struct tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q {
tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA kind;
union{
struct {NI64 intval;
};
struct {NF floatval;
};
struct {NimStringDesc* textval;
};
struct {NimStringDesc* blobval;
};
struct {NIM_BOOL boolval;
};
};
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* para1);
struct RootObj {
TNimType* m_type;
};
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
struct Exception : public RootObj {
virtual void raise() {throw *this;}
~Exception() {if(this->raiseId) popCurrentExceptionEx(this->raiseId);}
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA : public Exception {
virtual void raise() {throw *this;}
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw {
char dummy;
};
struct tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA {
NI64 lastID;
};
typedef NimStringDesc* tyArray_8ZvwQIddfpj2THRVPsFzIQ[1];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ : TGenericSeq {
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_phjbYJtsbOIAYa9be34hhZg : TGenericSeq {
  tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data[SEQ_DECL_SIZE];
};
struct tySequence_5nQuE8Alerr1wffkYjQ9bGg : TGenericSeq {
  tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA : TGenericSeq {
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence_5nQuE8Alerr1wffkYjQ9bGg)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*, prepareAndBindArgs_1iaacC6gqWeHe3FTjtelnA)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0);
extern "C" N_CDECL(int, sqlite3_prepare_v2)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING zSql, int nByte, tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*& ppStmt, NCSTRING* pzTail);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) __attribute__((noreturn));
extern "C" N_CDECL(NI32, sqlite3_clear_bindings)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
extern "C" N_CDECL(NI32, sqlite3_bind_text)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2, NCSTRING para3, NI32 n, tyProc_32w2ZypAyMWuajvi2Jt79cg para5);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
extern "C" N_CDECL(NI32, sqlite3_bind_null)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2);
extern "C" N_CDECL(NI32, sqlite3_bind_int64)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2, NI64 para3);
extern "C" N_CDECL(NI32, sqlite3_bind_double)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2, NF para3);
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw)(tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg* a, void* p);
static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace_njssp69aa7hvxte9bJ8uuDcg)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isOnStack_dJJW59cIgsBmT59aZrOM71Mg)(void* p);
static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
extern "C" N_CDECL(NI32, sqlite3_step)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
extern "C" N_CDECL(NI32, sqlite3_column_count)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pStmt);
extern "C" N_CDECL(NCSTRING, sqlite3_column_name)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
extern "C" N_CDECL(NI32, sqlite3_column_type)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 iCol);
static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col);
extern "C" N_CDECL(NCSTRING, sqlite3_column_text)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 iCol);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
extern "C" N_CDECL(NI32, sqlite3_finalize)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pStmt);
static N_NIMCALL(void, Marker_tyRef_E0cTKF9afYzykvtJvV8SvRA)(void* p, NI op);
N_NIMCALL(void, FieldDiscriminantCheck)(NI oldDiscVal, NI newDiscVal, TNimNode** a, NI L);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
extern "C" N_CDECL(NI64, sqlite3_last_insert_rowid)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* para1);
N_LIB_PRIVATE N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
TNimType NTI_U9cP8WGvRKuOoBThSbzXQVQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_phjbYJtsbOIAYa9be34hhZg_;
TNimType NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_;
TNimType NTI_5nQuE8Alerr1wffkYjQ9bGg_;
extern TNimType NTI_gcKyg9bhR5vWTJg3cREMk0Q_;
extern TNimType NTI_qrLSDoe2oBoAqNtJ9badtnA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_8gVorlB2Rkv7LEix8x9aC0Q_;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_E0cTKF9afYzykvtJvV8SvRA_;
extern TNimNode* NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[7];
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_7, "textval", 7);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_10, "intval", 6);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_12, "floatval", 8);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_14, "boolval", 7);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_15, "Unbindable data type: ", 22);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_17, "[SYSASSERT] ", 12);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_18, "begin nimGCunrefNoCycle", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_16 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_17),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_18)}
;
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_20, "[GCASSERT] ", 11);
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_21, "decRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_19 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_20),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_21)}
;
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_23, "decRef", 6);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_22 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_20),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_23)}
;
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_25, "end nimGCunrefNoCycle 5", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_24 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_17),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_25)}
;
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_27, "asgnRef", 7);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_26 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_20),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_27)}
;
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_29, "incRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GsqUuOaHBzpx3PWGFQW5yg_28 = {((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_20),
((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_29)}
;
TNimNode* NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[7];
STRING_LITERAL(TM_GsqUuOaHBzpx3PWGFQW5yg_33, "/Users/matt/m/buckets.git/ccore/src/buckets/db.nim(172, 9) `not"
" db.isNil` Database not connected.", 97);
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op) {
	tySequence_phjbYJtsbOIAYa9be34hhZg* a;
	NI T1_;
	a = (tySequence_phjbYJtsbOIAYa9be34hhZg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tySequence_5nQuE8Alerr1wffkYjQ9bGg)(void* p, NI op) {
	tySequence_5nQuE8Alerr1wffkYjQ9bGg* a;
	NI T1_;
	a = (tySequence_5nQuE8Alerr1wffkYjQ9bGg*)p;
	T1_ = (NI)0;
}

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = "";
}	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[(*dest).len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).len + ((NI) 1)))));
		(*dest).len += (*src).len;
}	}
	LA3_: ;
}

static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void) {
	gch_IcYaEuuWivYAS86vFMTS3Q.recGcLock += ((NI) 1);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(187, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw(gch_IcYaEuuWivYAS86vFMTS3Q.zct, c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(190, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(190, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_19, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(191, "gc.nim");
	{
		nimln_(106, "gc.nim");
		nimln_(191, "gc.nim");
		if (!!(((NU64)(((NI) 8)) <= (NU64)((*c).refcount)))) goto LA8_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_22, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA8_: ;
	nimln_(192, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	nimln_(193, "gc.nim");
	{
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA12_;
{		nimln_(194, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system(c);
}	}
	LA12_: ;
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(125, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(218, "gc.nim");
	{
		if (!NIM_FALSE) goto LA3_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_16, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA3_: ;
	nimln_(219, "gc.nim");
	decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p));
	nimln_(220, "gc.nim");
	{
		if (!NIM_FALSE) goto LA7_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_24, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA7_: ;
	popFrame();
}

static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(174, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(174, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_28, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(175, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(227, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(227, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isOnStack_dJJW59cIgsBmT59aZrOM71Mg(((void*) (dest)));
		if (!!(!(T3_))) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GsqUuOaHBzpx3PWGFQW5yg_26, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(229, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!((src == NIM_NIL))) goto LA8_;
{		nimln_(229, "gc.nim");
		incRef_MV4BBk6J1qu70IbBxwEn4wsystem(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src));
}	}
	LA8_: ;
	nimln_(230, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA12_;
{		nimln_(230, "gc.nim");
		decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest)));
}	}
	LA12_: ;
	nimln_(231, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*, prepareAndBindArgs_1iaacC6gqWeHe3FTjtelnA)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0) {
	tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* result;
	NimStringDesc* querystring;
	nimfr_("prepareAndBindArgs", "db.nim");
	result = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
	nimln_(110, "db.nim");
	querystring = query;
	nimln_(111, "db.nim");
	{
		int T3_;
		nimln_(483, "system.nim");
		nimln_(111, "db.nim");
		T3_ = (int)0;
		T3_ = sqlite3_prepare_v2(db, nimToCStringConv(querystring), ((int)chckRange((querystring ? querystring->len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), result, NIM_NIL);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
{		nimln_(112, "db.nim");
		dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}	}
	LA4_: ;
	nimln_(113, "db.nim");
	{
		NI32 T8_;
		nimln_(483, "system.nim");
		nimln_(113, "db.nim");
		T8_ = (NI32)0;
		T8_ = sqlite3_clear_bindings(result);
		if (!!((T8_ == ((NI32) 0)))) goto LA9_;
{		nimln_(114, "db.nim");
		dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}	}
	LA9_: ;
	{
		NI i;
		tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* param;
		i = (NI)0;
		param = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
		nimln_(2375, "system.nim");
		NI i_2 = ((NI) 0);
		{
			nimln_(2376, "system.nim");
			while (1) {
				NI TM_GsqUuOaHBzpx3PWGFQW5yg_30;
				if (!(i_2 < paramsLen_0)) goto LA13;
				nimln_(115, "db.nim");
				i = i_2;
				nimln_(2377, "system.nim");
				if ((NU)(i_2) >= (NU)(paramsLen_0)) raiseIndexError2(i_2,paramsLen_0-1);
				param = params[i_2];
				nimln_(116, "db.nim");
				switch ((*param).kind) {
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 3):
				{
					nimln_(118, "db.nim");
					{
						NI TM_GsqUuOaHBzpx3PWGFQW5yg_6;
						NI32 T17_;
						nimln_(483, "system.nim");
						nimln_(118, "db.nim");
						TM_GsqUuOaHBzpx3PWGFQW5yg_6 = addInt(i, ((NI) 1));
						if (!(((8 &(1U<<((NU)((*param).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_7));
						if (!(((8 &(1U<<((NU)((*param).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_7));
						T17_ = (NI32)0;
						T17_ = sqlite3_bind_text(result, ((int)chckRange((NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_6), ((int) (-2147483647 -1)), ((int) 2147483647))), nimToCStringConv((*param).textval), ((int)chckRange(((*param).textval ? (*param).textval->len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL);
						if (!!((T17_ == ((NI32) 0)))) goto LA18_;
{						nimln_(119, "db.nim");
						dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}					}
					LA18_: ;
				}
				break;
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 0):
				{
					nimln_(121, "db.nim");
					{
						NI TM_GsqUuOaHBzpx3PWGFQW5yg_8;
						NI32 T23_;
						nimln_(483, "system.nim");
						nimln_(121, "db.nim");
						TM_GsqUuOaHBzpx3PWGFQW5yg_8 = addInt(i, ((NI) 1));
						T23_ = (NI32)0;
						T23_ = sqlite3_bind_null(result, ((int)chckRange((NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_8), ((int) (-2147483647 -1)), ((int) 2147483647))));
						if (!!((T23_ == ((NI32) 0)))) goto LA24_;
{						nimln_(122, "db.nim");
						dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}					}
					LA24_: ;
				}
				break;
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 1):
				{
					nimln_(124, "db.nim");
					{
						NI TM_GsqUuOaHBzpx3PWGFQW5yg_9;
						NI32 T29_;
						nimln_(483, "system.nim");
						nimln_(124, "db.nim");
						TM_GsqUuOaHBzpx3PWGFQW5yg_9 = addInt(i, ((NI) 1));
						if (!(((2 &(1U<<((NU)((*param).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_10));
						T29_ = (NI32)0;
						T29_ = sqlite3_bind_int64(result, ((int)chckRange((NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_9), ((int) (-2147483647 -1)), ((int) 2147483647))), (*param).intval);
						if (!!((T29_ == ((NI32) 0)))) goto LA30_;
{						nimln_(125, "db.nim");
						dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}					}
					LA30_: ;
				}
				break;
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 2):
				{
					nimln_(127, "db.nim");
					{
						NI TM_GsqUuOaHBzpx3PWGFQW5yg_11;
						NI32 T35_;
						nimln_(483, "system.nim");
						nimln_(127, "db.nim");
						TM_GsqUuOaHBzpx3PWGFQW5yg_11 = addInt(i, ((NI) 1));
						if (!(((4 &(1U<<((NU)((*param).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_12));
						T35_ = (NI32)0;
						T35_ = sqlite3_bind_double(result, ((int)chckRange((NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_11), ((int) (-2147483647 -1)), ((int) 2147483647))), (*param).floatval);
						if (!!((T35_ == ((NI32) 0)))) goto LA36_;
{						nimln_(128, "db.nim");
						dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}					}
					LA36_: ;
				}
				break;
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 4):
				{
					nimln_(130, "db.nim");
					{
						NI TM_GsqUuOaHBzpx3PWGFQW5yg_13;
						NI T41_;
						NI32 T47_;
						nimln_(483, "system.nim");
						nimln_(130, "db.nim");
						TM_GsqUuOaHBzpx3PWGFQW5yg_13 = addInt(i, ((NI) 1));
						T41_ = (NI)0;
						{
							if (!(((16 &(1U<<((NU)((*param).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_14));
							if (!(*param).boolval) goto LA44_;
{							T41_ = ((NI) 1);
}						}
						goto LA42_;
						LA44_: ;
						{
							T41_ = ((NI) 0);
						}
						LA42_: ;
						T47_ = (NI32)0;
						T47_ = sqlite3_bind_int64(result, ((int)chckRange((NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_13), ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI64) (T41_)));
						if (!!((T47_ == ((NI32) 0)))) goto LA48_;
{						nimln_(131, "db.nim");
						dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}					}
					LA48_: ;
				}
				break;
				case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 5):
				{
					tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA* e;
					NimStringDesc* fmtRes;
					NimStringDesc* T51_;
					e = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*)0;
					nimln_(2989, "system.nim");
					e = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*) newObj((&NTI_gcKyg9bhR5vWTJg3cREMk0Q_), sizeof(tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA));
					new (e) tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
					(*e).m_type = (&NTI_qrLSDoe2oBoAqNtJ9badtnA_);
					nimln_(133, "db.nim");
					fmtRes = rawNewString(((NI) 44));
					fmtRes = resizeString(fmtRes, 22);
appendString(fmtRes, ((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_15));
					nimln_(270, "strformat.nim");
					fmtRes = resizeString(fmtRes, (reprEnum((NI)(*param).kind, (&NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_)) ? reprEnum((NI)(*param).kind, (&NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_))->len : 0) + 0);
appendString(fmtRes, reprEnum((NI)(*param).kind, (&NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_)));
					T51_ = (NimStringDesc*)0;
					T51_ = (*e).message; (*e).message = copyStringRC1(fmtRes);
					if (T51_) nimGCunrefNoCycle(T51_);
					nimln_(2984, "system.nim");
					asgnRef((void**) (&(*e).parent), NIM_NIL);
					nimln_(133, "db.nim");
					raiseExceptionEx((Exception*)e, "CatchableError", "prepareAndBindArgs", "db.nim", 133);
				}
				break;
				}
				nimln_(2378, "system.nim");
				TM_GsqUuOaHBzpx3PWGFQW5yg_30 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_30);
			} LA13: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col) {
	NimStringDesc* result;
	NCSTRING T1_;
	nimfr_("[]", "db_sqlite.nim");
	result = (NimStringDesc*)0;
	nimln_(224, "db_sqlite.nim");
	nimln_(225, "db_sqlite.nim");
	T1_ = (NCSTRING)0;
	T1_ = sqlite3_column_text(row, col);
	result = cstrToNimstr(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, fetchAll_yL7HtM6gH29aOZ839ajuWBMQ)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* statement, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0, tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ* Result) {
	nimfr_("fetchAll", "db.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_U9cP8WGvRKuOoBThSbzXQVQ_));
	{
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row;
		row = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
		nimln_(136, "db.nim");
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pstmt = prepareAndBindArgs_1iaacC6gqWeHe3FTjtelnA(db, statement, params, paramsLen_0);
		{
			nimln_(137, "db.nim");
			while (1) {
				NI32 T4_;
				tySequence_sM4lkSb7zS6F7OVMvW9cffQ* res;
				NI T36_;
				T4_ = (NI32)0;
				T4_ = sqlite3_step(pstmt);
				if (!(T4_ == ((NI32) 100))) goto LA3;
				nimln_(144, "db.nim");
				row = pstmt;
				res = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
				nimln_(147, "db.nim");
				NI32 L = sqlite3_column_count(row);
				nimln_(148, "db.nim");
				{
					NI T7_;
					T7_ = ((*Result).cols ? (*Result).cols->len : 0);
					if (!(T7_ == ((NI) 0))) goto LA8_;
{					{
						NI32 coli;
						coli = (NI32)0;
						nimln_(3716, "system.nim");
						NI32 i = ((NI32) 0);
						{
							nimln_(3717, "system.nim");
							while (1) {
								NCSTRING T13_;
								NimStringDesc* T14_;
								NI T15_;
								NimStringDesc* T16_;
								NI32 T17_;
								NI TM_GsqUuOaHBzpx3PWGFQW5yg_31;
								if (!(i < L)) goto LA12;
								nimln_(149, "db.nim");
								coli = i;
								nimln_(150, "db.nim");
								T13_ = (NCSTRING)0;
								T13_ = sqlite3_column_name(row, coli);
								T14_ = (NimStringDesc*)0;
								T14_ = cstrToNimstr(T13_);
								unsureAsgnRef((void**) (&(*Result).cols), (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3((*Result).cols, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_)));
								T15_ = (*Result).cols->len++;
								T16_ = (NimStringDesc*)0;
								T16_ = (*Result).cols->data[T15_]; (*Result).cols->data[T15_] = copyStringRC1(T14_);
								if (T16_) nimGCunrefNoCycle(T16_);
								nimln_(151, "db.nim");
								T17_ = (NI32)0;
								T17_ = sqlite3_column_type(row, coli);
								switch (T17_) {
								case ((NI) 1):
								{
									NI T19_;
									nimln_(153, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T19_ = (*Result).types->len++;
									(*Result).types->data[T19_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 1);
								}
								break;
								case ((NI) 5):
								{
									NI T21_;
									nimln_(155, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T21_ = (*Result).types->len++;
									(*Result).types->data[T21_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 0);
								}
								break;
								case ((NI) 3):
								{
									NI T23_;
									nimln_(157, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T23_ = (*Result).types->len++;
									(*Result).types->data[T23_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 3);
								}
								break;
								case ((NI) 2):
								{
									NI T25_;
									nimln_(159, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T25_ = (*Result).types->len++;
									(*Result).types->data[T25_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 2);
								}
								break;
								case ((NI) 4):
								{
									NI T27_;
									nimln_(161, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T27_ = (*Result).types->len++;
									(*Result).types->data[T27_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 5);
								}
								break;
								default:
								{
									NI T29_;
									nimln_(163, "db.nim");
									unsureAsgnRef((void**) (&(*Result).types), (tySequence_5nQuE8Alerr1wffkYjQ9bGg*) incrSeqV3((*Result).types, (&NTI_5nQuE8Alerr1wffkYjQ9bGg_)));
									T29_ = (*Result).types->len++;
									(*Result).types->data[T29_] = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 0);
								}
								break;
								}
								nimln_(3719, "system.nim");
								TM_GsqUuOaHBzpx3PWGFQW5yg_31 = addInt(i, ((NI) 1));
								if (TM_GsqUuOaHBzpx3PWGFQW5yg_31 < (-2147483647 -1) || TM_GsqUuOaHBzpx3PWGFQW5yg_31 > 2147483647) raiseOverflow();
								i = (NI32)(TM_GsqUuOaHBzpx3PWGFQW5yg_31);
							} LA12: ;
						}
					}
}				}
				LA8_: ;
				{
					NI32 coli_2;
					coli_2 = (NI32)0;
					nimln_(3716, "system.nim");
					NI32 i_2 = ((NI32) 0);
					{
						nimln_(3717, "system.nim");
						while (1) {
							NimStringDesc* T33_;
							NI T34_;
							NimStringDesc* T35_;
							NI TM_GsqUuOaHBzpx3PWGFQW5yg_32;
							if (!(i_2 < L)) goto LA32;
							nimln_(164, "db.nim");
							coli_2 = i_2;
							nimln_(165, "db.nim");
							T33_ = (NimStringDesc*)0;
							T33_ = X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile(row, coli_2);
							res = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(res, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
							T34_ = res->len++;
							T35_ = (NimStringDesc*)0;
							T35_ = res->data[T34_]; res->data[T34_] = copyStringRC1(T33_);
							if (T35_) nimGCunrefNoCycle(T35_);
							nimln_(3719, "system.nim");
							TM_GsqUuOaHBzpx3PWGFQW5yg_32 = addInt(i_2, ((NI) 1));
							if (TM_GsqUuOaHBzpx3PWGFQW5yg_32 < (-2147483647 -1) || TM_GsqUuOaHBzpx3PWGFQW5yg_32 > 2147483647) raiseOverflow();
							i_2 = (NI32)(TM_GsqUuOaHBzpx3PWGFQW5yg_32);
						} LA32: ;
					}
				}
				nimln_(166, "db.nim");
				unsureAsgnRef((void**) (&(*Result).rows), (tySequence_phjbYJtsbOIAYa9be34hhZg*) incrSeqV3((*Result).rows, (&NTI_phjbYJtsbOIAYa9be34hhZg_)));
				T36_ = (*Result).rows->len++;
				genericSeqAssign((&(*Result).rows->data[T36_]), res, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
			} LA3: ;
		}
		nimln_(139, "db.nim");
		{
			NI32 T39_;
			nimln_(483, "system.nim");
			nimln_(139, "db.nim");
			T39_ = (NI32)0;
			T39_ = sqlite3_finalize(pstmt);
			if (!!((T39_ == ((NI32) 0)))) goto LA40_;
{			nimln_(140, "db.nim");
			dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}		}
		LA40_: ;
	}
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_E0cTKF9afYzykvtJvV8SvRA)(void* p, NI op) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* a;
	a = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)p;
	switch ((*a).kind) {
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 1):
	break;
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 2):
	break;
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 3):
	nimGCvisit((void*)(*a).textval, op);
	break;
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 5):
	nimGCvisit((void*)(*a).blobval, op);
	break;
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 4):
	break;
	case ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 0):
	break;
	} 
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_opUVQPa4k9aAgZsg9aKPuaog)(NI x) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* result;
	tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA T1_;
	nimfr_("newParam", "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
	nimln_(67, "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*) newObj((&NTI_E0cTKF9afYzykvtJvV8SvRA_), sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q));
	nimln_(68, "db.nim");
	T1_ = (tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA)0;
	T1_ = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 1);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind, 7);
	(*result).kind = T1_;
	if (!(((2 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_10));
	nimln_(69, "db.nim");
	(*result).intval = ((NI64) (x));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_k5IcRUo9cf7SwFKByll2iag)(NimStringDesc* x) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* result;
	tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA T1_;
	NimStringDesc* T2_;
	nimfr_("newParam", "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
	nimln_(62, "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*) newObj((&NTI_E0cTKF9afYzykvtJvV8SvRA_), sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q));
	nimln_(63, "db.nim");
	T1_ = (tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA)0;
	T1_ = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 3);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind, 7);
	(*result).kind = T1_;
	if (!(((8 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_7));
	nimln_(64, "db.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = (*result).textval; (*result).textval = copyStringRC1(x);
	if (T2_) nimGCunrefNoCycle(T2_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_j5FS2km0qtRufvzb6B7zHQ)(NF x) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* result;
	tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA T1_;
	nimfr_("newParam", "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
	nimln_(72, "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*) newObj((&NTI_E0cTKF9afYzykvtJvV8SvRA_), sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q));
	nimln_(73, "db.nim");
	T1_ = (tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA)0;
	T1_ = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 2);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind, 7);
	(*result).kind = T1_;
	if (!(((4 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_12));
	nimln_(74, "db.nim");
	(*result).floatval = x;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_U4CJLW4cl5UxoEpwDyohCg)(void* x) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* result;
	tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA T1_;
	nimfr_("newParam", "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
	nimln_(77, "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*) newObj((&NTI_E0cTKF9afYzykvtJvV8SvRA_), sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q));
	nimln_(78, "db.nim");
	T1_ = (tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA)0;
	T1_ = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 0);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind, 7);
	(*result).kind = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_Ij8X9aQmqY59ae9bP3wiQ79azA)(NIM_BOOL x) {
	tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* result;
	tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA T1_;
	nimfr_("newParam", "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
	nimln_(81, "db.nim");
	result = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*) newObj((&NTI_E0cTKF9afYzykvtJvV8SvRA_), sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q));
	nimln_(82, "db.nim");
	T1_ = (tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA)0;
	T1_ = ((tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA) 4);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind, 7);
	(*result).kind = T1_;
	if (!(((16 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_14));
	nimln_(83, "db.nim");
	(*result).boolval = x;
	popFrame();
	return result;
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA, runQuery_djJQq5r3kwb3crAxcJersA)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0) {
	tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA result;
	nimfr_("runQuery", "db.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA));
	nimln_(172, "db.nim");
	{
		if (!!(!((db == 0)))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GsqUuOaHBzpx3PWGFQW5yg_33));
}	}
	LA3_: ;
	nimln_(173, "db.nim");
	tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pstmt = prepareAndBindArgs_1iaacC6gqWeHe3FTjtelnA(db, query, params, paramsLen_0);
	nimln_(174, "db.nim");
	{
		NI32 T7_;
		T7_ = (NI32)0;
		T7_ = sqlite3_step(pstmt);
		if (!(T7_ == ((NI) 101) || T7_ == ((NI) 100))) goto LA8_;
{		nimln_(175, "db.nim");
		result.lastID = sqlite3_last_insert_rowid(db);
		nimln_(176, "db.nim");
		{
			NI32 T12_;
			nimln_(483, "system.nim");
			nimln_(176, "db.nim");
			T12_ = (NI32)0;
			T12_ = sqlite3_finalize(pstmt);
			if (!!((T12_ == ((NI32) 0)))) goto LA13_;
{			nimln_(177, "db.nim");
			dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}		}
		LA13_: ;
}	}
	LA8_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, executeMany_yEh4EZPD1kHlwpF1V8LR2Q)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc** statements, NI statementsLen_0) {
	nimfr_("executeMany", "db.nim");
	{
		NimStringDesc* s;
		s = (NimStringDesc*)0;
		nimln_(2302, "system.nim");
		NI i = ((NI) 0);
		{
			nimln_(2303, "system.nim");
			while (1) {
				tyArray_8ZvwQIddfpj2THRVPsFzIQ T4_;
				NI TM_GsqUuOaHBzpx3PWGFQW5yg_34;
				if (!(i < statementsLen_0)) goto LA3;
				nimln_(182, "db.nim");
				if ((NU)(i) >= (NU)(statementsLen_0)) raiseIndexError2(i,statementsLen_0-1);
				s = statements[i];
				nimln_(183, "db.nim");
				nimZeroMem((void*)T4_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
				exec_kASFnJjvwTJpKpmn9aQHmPg(db, s, T4_, 0);
				nimln_(2305, "system.nim");
				TM_GsqUuOaHBzpx3PWGFQW5yg_34 = addInt(i, ((NI) 1));
				i = (NI)(TM_GsqUuOaHBzpx3PWGFQW5yg_34);
			} LA3: ;
		}
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, buckets_dbDatInit000)(void) {
static TNimNode* TM_GsqUuOaHBzpx3PWGFQW5yg_2[3];
static TNimNode* TM_GsqUuOaHBzpx3PWGFQW5yg_3[6];
NI TM_GsqUuOaHBzpx3PWGFQW5yg_5;
static char* NIM_CONST TM_GsqUuOaHBzpx3PWGFQW5yg_4[6] = {
"Null", 
"Int", 
"Float", 
"Text", 
"Bool", 
"Blob"};
static TNimNode TM_GsqUuOaHBzpx3PWGFQW5yg_0[18];
NTI_U9cP8WGvRKuOoBThSbzXQVQ_.size = sizeof(tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ);
NTI_U9cP8WGvRKuOoBThSbzXQVQ_.kind = 18;
NTI_U9cP8WGvRKuOoBThSbzXQVQ_.base = 0;
NTI_U9cP8WGvRKuOoBThSbzXQVQ_.flags = 2;
TM_GsqUuOaHBzpx3PWGFQW5yg_2[0] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[1];
NTI_phjbYJtsbOIAYa9be34hhZg_.size = sizeof(tySequence_phjbYJtsbOIAYa9be34hhZg*);
NTI_phjbYJtsbOIAYa9be34hhZg_.kind = 24;
NTI_phjbYJtsbOIAYa9be34hhZg_.base = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
NTI_phjbYJtsbOIAYa9be34hhZg_.flags = 2;
NTI_phjbYJtsbOIAYa9be34hhZg_.marker = Marker_tySequence_phjbYJtsbOIAYa9be34hhZg;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[1].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[1].offset = offsetof(tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ, rows);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[1].typ = (&NTI_phjbYJtsbOIAYa9be34hhZg_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[1].name = "rows";
TM_GsqUuOaHBzpx3PWGFQW5yg_2[1] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[2];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[2].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[2].offset = offsetof(tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ, cols);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[2].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[2].name = "cols";
TM_GsqUuOaHBzpx3PWGFQW5yg_2[2] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[3];
NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_.size = sizeof(tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA);
NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_.kind = 14;
NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_.base = 0;
NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_.flags = 3;
for (TM_GsqUuOaHBzpx3PWGFQW5yg_5 = 0; TM_GsqUuOaHBzpx3PWGFQW5yg_5 < 6; TM_GsqUuOaHBzpx3PWGFQW5yg_5++) {
TM_GsqUuOaHBzpx3PWGFQW5yg_0[TM_GsqUuOaHBzpx3PWGFQW5yg_5+4].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[TM_GsqUuOaHBzpx3PWGFQW5yg_5+4].offset = TM_GsqUuOaHBzpx3PWGFQW5yg_5;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[TM_GsqUuOaHBzpx3PWGFQW5yg_5+4].name = TM_GsqUuOaHBzpx3PWGFQW5yg_4[TM_GsqUuOaHBzpx3PWGFQW5yg_5];
TM_GsqUuOaHBzpx3PWGFQW5yg_3[TM_GsqUuOaHBzpx3PWGFQW5yg_5] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[TM_GsqUuOaHBzpx3PWGFQW5yg_5+4];
}
TM_GsqUuOaHBzpx3PWGFQW5yg_0[10].len = 6; TM_GsqUuOaHBzpx3PWGFQW5yg_0[10].kind = 2; TM_GsqUuOaHBzpx3PWGFQW5yg_0[10].sons = &TM_GsqUuOaHBzpx3PWGFQW5yg_3[0];
NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_.node = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[10];
NTI_5nQuE8Alerr1wffkYjQ9bGg_.size = sizeof(tySequence_5nQuE8Alerr1wffkYjQ9bGg*);
NTI_5nQuE8Alerr1wffkYjQ9bGg_.kind = 24;
NTI_5nQuE8Alerr1wffkYjQ9bGg_.base = (&NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_);
NTI_5nQuE8Alerr1wffkYjQ9bGg_.flags = 2;
NTI_5nQuE8Alerr1wffkYjQ9bGg_.marker = Marker_tySequence_5nQuE8Alerr1wffkYjQ9bGg;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[3].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[3].offset = offsetof(tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ, types);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[3].typ = (&NTI_5nQuE8Alerr1wffkYjQ9bGg_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[3].name = "types";
TM_GsqUuOaHBzpx3PWGFQW5yg_0[0].len = 3; TM_GsqUuOaHBzpx3PWGFQW5yg_0[0].kind = 2; TM_GsqUuOaHBzpx3PWGFQW5yg_0[0].sons = &TM_GsqUuOaHBzpx3PWGFQW5yg_2[0];
NTI_U9cP8WGvRKuOoBThSbzXQVQ_.node = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[0];
NTI_8gVorlB2Rkv7LEix8x9aC0Q_.size = sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q);
NTI_8gVorlB2Rkv7LEix8x9aC0Q_.kind = 18;
NTI_8gVorlB2Rkv7LEix8x9aC0Q_.base = 0;
NTI_8gVorlB2Rkv7LEix8x9aC0Q_.flags = 2;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].kind = 3;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, kind);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].typ = (&NTI_WRq6Jv2bvs9b3t9bKN7EgcWA_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].name = "kind";
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].sons = &NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[0];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[11].len = 6;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[12].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[12].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, intval);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[12].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[12].name = "intval";
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[1] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[12];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[13].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[13].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, floatval);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[13].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[13].name = "floatval";
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[2] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[13];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[14].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[14].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, textval);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[14].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[14].name = "textval";
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[3] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[14];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[15].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[15].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, blobval);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[15].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[15].name = "blobval";
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[5] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[15];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[16].kind = 1;
TM_GsqUuOaHBzpx3PWGFQW5yg_0[16].offset = offsetof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q, boolval);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[16].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_GsqUuOaHBzpx3PWGFQW5yg_0[16].name = "boolval";
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[4] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[16];
TM_GsqUuOaHBzpx3PWGFQW5yg_0[17].len = 0; TM_GsqUuOaHBzpx3PWGFQW5yg_0[17].kind = 2;
NimDT__8gVorlB2Rkv7LEix8x9aC0Q_kind[0] = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[17];
NTI_8gVorlB2Rkv7LEix8x9aC0Q_.node = &TM_GsqUuOaHBzpx3PWGFQW5yg_0[11];
NTI_E0cTKF9afYzykvtJvV8SvRA_.size = sizeof(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*);
NTI_E0cTKF9afYzykvtJvV8SvRA_.kind = 22;
NTI_E0cTKF9afYzykvtJvV8SvRA_.base = (&NTI_8gVorlB2Rkv7LEix8x9aC0Q_);
NTI_E0cTKF9afYzykvtJvV8SvRA_.flags = 2;
NTI_E0cTKF9afYzykvtJvV8SvRA_.marker = Marker_tyRef_E0cTKF9afYzykvtJvV8SvRA;
}

