/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_Table_VhiYQVROvZwCBgplqpTfWg;
struct tySequence_hC9cYWgGj63WaE3PXFdHUGw;
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ;
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
struct NimStringDesc;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct tyObject_DbError_9cp8FUMATyqFmLaAKCXEjCQ;
struct tyObject_IOError_iLZrPn9anoh9ad1MmO0RczFw;
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
struct Exception;
struct RootObj;
struct tySequence_uB9b75OUPRENsBAu4AnoePA;
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
struct tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg;
struct tyTuple_eq1RM0xbpgPWPAQamwDgbA;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table_VhiYQVROvZwCBgplqpTfWg {
tySequence_hC9cYWgGj63WaE3PXFdHUGw* data;
NI counter;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ {
NI id;
tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db;
NimStringDesc* filename;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
struct RootObj {
TNimType* m_type;
};
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
struct Exception : public RootObj {
virtual void raise() {throw *this;}
~Exception() {if(this->raiseId) popCurrentExceptionEx(this->raiseId);}
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA : public Exception {
virtual void raise() {throw *this;}
};
struct tyObject_IOError_iLZrPn9anoh9ad1MmO0RczFw : public tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA {
virtual void raise() {throw *this;}
};
struct tyObject_DbError_9cp8FUMATyqFmLaAKCXEjCQ : public tyObject_IOError_iLZrPn9anoh9ad1MmO0RczFw {
virtual void raise() {throw *this;}
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_8ZvwQIddfpj2THRVPsFzIQ[1];
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw {
char dummy;
};
typedef N_NIMCALL_PTR(void, tyProc_Ct1Mg728R1V16bUJA7EJ8A) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db);
struct tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg {
NimStringDesc* Field0;
tyProc_Ct1Mg728R1V16bUJA7EJ8A Field1;
};
typedef tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg tyArray_3elISlPUynt0R48Wr6G2wg[15];
struct tyTuple_eq1RM0xbpgPWPAQamwDgbA {
NI Field0;
NI Field1;
tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* Field2;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ : TGenericSeq {
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_hC9cYWgGj63WaE3PXFdHUGw : TGenericSeq {
  tyTuple_eq1RM0xbpgPWPAQamwDgbA data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA : TGenericSeq {
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ)(void* p, NI op);
static N_NIMCALL(void, TM_Q8GDWOFB5uWKFMQFSo1oVw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, initTable_jqzpDgYBM9aUAc5X3WbaZOA)(NI initialSize, tyObject_Table_VhiYQVROvZwCBgplqpTfWg* Result);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, logLoop_Y1QvvdpC0FmKBCafruMWGQ)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, memTrackerWrite)(void* address, NI size, NCSTRING file, NI line);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__cWlFtzNs7sAIHXtL02SHCg)(tyObject_Table_VhiYQVROvZwCBgplqpTfWg& t, NI key, tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* val);
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*, open_SRJkmN7JR2aulOhbafCrYA)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, upgradeSchema_LH14cll3kWhgg7HfQbZIzw)(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* bf);
N_LIB_PRIVATE N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*, setupQuery_6EQAJlzQgp6Lnc8upW20sQ)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
extern "C" N_CDECL(NI32, sqlite3_step)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col);
extern "C" N_CDECL(NCSTRING, sqlite3_column_text)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 iCol);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
extern "C" N_CDECL(NI32, sqlite3_finalize)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pStmt);
N_LIB_PRIVATE N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ch0e5PgaoEZEQHhvsLrGJQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuAlignString)(NimStringDesc* s, NI count, NIM_CHAR padding);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ**, X5BX5D__9bymmKdwETeROM26iiSEzvw)(tyObject_Table_VhiYQVROvZwCBgplqpTfWg& t, NI key);
NI nextid_qcNG8J33Ctn5H8ycDMTLpA;
tyObject_Table_VhiYQVROvZwCBgplqpTfWg id2BudgetFile_tTZwLExyJdLAlwEEzldPEw;
TNimType NTI_yi1kAYh8kb3f1o4vS0ZTBQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_Ocaq0E9cAGvTovUG5l30IXg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_5PWEcVklnzmjVvFuGsuXhQ_;
extern TNimType NTI_VhiYQVROvZwCBgplqpTfWg_;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern tyArray_3elISlPUynt0R48Wr6G2wg migrations_XP1BT1YxTzkGsU62UYEcJQ;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_4, "Opening file ", 13);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_6, "Failed opening: ", 16);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_8, "Upgrading schema ...", 20);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_7 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_8)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_9, "  CREATE TABLE IF NOT EXISTS _schema_version (\012    id INTEGER P"
"RIMARY KEY,\012    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\012   "
" name TEXT UNIQUE\012  )", 148);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_10, "SELECT name FROM _schema_version", 32);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_11, "Applied patches: ", 17);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_13, "-", 1);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_16, "Patch ", 6);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_17, " already applied.", 17);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_18, "applying patch: ", 16);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_19, "BEGIN", 5);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_20, "INSERT INTO _schema_version (name) VALUES (\?)", 45);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_21, "COMMIT", 6);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_22, "error applying patch ", 21);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_23, ": ", 2);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_24, "ROLLBACK", 8);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_27, "Schema upgrade complete", 23);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_26 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_27)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_29, "Done opening budget file", 24);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_28 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_29)}
;
static N_NIMCALL(void, Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ)(void* p, NI op) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* a;
	a = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)p;
	nimGCvisit((void*)(*a).filename, op);
}
static N_NIMCALL(void, TM_Q8GDWOFB5uWKFMQFSo1oVw_3)(void) {
	nimGCvisit((void*)id2BudgetFile_tTZwLExyJdLAlwEEzldPEw.data, 0);
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[(*dest).len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).len + ((NI) 1)))));
		(*dest).len += (*src).len;
}	}
	LA3_: ;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col) {
	NimStringDesc* result;
	NCSTRING T1_;
	nimfr_("[]", "db_sqlite.nim");
	result = (NimStringDesc*)0;
	nimln_(224, "db_sqlite.nim");
	nimln_(225, "db_sqlite.nim");
	T1_ = (NCSTRING)0;
	T1_ = sqlite3_column_text(row, col);
	result = cstrToNimstr(T1_);
	popFrame();
	return result;
}

static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr_("eqStrings", "strmantle.nim");
{	result = (NIM_BOOL)0;
	nimln_(24, "strmantle.nim");
	NI alen = (a ? a->len : 0);
	nimln_(25, "strmantle.nim");
	NI blen = (b ? b->len : 0);
	nimln_(26, "strmantle.nim");
	{
		if (!(alen == blen)) goto LA3_;
{		nimln_(27, "strmantle.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
{			result = NIM_TRUE;
			goto BeforeRet_;
}		}
		LA7_: ;
		nimln_(28, "strmantle.nim");
		result = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
}	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		i = (NimStringDesc*)0;
		nimln_(2302, "system.nim");
		NI i_2 = ((NI) 0);
		{
			nimln_(2303, "system.nim");
			while (1) {
				NI TM_Q8GDWOFB5uWKFMQFSo1oVw_14;
				NI TM_Q8GDWOFB5uWKFMQFSo1oVw_15;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2567, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError2(i_2,aLen_0-1);
				i = a[i_2];
				nimln_(2568, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
{					goto BeforeRet_;
}				}
				LA6_: ;
				nimln_(2569, "system.nim");
				TM_Q8GDWOFB5uWKFMQFSo1oVw_14 = addInt(result, ((NI) 1));
				result = (NI)(TM_Q8GDWOFB5uWKFMQFSo1oVw_14);
				nimln_(2305, "system.nim");
				TM_Q8GDWOFB5uWKFMQFSo1oVw_15 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_Q8GDWOFB5uWKFMQFSo1oVw_15);
			} LA3: ;
		}
	}
	nimln_(2570, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2575, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3588, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void) {
	NimStringDesc* result;
	nimfr_("getCurrentExceptionMsg", "system.nim");
{	result = (NimStringDesc*)0;
	nimln_(3593, "system.nim");
	Exception* e = getCurrentException();
	nimln_(3594, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3_;
{		result = ((NimStringDesc*) NIM_NIL);
}	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, upgradeSchema_LH14cll3kWhgg7HfQbZIzw)(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* bf) {
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T5_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* applied;
	TFrame* _nimCurFrame;
	nimfr_("upgradeSchema", "budgetfile.nim");
	_nimCurFrame = getFrame();
	nimln_(25, "budgetfile.nim");
	{
		nimln_(293, "logging.nim");
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2))) goto LA3_;
{		nimln_(294, "logging.nim");
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2), TM_Q8GDWOFB5uWKFMQFSo1oVw_7, 1);
}	}
	LA3_: ;
	nimln_(28, "budgetfile.nim");
	nimZeroMem((void*)T5_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
	exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_9), T5_, 0);
	applied = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	{
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row;
		tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* colontmp_;
		NimStringDesc* colontmp__2;
		tyArray_8ZvwQIddfpj2THRVPsFzIQ T7_;
		row = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
		colontmp_ = (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*)0;
		colontmp__2 = (NimStringDesc*)0;
		nimln_(35, "budgetfile.nim");
		colontmp_ = (*bf).db;
		colontmp__2 = copyString(((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_10));
		nimln_(181, "db_sqlite.nim");
		nimZeroMem((void*)T7_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* stmt = setupQuery_6EQAJlzQgp6Lnc8upW20sQ(colontmp_, colontmp__2, T7_, 0);
		nimln_(182, "db_sqlite.nim");
		try {
			{
				nimln_(183, "db_sqlite.nim");
				while (1) {
					NI32 T11_;
					NimStringDesc* T12_;
					NI T13_;
					T11_ = (NI32)0;
					T11_ = sqlite3_step(stmt);
					if (!(T11_ == ((NI32) 100))) goto LA10;
					nimln_(35, "budgetfile.nim");
					row = stmt;
					nimln_(36, "budgetfile.nim");
					T12_ = (NimStringDesc*)0;
					T12_ = X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile(row, ((NI32) 0));
					applied = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(applied, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
					T13_ = applied->len++;
					applied->data[T13_] = copyString(T12_);
					memTrackerWrite((void*)(&applied->data[T13_]), 8, "/Users/matt/m/buckets.git/ccore/src/buckets/budgetfile.nim", 36);
				} LA10: ;
			}
		}
		catch (...) {
			nimln_(186, "db_sqlite.nim");
			{
				NI32 T17_;
				nimln_(483, "system.nim");
				nimln_(186, "db_sqlite.nim");
				T17_ = (NI32)0;
				T17_ = sqlite3_finalize(stmt);
				if (!!((T17_ == ((NI32) 0)))) goto LA18_;
{				dbError_yRzNipQFOsKqLVySy7Je9bw(colontmp_);
}			}
			LA18_: ;
			throw;
		}
		{
			{
				NI32 T23_;
				nimln_(483, "system.nim");
				nimln_(186, "db_sqlite.nim");
				T23_ = (NI32)0;
				T23_ = sqlite3_finalize(stmt);
				if (!!((T23_ == ((NI32) 0)))) goto LA24_;
{				dbError_yRzNipQFOsKqLVySy7Je9bw(colontmp_);
}			}
			LA24_: ;
		}
	}
	nimln_(37, "budgetfile.nim");
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T30_;
		NimStringDesc* fmtRes;
		NimStringDesc* T31_;
		nimln_(293, "logging.nim");
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA28_;
{		nimln_(294, "logging.nim");
		nimZeroMem((void*)T30_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		nimln_(37, "budgetfile.nim");
		fmtRes = rawNewString(((NI) 36));
		fmtRes = resizeString(fmtRes, 17);
appendString(fmtRes, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_11));
		nimln_(270, "strformat.nim");
		T31_ = (NimStringDesc*)0;
		T31_ = dollar__ch0e5PgaoEZEQHhvsLrGJQ(applied);
		fmtRes = resizeString(fmtRes, (T31_ ? T31_->len : 0) + 0);
appendString(fmtRes, T31_);
		T30_[0] = copyString(fmtRes);
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T30_, 1);
}	}
	LA28_: ;
	nimln_(40, "budgetfile.nim");
	NI order = ((NI) 0);
	{
		tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg migration;
		nimZeroMem((void*)(&migration), sizeof(tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg));
		nimln_(2316, "system.nim");
		NI i = ((NI) 0);
		nimln_(2317, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 14))) goto LA35_;
{			{
				nimln_(2318, "system.nim");
				while (1) {
					NI TM_Q8GDWOFB5uWKFMQFSo1oVw_25;
					nimln_(41, "budgetfile.nim");
					migration.Field0 = migrations_XP1BT1YxTzkGsU62UYEcJQ[(i)- 0].Field0;
					migration.Field1 = migrations_XP1BT1YxTzkGsU62UYEcJQ[(i)- 0].Field1;
					{
						NI TM_Q8GDWOFB5uWKFMQFSo1oVw_12;
						NimStringDesc* padded_order;
						NimStringDesc* fullname;
						NimStringDesc* fmtRes_2;
						tyArray_8ZvwQIddfpj2THRVPsFzIQ T54_;
						nimln_(42, "budgetfile.nim");
						TM_Q8GDWOFB5uWKFMQFSo1oVw_12 = addInt(order, ((NI) 1));
						order = (NI)(TM_Q8GDWOFB5uWKFMQFSo1oVw_12);
						nimln_(43, "budgetfile.nim");
						padded_order = nsuAlignString(nsuIntToStr(order, ((NI) 1)), ((NI) 4), 48);
						nimln_(44, "budgetfile.nim");
						fmtRes_2 = rawNewString(((NI) 51));
						nimln_(260, "strformat.nim");
						fmtRes_2 = resizeString(fmtRes_2, (padded_order ? padded_order->len : 0) + 0);
appendString(fmtRes_2, padded_order);
						nimln_(44, "budgetfile.nim");
						fmtRes_2 = resizeString(fmtRes_2, 1);
appendString(fmtRes_2, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_13));
						nimln_(260, "strformat.nim");
						fmtRes_2 = resizeString(fmtRes_2, (migration.Field0 ? migration.Field0->len : 0) + 0);
appendString(fmtRes_2, migration.Field0);
						fullname = fmtRes_2;
						nimln_(45, "budgetfile.nim");
						{
							if (!contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile(applied->data, (applied ? applied->len : 0), fullname)) goto LA42_;
{							nimln_(46, "budgetfile.nim");
							{
								tyArray_nHXaesL0DJZHyVS07ARPRA T48_;
								NimStringDesc* fmtRes_3;
								nimln_(293, "logging.nim");
								if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA46_;
{								nimln_(294, "logging.nim");
								nimZeroMem((void*)T48_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
								nimln_(46, "budgetfile.nim");
								fmtRes_3 = rawNewString(((NI) 43));
								fmtRes_3 = resizeString(fmtRes_3, 6);
appendString(fmtRes_3, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_16));
								nimln_(260, "strformat.nim");
								fmtRes_3 = resizeString(fmtRes_3, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_3, fullname);
								nimln_(46, "budgetfile.nim");
								fmtRes_3 = resizeString(fmtRes_3, 17);
appendString(fmtRes_3, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_17));
								T48_[0] = copyString(fmtRes_3);
								logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T48_, 1);
}							}
							LA46_: ;
							nimln_(47, "budgetfile.nim");
							goto LA39;
}						}
						LA42_: ;
						nimln_(48, "budgetfile.nim");
						{
							tyArray_nHXaesL0DJZHyVS07ARPRA T53_;
							NimStringDesc* fmtRes_4;
							nimln_(293, "logging.nim");
							if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2))) goto LA51_;
{							nimln_(294, "logging.nim");
							nimZeroMem((void*)T53_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
							nimln_(48, "budgetfile.nim");
							fmtRes_4 = rawNewString(((NI) 36));
							fmtRes_4 = resizeString(fmtRes_4, 16);
appendString(fmtRes_4, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_18));
							nimln_(260, "strformat.nim");
							fmtRes_4 = resizeString(fmtRes_4, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_4, fullname);
							T53_[0] = copyString(fmtRes_4);
							logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2), T53_, 1);
}						}
						LA51_: ;
						nimln_(49, "budgetfile.nim");
						nimZeroMem((void*)T54_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
						exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_19), T54_, 0);
						nimln_(50, "budgetfile.nim");
						try {
							tyArray_nHXaesL0DJZHyVS07ARPRA T56_;
							tyArray_8ZvwQIddfpj2THRVPsFzIQ T57_;
							nimln_(51, "budgetfile.nim");
							migration.Field1((*bf).db);
							nimln_(52, "budgetfile.nim");
							nimZeroMem((void*)T56_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
							T56_[0] = copyString(fullname);
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_20), T56_, 1);
							nimln_(53, "budgetfile.nim");
							nimZeroMem((void*)T57_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_21), T57_, 0);
						}
						catch (...) {
							tyArray_8ZvwQIddfpj2THRVPsFzIQ T65_;
							setFrame(_nimCurFrame);
							nimln_(55, "budgetfile.nim");
							{
								tyArray_nHXaesL0DJZHyVS07ARPRA T63_;
								NimStringDesc* fmtRes_5;
								NimStringDesc* T64_;
								nimln_(293, "logging.nim");
								if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 5))) goto LA61_;
{								nimln_(294, "logging.nim");
								nimZeroMem((void*)T63_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
								nimln_(55, "budgetfile.nim");
								fmtRes_5 = rawNewString(((NI) 79));
								fmtRes_5 = resizeString(fmtRes_5, 21);
appendString(fmtRes_5, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_22));
								nimln_(260, "strformat.nim");
								fmtRes_5 = resizeString(fmtRes_5, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_5, fullname);
								nimln_(55, "budgetfile.nim");
								fmtRes_5 = resizeString(fmtRes_5, 2);
appendString(fmtRes_5, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_23));
								nimln_(260, "strformat.nim");
								nimln_(315, "strformat.nim");
								T64_ = (NimStringDesc*)0;
								T64_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile();
								fmtRes_5 = resizeString(fmtRes_5, (T64_ ? T64_->len : 0) + 0);
appendString(fmtRes_5, T64_);
								T63_[0] = copyString(fmtRes_5);
								logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 5), T63_, 1);
}							}
							LA61_: ;
							nimln_(56, "budgetfile.nim");
							nimZeroMem((void*)T65_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_24), T65_, 0);
							nimln_(57, "budgetfile.nim");
							throw;
						}
					} LA39: ;
					nimln_(2320, "system.nim");
					{
						if (!(((NI) 14) <= ((NI) (i)))) goto LA68_;
{						goto LA37;
}					}
					LA68_: ;
					nimln_(2321, "system.nim");
					TM_Q8GDWOFB5uWKFMQFSo1oVw_25 = addInt(i, ((NI) 1));
					if (TM_Q8GDWOFB5uWKFMQFSo1oVw_25 < 0 || TM_Q8GDWOFB5uWKFMQFSo1oVw_25 > 14) raiseOverflow();
					i = (NI)(TM_Q8GDWOFB5uWKFMQFSo1oVw_25);
				}
			} LA37: ;
}		}
		LA35_: ;
	}
	nimln_(58, "budgetfile.nim");
	{
		nimln_(293, "logging.nim");
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2))) goto LA72_;
{		nimln_(294, "logging.nim");
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2), TM_Q8GDWOFB5uWKFMQFSo1oVw_26, 1);
}	}
	LA72_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, openBudgetFile_WkDTJ1JqGfRfDWV2gutrmw)(NimStringDesc* filename) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* result;
	NI TM_Q8GDWOFB5uWKFMQFSo1oVw_5;
	TFrame* _nimCurFrame;
	nimfr_("openBudgetFile", "budgetfile.nim");
	_nimCurFrame = getFrame();
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)0;
	nimln_(62, "budgetfile.nim");
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*) newObj((&NTI_5PWEcVklnzmjVvFuGsuXhQ_), sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ));
	nimln_(63, "budgetfile.nim");
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
		NimStringDesc* fmtRes;
		nimln_(293, "logging.nim");
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2))) goto LA3_;
{		nimln_(294, "logging.nim");
		nimZeroMem((void*)T5_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		nimln_(63, "budgetfile.nim");
		fmtRes = rawNewString(((NI) 33));
		fmtRes = resizeString(fmtRes, 13);
appendString(fmtRes, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_4));
		nimln_(260, "strformat.nim");
		fmtRes = resizeString(fmtRes, (filename ? filename->len : 0) + 0);
appendString(fmtRes, filename);
		T5_[0] = copyString(fmtRes);
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2), T5_, 1);
}	}
	LA3_: ;
	nimln_(64, "budgetfile.nim");
	(*result).id = nextid_qcNG8J33Ctn5H8ycDMTLpA;
	memTrackerWrite((void*)(&(*result).id), 8, "/Users/matt/m/buckets.git/ccore/src/buckets/budgetfile.nim", 64);
	nimln_(65, "budgetfile.nim");
	TM_Q8GDWOFB5uWKFMQFSo1oVw_5 = addInt(nextid_qcNG8J33Ctn5H8ycDMTLpA, ((NI) 1));
	nextid_qcNG8J33Ctn5H8ycDMTLpA = (NI)(TM_Q8GDWOFB5uWKFMQFSo1oVw_5);
	memTrackerWrite((void*)(&nextid_qcNG8J33Ctn5H8ycDMTLpA), 8, "/Users/matt/lib/Nim/lib/system.nim", 740);
	nimln_(66, "budgetfile.nim");
	X5BX5Deq__cWlFtzNs7sAIHXtL02SHCg(id2BudgetFile_tTZwLExyJdLAlwEEzldPEw, (*result).id, result);
	nimln_(67, "budgetfile.nim");
	try {
		nimln_(68, "budgetfile.nim");
		(*result).db = open_SRJkmN7JR2aulOhbafCrYA(filename, ((NimStringDesc*) NIM_NIL), ((NimStringDesc*) NIM_NIL), ((NimStringDesc*) NIM_NIL));
	}
	catch (tyObject_DbError_9cp8FUMATyqFmLaAKCXEjCQ&) {
		tyArray_Re75IspeoxXy2oCZHwcRrA T8_;
		setFrame(_nimCurFrame);
		nimln_(70, "budgetfile.nim");
		nimZeroMem((void*)T8_, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
		T8_[0] = copyString(((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_6));
		T8_[1] = copyString(filename);
		echoBinSafe(T8_, 2);
		nimln_(71, "budgetfile.nim");
		throw;
	}
	nimln_(72, "budgetfile.nim");
	(*result).filename = copyString(filename);
	memTrackerWrite((void*)(&(*result).filename), 8, "/Users/matt/m/buckets.git/ccore/src/buckets/budgetfile.nim", 72);
	nimln_(73, "budgetfile.nim");
	upgradeSchema_LH14cll3kWhgg7HfQbZIzw(result);
	nimln_(74, "budgetfile.nim");
	{
		nimln_(293, "logging.nim");
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA11_;
{		nimln_(294, "logging.nim");
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_28, 1);
}	}
	LA11_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ)(NI id) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* result;
	nimfr_("getBudgetFile", "budgetfile.nim");
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)0;
	nimln_(77, "budgetfile.nim");
	nimln_(78, "budgetfile.nim");
	result = (*X5BX5D__9bymmKdwETeROM26iiSEzvw(id2BudgetFile_tTZwLExyJdLAlwEEzldPEw, id));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
}
	nimfr_("budgetfile", "budgetfile.nim");
nimRegisterGlobalMarker(TM_Q8GDWOFB5uWKFMQFSo1oVw_3);
	nimln_(20, "budgetfile.nim");
	initTable_jqzpDgYBM9aUAc5X3WbaZOA(((NI) 64), (&id2BudgetFile_tTZwLExyJdLAlwEEzldPEw));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileDatInit000)(void) {
static TNimNode* TM_Q8GDWOFB5uWKFMQFSo1oVw_2[3];
static TNimNode TM_Q8GDWOFB5uWKFMQFSo1oVw_0[4];
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.size = sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ);
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.kind = 18;
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.base = 0;
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.flags = 2;
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[0] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, id);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].name = "id";
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[1] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, db);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].typ = (&NTI_Ocaq0E9cAGvTovUG5l30IXg_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].name = "db";
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[2] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, filename);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].name = "filename";
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].len = 3; TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].kind = 2; TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].sons = &TM_Q8GDWOFB5uWKFMQFSo1oVw_2[0];
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.node = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0];
NTI_5PWEcVklnzmjVvFuGsuXhQ_.size = sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*);
NTI_5PWEcVklnzmjVvFuGsuXhQ_.kind = 22;
NTI_5PWEcVklnzmjVvFuGsuXhQ_.base = (&NTI_yi1kAYh8kb3f1o4vS0ZTBQ_);
NTI_5PWEcVklnzmjVvFuGsuXhQ_.flags = 2;
NTI_5PWEcVklnzmjVvFuGsuXhQ_.marker = Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ;
}

