/* Generated by Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStringDesc;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR tyUncheckedArray_py3s8sMDoAoBkn8uuh0ZzQ[1];
struct NimStringDesc : public TGenericSeq {
tyUncheckedArray_py3s8sMDoAoBkn8uuh0ZzQ data;
};
typedef NU8 tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA, parseEnum_F2m6TxOYlOgS9b1zJlysJMw)(NimStringDesc* s, tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA default_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
TNimType NTI_1nKXODQf4pVTsjJDOlhgTA_;
STRING_LITERAL(TM_N9cGyzi9aEspHXroBx9c4suKA_5, "Not implemented yet", 19);
STRING_LITERAL(TM_N9cGyzi9aEspHXroBx9c4suKA_6, "Unknown function", 16);

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, stringRPC_NXNco20FAG0NBry9bX8ez9cA)(NimStringDesc* command, NimStringDesc* arg) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA cmd = parseEnum_F2m6TxOYlOgS9b1zJlysJMw(command, ((tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA) 0));
	switch (cmd) {
	case ((tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA) 1):
	{
		result = copyString(arg);
	}
	break;
	case ((tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA) 2):
	{
		result = copyString(((NimStringDesc*) &TM_N9cGyzi9aEspHXroBx9c4suKA_5));
	}
	break;
	case ((tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA) 0):
	{
		result = copyString(((NimStringDesc*) &TM_N9cGyzi9aEspHXroBx9c4suKA_6));
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, buckets_bucketsInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
}
}

N_LIB_PRIVATE N_NIMCALL(void, buckets_bucketsDatInit000)(void) {
static TNimNode* TM_N9cGyzi9aEspHXroBx9c4suKA_2[3];
NI TM_N9cGyzi9aEspHXroBx9c4suKA_4;
static char* NIM_CONST TM_N9cGyzi9aEspHXroBx9c4suKA_3[3] = {
"Unknown", 
"Echo", 
"Exec"};
static TNimNode TM_N9cGyzi9aEspHXroBx9c4suKA_0[4];
NTI_1nKXODQf4pVTsjJDOlhgTA_.size = sizeof(tyEnum_Commands_1nKXODQf4pVTsjJDOlhgTA);
NTI_1nKXODQf4pVTsjJDOlhgTA_.kind = 14;
NTI_1nKXODQf4pVTsjJDOlhgTA_.base = 0;
NTI_1nKXODQf4pVTsjJDOlhgTA_.flags = 3;
for (TM_N9cGyzi9aEspHXroBx9c4suKA_4 = 0; TM_N9cGyzi9aEspHXroBx9c4suKA_4 < 3; TM_N9cGyzi9aEspHXroBx9c4suKA_4++) {
TM_N9cGyzi9aEspHXroBx9c4suKA_0[TM_N9cGyzi9aEspHXroBx9c4suKA_4+0].kind = 1;
TM_N9cGyzi9aEspHXroBx9c4suKA_0[TM_N9cGyzi9aEspHXroBx9c4suKA_4+0].offset = TM_N9cGyzi9aEspHXroBx9c4suKA_4;
TM_N9cGyzi9aEspHXroBx9c4suKA_0[TM_N9cGyzi9aEspHXroBx9c4suKA_4+0].name = TM_N9cGyzi9aEspHXroBx9c4suKA_3[TM_N9cGyzi9aEspHXroBx9c4suKA_4];
TM_N9cGyzi9aEspHXroBx9c4suKA_2[TM_N9cGyzi9aEspHXroBx9c4suKA_4] = &TM_N9cGyzi9aEspHXroBx9c4suKA_0[TM_N9cGyzi9aEspHXroBx9c4suKA_4+0];
}
TM_N9cGyzi9aEspHXroBx9c4suKA_0[3].len = 3; TM_N9cGyzi9aEspHXroBx9c4suKA_0[3].kind = 2; TM_N9cGyzi9aEspHXroBx9c4suKA_0[3].sons = &TM_N9cGyzi9aEspHXroBx9c4suKA_2[0];
NTI_1nKXODQf4pVTsjJDOlhgTA_.node = &TM_N9cGyzi9aEspHXroBx9c4suKA_0[3];
}

