/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#include <new>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct NimStringDesc;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct tySequence_AHQ350tguQkj2pXJTiVQzw;
struct tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ;
struct tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ;
struct RootObj;
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA;
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ;
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
struct tySequence_EQ6L4H42GvMcXeqG7p5fZw;
struct tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q;
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
struct tyObject_OrderedTable_ZZvSdVkA2s2sIyifu4cpkg;
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
struct Exception;
struct tySequence_uB9b75OUPRENsBAu4AnoePA;
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
struct tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ;
struct tySequence_phjbYJtsbOIAYa9be34hhZg;
struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ;
struct tySequence_lmmAXZV2yeOkTTvh7ZeG9cA;
struct tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA;
struct tyObject_AssertionError_G9cUlLvU4AFC26wbFxLFkFA;
struct tyObject_Defect_LbeSGvgPzGzXnW9caIkJqMA;
struct tyObject_RollingFileLoggercolonObjectType__RVbeT0aVEu0OfdbVn1KX0g;
struct tyObject_FileLoggercolonObjectType__IRs4hY6GNcXZ1akep9cf7jA;
struct tyObject_ConsoleLoggercolonObjectType__4w707i5soOx7A2LWkxurNA;
struct tyTuple_awOivLjlO76sGdHY7nQUjQ;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING msg);
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
struct RootObj {
TNimType* m_type;
};
struct tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ : public RootObj {
tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold;
NimStringDesc* fmtStr;
};
struct tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ : public tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ {
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ {
NI id;
tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db;
NimStringDesc* filename;
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_ZZvSdVkA2s2sIyifu4cpkg {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
};
struct {NI64 num;
};
struct {NF fnum;
};
struct {NIM_BOOL bval;
};
struct {tyObject_OrderedTable_ZZvSdVkA2s2sIyifu4cpkg fields;
};
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
};
};
};
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
struct Exception : public RootObj {
virtual void raise() {throw *this;}
~Exception() {if(this->raiseId) popCurrentExceptionEx(this->raiseId);}
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raiseId;
Exception* up;
};
struct tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA : public Exception {
virtual void raise() {throw *this;}
};
struct tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ {
tySequence_phjbYJtsbOIAYa9be34hhZg* rows;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* cols;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* types;
};
struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ {
NimStringDesc* Field0;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field1;
};
typedef tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyArray_rhtWm6uYOU6da9bZDT6ryDA[4];
typedef tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyArray_rnBfBeuXQMeTae3dUyC1Bw[2];
struct tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA {
NI64 lastID;
};
struct tyObject_Defect_LbeSGvgPzGzXnW9caIkJqMA : public Exception {
virtual void raise() {throw *this;}
};
struct tyObject_AssertionError_G9cUlLvU4AFC26wbFxLFkFA : public tyObject_Defect_LbeSGvgPzGzXnW9caIkJqMA {
virtual void raise() {throw *this;}
};
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ : TGenericSeq {
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_AHQ350tguQkj2pXJTiVQzw : TGenericSeq {
  tyProc_5cp59bim9aJ4WupX5aVaD1Sg data[SEQ_DECL_SIZE];
};
struct tySequence_EQ6L4H42GvMcXeqG7p5fZw : TGenericSeq {
  tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ : TGenericSeq {
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence_phjbYJtsbOIAYa9be34hhZg : TGenericSeq {
  tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data[SEQ_DECL_SIZE];
};
struct tySequence_lmmAXZV2yeOkTTvh7ZeG9cA : TGenericSeq {
  tyTuple_jq7X5k7hWG0tdTZTDkiyGQ data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g : TGenericSeq {
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA : TGenericSeq {
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_GqwyQEukm0XJRh6VvuDcmA_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, Marker_tySequence_AHQ350tguQkj2pXJTiVQzw)(void* p, NI op);
static N_NIMCALL(void, TM_GqwyQEukm0XJRh6VvuDcmA_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, log_wsjRFKCkSU1CgTpE6DRsrg)(tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substituteLog_GUiLaZ0b21eA2W7LstPGkg)(NimStringDesc* frmt, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NCSTRING, buckets_version)(void);
N_NIMCALL(NCSTRING, buckets_stringpc)(NCSTRING command, NCSTRING arg, NI arglen);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, stringRPC_NXNco20FAG0NBry9bX8ez9cA)(NimStringDesc* command, NimStringDesc* arg);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, buckets_register_logger)(tyProc_5cp59bim9aJ4WupX5aVaD1Sg fn);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_INLINE(void, asgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isOnStack_dJJW59cIgsBmT59aZrOM71Mg)(void* p);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace_njssp69aa7hvxte9bJ8uuDcg)(void);
static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw)(tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg* a, void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_a1qK8gNpfISO1NXnbbEzHw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, addHandler_JMzV3oNQoqgx3BNo3w87bg)(tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ* handler);
N_NIMCALL(NI, buckets_openfile)(NCSTRING filename);
N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, openBudgetFile_WkDTJ1JqGfRfDWV2gutrmw)(NimStringDesc* filename);
N_NIMCALL(NCSTRING, buckets_db_all_json)(NI budget_handle, NCSTRING query, NCSTRING params_json);
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ)(NI id);
N_LIB_PRIVATE N_NIMCALL(tySequence_EQ6L4H42GvMcXeqG7p5fZw*, json_to_params_gVVWMJkILSzPVaoeCq1GHg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING query, NCSTRING params_json);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_q2jt59czHU4BW88Mb7EJDUA)(NimStringDesc* buffer);
N_LIB_PRIVATE N_NIMCALL(tySequence_oLpBKXzW3hF9aCVMo5EymfQ*, getElems_ES84hcmEkNlkkNKiutnPbg)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, tySequence_oLpBKXzW3hF9aCVMo5EymfQ* default_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_opUVQPa4k9aAgZsg9aKPuaog)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, getInt_rDQb9chpfbduaO7rsIalSMw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NI default_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_k5IcRUo9cf7SwFKByll2iag)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr_z2Itmc4KJ7uMBtaTVQ09cqw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NimStringDesc* default_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_j5FS2km0qtRufvzb6B7zHQ)(NF x);
N_LIB_PRIVATE N_NIMCALL(NF, getFloat_Cc9ayyBhVu0SPW8c9adrFiQA)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NF default_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_U4CJLW4cl5UxoEpwDyohCg)(void* x);
N_LIB_PRIVATE N_NIMCALL(tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*, newParam_Ij8X9aQmqY59ae9bP3wiQ79azA)(NIM_BOOL x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, getBool_8bAmYR2oBpeYFwvomDc8dg)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NIM_BOOL default_0);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_NIMCALL(void, Marker_tySequence_EQ6L4H42GvMcXeqG7p5fZw)(void* p, NI op);
extern "C" N_CDECL(int, sqlite3_prepare_v2)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING zSql, int nByte, tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*& ppStmt, NCSTRING* pzTail);
static N_INLINE(size_t, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) __attribute__((noreturn));
extern "C" N_CDECL(NI32, sqlite3_bind_parameter_count)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
extern "C" N_CDECL(NCSTRING, sqlite3_bind_parameter_name)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 para2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_VczJ0fz1o49a9ajsD9cvbBPBQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* key);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggclib)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__3MszA1IsDLkWcBk0f4ZIOQ)(tyObject_OrderedTable_ZZvSdVkA2s2sIyifu4cpkg& t, NimStringDesc* key);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ*, fetchAll_pXpsWPv7osnhxTUlJNRtlw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* statement, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJObject_phgxr9cKlc0dmrJpCth52pw_2)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJArray_phgxr9cKlc0dmrJpCth52pw_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, add_NE4BWkXVxUMFtDmmA5ZcHw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* child);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJString_8iXO9aRAijCPe58pujCBbuQ_2)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, add_n3qm2zfwLtoWXXf3UIj9aeg)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(void, toUgly_5SA9aXRryVJvgoCag29cRzQw)(NimStringDesc*& result, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__9bR9b9aepApwIZEZZtX9cb7RFA)(tyTuple_jq7X5k7hWG0tdTZTDkiyGQ* keyVals, NI keyValsLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__8iXO9aRAijCPe58pujCBbuQ_3)(NimStringDesc* s);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, keepString_NmPLFe10r6PjDoUK2efLMw)(NimStringDesc* x);
N_NIMCALL(NCSTRING, buckets_db_run_json)(NI budget_handle, NCSTRING query, NCSTRING params_json);
N_LIB_PRIVATE N_NIMCALL(tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA*, runQuery_ZvHm6eg9bqWl9arKUfiSea6w)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__z0g83xvrx4R10lOvgItZ9aQ_2)(NI64 n);
N_NIMCALL(NCSTRING, buckets_db_execute_many_json)(NI budget_handle, NCSTRING queries_json);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, jsonStringToStringSeq_yoZz9aBtjaT9bqb6xITm9cC9bA)(NCSTRING jsonstring);
N_LIB_PRIVATE N_NIMCALL(void, executeMany_WszC4nheyy9bsMXF4tK0v1Q)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc** statements, NI statementsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_NIMCALL(void, chckNilDisp)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, log_rG6osqE0luZSJUlLifxyVg)(tyObject_RollingFileLoggercolonObjectType__RVbeT0aVEu0OfdbVn1KX0g* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_yEa9cUwzxhGRtg9cspcfCIHg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NIMCALL(void, log_m2nFIuqvJSzncok28dY8Kg)(tyObject_FileLoggercolonObjectType__IRs4hY6GNcXZ1akep9cf7jA* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_A500h04AJ9cHQgD9ad6BzDYw)(tyObject_ConsoleLoggercolonObjectType__4w707i5soOx7A2LWkxurNA* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_2EMZHteAOCjvMWyiczAS7w)(tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_posixInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_osInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_loggingDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_loggingInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_sqlite3DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_streamsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_lexbaseDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parsejsonDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_jsonDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_db_commonDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_dbDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_dbschemaDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_dbschemaInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, buckets_bucketsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, clibDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
tySequence_AHQ350tguQkj2pXJTiVQzw* LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw;
TNimType NTI_5cp59bim9aJ4WupX5aVaD1Sg_;
TNimType NTI_AHQ350tguQkj2pXJTiVQzw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_9bhietBQiofDPLK3sBa0qPQ_;
TNimType NTI_pZbUChI2wyLci5Jc82XTOQ_;
TNimType NTI_a1qK8gNpfISO1NXnbbEzHw_;
extern TNimType NTI_oLpBKXzW3hF9aCVMo5EymfQ_;
extern TNimType NTI_gcKyg9bhR5vWTJg3cREMk0Q_;
extern TNimType NTI_qrLSDoe2oBoAqNtJ9badtnA_;
extern TNimType NTI_RUngo7nCHe6O8aBGIcrhtg_;
extern TNimType NTI_E0cTKF9afYzykvtJvV8SvRA_;
TNimType NTI_EQ6L4H42GvMcXeqG7p5fZw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI_lmmAXZV2yeOkTTvh7ZeG9cA_;
extern TNimType NTI_RVbeT0aVEu0OfdbVn1KX0g_;
extern TNimType NTI_IRs4hY6GNcXZ1akep9cf7jA_;
static TNimType* Nim_OfCheck_CACHE44[2];
extern TNimType NTI_4w707i5soOx7A2LWkxurNA_;
static TNimType* Nim_OfCheck_CACHE45[2];
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_5, "/Users/matt/lib/Nim/lib/system.nim(4015, 11) `len(a) == L` seq "
"modified while iterating over it", 95);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_6, "0.1.0", 5);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_8, "[GCASSERT] ", 11);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_9, "asgnRef", 7);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_7 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_8),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_9)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_11, "incRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_10 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_8),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_11)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_13, "decRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_12 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_8),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_13)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_15, "decRef", 6);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_14 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_8),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_15)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_16, "/Users/matt/m/buckets.git/ccore/src/buckets/clib.nim(97, 9) `pa"
"rsed.kind == JArray or parsed.kind == JObject` Only Arrays and O"
"bjects are supported for db params", 161);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_17, "Unsupported argument type:", 26);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_19, "/Users/matt/lib/Nim/lib/pure/json.nim(478, 9) `not isNil(node)`"
" ", 64);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_20, "/Users/matt/lib/Nim/lib/pure/json.nim(479, 9) `node.kind == JOb"
"ject` ", 69);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_21, "fields", 6);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_22, "Missing value for parameter: ", 29);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_24, "[SYSASSERT] ", 12);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_25, "begin nimGCunrefNoCycle", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_23 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_24),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_25)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_27, "end nimGCunrefNoCycle 5", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_GqwyQEukm0XJRh6VvuDcmA_26 = {((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_24),
((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_27)}
;
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_29, "Invalid argument type for db params", 35);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_34, "err", 3);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_35, "cols", 4);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_36, "rows", 4);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_37, "types", 5);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_38, "lastID", 6);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_39, "/Users/matt/m/buckets.git/ccore/src/buckets/clib.nim(190, 12) `"
"node.kind == JArray` ", 84);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_40, "/Users/matt/lib/Nim/lib/pure/json.nim(746, 10) `node.kind == JA"
"rray` ", 69);
STRING_LITERAL(TM_GqwyQEukm0XJRh6VvuDcmA_41, "elems", 5);
static N_NIMCALL(void, TM_GqwyQEukm0XJRh6VvuDcmA_2)(void) {
	nimGCvisit((void*)STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA, 0);
}
static N_NIMCALL(void, Marker_tySequence_AHQ350tguQkj2pXJTiVQzw)(void* p, NI op) {
	tySequence_AHQ350tguQkj2pXJTiVQzw* a;
	NI T1_;
	a = (tySequence_AHQ350tguQkj2pXJTiVQzw*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, TM_GqwyQEukm0XJRh6VvuDcmA_3)(void) {
	nimGCvisit((void*)LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw, 0);
}

static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == NIM_NIL);
		if (T3_) goto LA4_;
		T3_ = ((*s).len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = "";
}	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, log_wsjRFKCkSU1CgTpE6DRsrg)(tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "clib.nim");
	nimln_(39, "clib.nim");
	{
		NimStringDesc* ln;
		if (!((*logger).levelThreshold <= level)) goto LA3_;
{		nimln_(40, "clib.nim");
		ln = substituteLog_GUiLaZ0b21eA2W7LstPGkg((*logger).fmtStr, level, args, argsLen_0);
		{
			tyProc_5cp59bim9aJ4WupX5aVaD1Sg fn;
			NI T6_;
			fn = (tyProc_5cp59bim9aJ4WupX5aVaD1Sg)0;
			nimln_(4010, "system.nim");
			NI i = ((NI) 0);
			nimln_(4011, "system.nim");
			T6_ = (LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw ? LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len : 0);
			NI L = T6_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					NI TM_GqwyQEukm0XJRh6VvuDcmA_4;
					if (!(i < L)) goto LA8;
					nimln_(41, "clib.nim");
					if ((NU)(i) >= (NU)(LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw ? LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len : 0)) raiseIndexError2(i,(LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw ? LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len : 0)-1);
					fn = LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->data[i];
					nimln_(42, "clib.nim");
					fn(nimToCStringConv(ln));
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_4 = addInt(i, ((NI) 1));
					i = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_4);
					nimln_(4015, "system.nim");
					{
						NI T11_;
						T11_ = (LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw ? LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len : 0);
						if (!!((T11_ == L))) goto LA12_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA12_: ;
				} LA8: ;
			}
		}
}	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(NCSTRING, buckets_version)(void) {
	NCSTRING result;
	nimfr_("buckets_version", "clib.nim");
	result = (NCSTRING)0;
	nimln_(54, "clib.nim");
	result = nimToCStringConv(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_6));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

N_NIMCALL(NCSTRING, buckets_stringpc)(NCSTRING command, NCSTRING arg, NI arglen) {
	NCSTRING result;
	NimStringDesc* fullarg;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("buckets_stringpc", "clib.nim");
	result = (NCSTRING)0;
	fullarg = (NimStringDesc*)0;
	nimln_(61, "clib.nim");
	fullarg = mnewString(((NI)chckRange(arglen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(62, "clib.nim");
	if ((NU)(((NI) 0)) >= (NU)(fullarg ? fullarg->len : 0)) raiseIndexError2(((NI) 0),(fullarg ? fullarg->len : 0)-1);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&fullarg->data[((NI) 0)]))), ((void*) (arg)), ((NI)chckRange(arglen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(63, "clib.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = cstrToNimstr(command);
	T2_ = (NimStringDesc*)0;
	T2_ = stringRPC_NXNco20FAG0NBry9bX8ez9cA(T1_, fullarg);
	result = nimToCStringConv(T2_);
	popFrame();
	return result;
}

static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void) {
	gch_IcYaEuuWivYAS86vFMTS3Q.recGcLock += ((NI) 1);
}

static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(174, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(174, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_10, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(175, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(125, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(187, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw(gch_IcYaEuuWivYAS86vFMTS3Q.zct, c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(190, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(190, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_12, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(191, "gc.nim");
	{
		nimln_(106, "gc.nim");
		nimln_(191, "gc.nim");
		if (!!(((NU64)(((NI) 8)) <= (NU64)((*c).refcount)))) goto LA8_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_14, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA8_: ;
	nimln_(192, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	nimln_(193, "gc.nim");
	{
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA12_;
{		nimln_(194, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system(c);
}	}
	LA12_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(227, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(227, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isOnStack_dJJW59cIgsBmT59aZrOM71Mg(((void*) (dest)));
		if (!!(!(T3_))) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_7, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(229, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!((src == NIM_NIL))) goto LA8_;
{		nimln_(229, "gc.nim");
		incRef_MV4BBk6J1qu70IbBxwEn4wsystem(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src));
}	}
	LA8_: ;
	nimln_(230, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA12_;
{		nimln_(230, "gc.nim");
		decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest)));
}	}
	LA12_: ;
	nimln_(231, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_a1qK8gNpfISO1NXnbbEzHw)(void* p, NI op) {
	tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ* a;
	a = (tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ*)p;
	nimGCvisit((void*)(*a).fmtStr, op);
}

N_NIMCALL(void, buckets_register_logger)(tyProc_5cp59bim9aJ4WupX5aVaD1Sg fn) {
	NI T1_;
	nimfr_("buckets_register_logger", "clib.nim");
	nimln_(68, "clib.nim");
	asgnRef((void**) (&LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw), (tySequence_AHQ350tguQkj2pXJTiVQzw*) incrSeqV3(LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw, (&NTI_AHQ350tguQkj2pXJTiVQzw_)));
	T1_ = LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len++;
	LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->data[T1_] = fn;
	nimln_(69, "clib.nim");
	{
		NI T4_;
		tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ* logger;
		T4_ = (LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw ? LOG_FUNCTIONS_B8Yy0aQGu06mYt0gns35Xw->len : 0);
		if (!(T4_ == ((NI) 1))) goto LA5_;
{		logger = (tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ*)0;
		nimln_(71, "clib.nim");
		logger = (tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ*) newObj((&NTI_a1qK8gNpfISO1NXnbbEzHw_), sizeof(tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ));
		(*logger).m_type = (&NTI_pZbUChI2wyLci5Jc82XTOQ_);
		nimln_(72, "clib.nim");
		addHandler_JMzV3oNQoqgx3BNo3w87bg(logger);
}	}
	LA5_: ;
	popFrame();
}

N_NIMCALL(NI, buckets_openfile)(NCSTRING filename) {
	NI result;
	NimStringDesc* T1_;
	nimfr_("buckets_openfile", "clib.nim");
	result = (NI)0;
	nimln_(75, "clib.nim");
	nimln_(76, "clib.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = cstrToNimstr(filename);
	result = (*openBudgetFile_WkDTJ1JqGfRfDWV2gutrmw(T1_)).id;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[(*dest).len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).len + ((NI) 1)))));
		(*dest).len += (*src).len;
}	}
	LA3_: ;
}
static N_NIMCALL(void, Marker_tySequence_EQ6L4H42GvMcXeqG7p5fZw)(void* p, NI op) {
	tySequence_EQ6L4H42GvMcXeqG7p5fZw* a;
	NI T1_;
	a = (tySequence_EQ6L4H42GvMcXeqG7p5fZw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(size_t, nimCStrLen)(NCSTRING a) {
	size_t result;
	result = (size_t)0;
	result = strlen(a);
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggclib)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("[]", "json.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(478, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_19));
}	}
	LA3_: ;
	nimln_(479, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_20));
}	}
	LA7_: ;
	nimln_(482, "json.nim");
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_21));
	result = (*X5BX5D__3MszA1IsDLkWcBk0f4ZIOQ((*node).fields, name));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(218, "gc.nim");
	{
		if (!NIM_FALSE) goto LA3_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_23, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA3_: ;
	nimln_(219, "gc.nim");
	decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p));
	nimln_(220, "gc.nim");
	{
		if (!NIM_FALSE) goto LA7_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_GqwyQEukm0XJRh6VvuDcmA_26, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA7_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tySequence_EQ6L4H42GvMcXeqG7p5fZw*, json_to_params_gVVWMJkILSzPVaoeCq1GHg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING query, NCSTRING params_json) {
	tySequence_EQ6L4H42GvMcXeqG7p5fZw* result;
	NimStringDesc* T1_;
	nimfr_("json_to_params", "clib.nim");
	result = (tySequence_EQ6L4H42GvMcXeqG7p5fZw*)0;
	nimln_(96, "clib.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = cstrToNimstr(params_json);
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* parsed = parseJson_q2jt59czHU4BW88Mb7EJDUA(T1_);
	nimln_(97, "clib.nim");
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*parsed).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6));
		if (T4_) goto LA5_;
		T4_ = ((*parsed).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5));
		LA5_: ;
		if (!!(T4_)) goto LA6_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_16));
}	}
	LA6_: ;
	nimln_(98, "clib.nim");
	switch ((*parsed).kind) {
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
	{
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* item;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* colontmp_;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* T10_;
			NI T11_;
			item = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			colontmp_ = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			nimln_(100, "clib.nim");
			T10_ = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			T10_ = NIM_NIL;
			colontmp_ = getElems_ES84hcmEkNlkkNKiutnPbg(parsed, T10_);
			nimln_(4010, "system.nim");
			NI i = ((NI) 0);
			nimln_(4011, "system.nim");
			T11_ = (colontmp_ ? colontmp_->len : 0);
			NI L = T11_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* T14_;
					NI T22_;
					NI TM_GqwyQEukm0XJRh6VvuDcmA_18;
					if (!(i < L)) goto LA13;
					nimln_(100, "clib.nim");
					if ((NU)(i) >= (NU)(colontmp_ ? colontmp_->len : 0)) raiseIndexError2(i,(colontmp_ ? colontmp_->len : 0)-1);
					item = colontmp_->data[i];
					nimln_(101, "clib.nim");
					T14_ = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
					switch ((*item).kind) {
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 2):
					{
						nimln_(81, "clib.nim");
						T14_ = newParam_opUVQPa4k9aAgZsg9aKPuaog(getInt_rDQb9chpfbduaO7rsIalSMw(item, ((NI) 0)));
					}
					break;
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4):
					{
						nimln_(83, "clib.nim");
						T14_ = newParam_k5IcRUo9cf7SwFKByll2iag(getStr_z2Itmc4KJ7uMBtaTVQ09cqw(item, ((NimStringDesc*) NIM_NIL)));
					}
					break;
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 3):
					{
						nimln_(85, "clib.nim");
						T14_ = newParam_j5FS2km0qtRufvzb6B7zHQ(getFloat_Cc9ayyBhVu0SPW8c9adrFiQA(item, 0.0));
					}
					break;
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 0):
					{
						nimln_(87, "clib.nim");
						T14_ = newParam_U4CJLW4cl5UxoEpwDyohCg(NIM_NIL);
					}
					break;
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1):
					{
						nimln_(89, "clib.nim");
						T14_ = newParam_Ij8X9aQmqY59ae9bP3wiQ79azA(getBool_8bAmYR2oBpeYFwvomDc8dg(item, NIM_FALSE));
					}
					break;
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
					case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
					{
						tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA* e;
						NimStringDesc* T21_;
						e = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*)0;
						nimln_(2989, "system.nim");
						e = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*) newObj((&NTI_gcKyg9bhR5vWTJg3cREMk0Q_), sizeof(tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA));
						new (e) tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
						(*e).m_type = (&NTI_qrLSDoe2oBoAqNtJ9badtnA_);
						nimln_(91, "clib.nim");
						T21_ = (NimStringDesc*)0;
						T21_ = rawNewString((reprEnum((NI)(*item).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)) ? reprEnum((NI)(*item).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_))->len : 0) + 26);
appendString(T21_, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_17));
appendString(T21_, reprEnum((NI)(*item).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
						asgnRef((void**) (&(*e).message), T21_);
						nimln_(2984, "system.nim");
						asgnRef((void**) (&(*e).parent), NIM_NIL);
						nimln_(91, "clib.nim");
						raiseExceptionEx((Exception*)e, "CatchableError", "json_to_params", "clib.nim", 91);
					}
					break;
					}
					result = (tySequence_EQ6L4H42GvMcXeqG7p5fZw*) incrSeqV3(result, (&NTI_EQ6L4H42GvMcXeqG7p5fZw_));
					T22_ = result->len++;
					asgnRef((void**) (&result->data[T22_]), T14_);
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_18 = addInt(i, ((NI) 1));
					i = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_18);
					nimln_(4015, "system.nim");
					{
						NI T25_;
						T25_ = (colontmp_ ? colontmp_->len : 0);
						if (!!((T25_ == L))) goto LA26_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA26_: ;
				} LA13: ;
			}
		}
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
	{
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pstmt;
		pstmt = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
		nimln_(105, "clib.nim");
		{
			int T31_;
			nimln_(483, "system.nim");
			nimln_(105, "clib.nim");
			T31_ = (int)0;
			T31_ = sqlite3_prepare_v2(db, query, ((int)chckRange((query ? nimCStrLen(query) : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), pstmt, NIM_NIL);
			if (!!((T31_ == ((NI32) 0)))) goto LA32_;
{			nimln_(106, "clib.nim");
			dbError_yRzNipQFOsKqLVySy7Je9bw(db);
}		}
		LA32_: ;
		{
			NI32 i_2;
			NI32 colontmp__2;
			i_2 = (NI32)0;
			colontmp__2 = (NI32)0;
			nimln_(107, "clib.nim");
			colontmp__2 = sqlite3_bind_parameter_count(pstmt);
			nimln_(2172, "system.nim");
			NI32 res = ((NI32) 1);
			{
				nimln_(2173, "system.nim");
				while (1) {
					NimStringDesc* key;
					NCSTRING T37_;
					NI TM_GqwyQEukm0XJRh6VvuDcmA_28;
					if (!(res <= colontmp__2)) goto LA36;
					nimln_(107, "clib.nim");
					i_2 = res;
					nimln_(108, "clib.nim");
					T37_ = (NCSTRING)0;
					T37_ = sqlite3_bind_parameter_name(pstmt, i_2);
					key = cstrToNimstr(T37_);
					nimln_(109, "clib.nim");
					{
						tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* T42_;
						NI T50_;
						if (!hasKey_VczJ0fz1o49a9ajsD9cvbBPBQ(parsed, key)) goto LA40_;
{						nimln_(110, "clib.nim");
						T42_ = (tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q*)0;
						switch ((*X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key)).kind) {
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 2):
						{
							nimln_(81, "clib.nim");
							nimln_(110, "clib.nim");
							T42_ = newParam_opUVQPa4k9aAgZsg9aKPuaog(getInt_rDQb9chpfbduaO7rsIalSMw(X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key), ((NI) 0)));
						}
						break;
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4):
						{
							nimln_(83, "clib.nim");
							nimln_(110, "clib.nim");
							T42_ = newParam_k5IcRUo9cf7SwFKByll2iag(getStr_z2Itmc4KJ7uMBtaTVQ09cqw(X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key), ((NimStringDesc*) NIM_NIL)));
						}
						break;
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 3):
						{
							nimln_(85, "clib.nim");
							nimln_(110, "clib.nim");
							T42_ = newParam_j5FS2km0qtRufvzb6B7zHQ(getFloat_Cc9ayyBhVu0SPW8c9adrFiQA(X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key), 0.0));
						}
						break;
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 0):
						{
							nimln_(87, "clib.nim");
							T42_ = newParam_U4CJLW4cl5UxoEpwDyohCg(NIM_NIL);
						}
						break;
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1):
						{
							nimln_(89, "clib.nim");
							nimln_(110, "clib.nim");
							T42_ = newParam_Ij8X9aQmqY59ae9bP3wiQ79azA(getBool_8bAmYR2oBpeYFwvomDc8dg(X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key), NIM_FALSE));
						}
						break;
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
						case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
						{
							tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA* e_2;
							NimStringDesc* T49_;
							e_2 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*)0;
							nimln_(2989, "system.nim");
							e_2 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*) newObj((&NTI_gcKyg9bhR5vWTJg3cREMk0Q_), sizeof(tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA));
							new (e_2) tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
							(*e_2).m_type = (&NTI_qrLSDoe2oBoAqNtJ9badtnA_);
							nimln_(91, "clib.nim");
							T49_ = (NimStringDesc*)0;
							nimln_(110, "clib.nim");
							T49_ = rawNewString((reprEnum((NI)(*X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key)).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)) ? reprEnum((NI)(*X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key)).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_))->len : 0) + 26);
appendString(T49_, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_17));
appendString(T49_, reprEnum((NI)(*X5BX5D__bm6Lzuv1zmaV42IeMuikggclib(parsed, key)).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
							asgnRef((void**) (&(*e_2).message), T49_);
							nimln_(2984, "system.nim");
							asgnRef((void**) (&(*e_2).parent), NIM_NIL);
							nimln_(91, "clib.nim");
							raiseExceptionEx((Exception*)e_2, "CatchableError", "json_to_params", "clib.nim", 91);
						}
						break;
						}
						result = (tySequence_EQ6L4H42GvMcXeqG7p5fZw*) incrSeqV3(result, (&NTI_EQ6L4H42GvMcXeqG7p5fZw_));
						T50_ = result->len++;
						asgnRef((void**) (&result->data[T50_]), T42_);
}					}
					goto LA38_;
					LA40_: ;
					{
						tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA* e_3;
						NimStringDesc* fmtRes;
						NimStringDesc* T52_;
						e_3 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*)0;
						nimln_(2989, "system.nim");
						e_3 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*) newObj((&NTI_gcKyg9bhR5vWTJg3cREMk0Q_), sizeof(tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA));
						new (e_3) tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
						(*e_3).m_type = (&NTI_qrLSDoe2oBoAqNtJ9badtnA_);
						nimln_(112, "clib.nim");
						fmtRes = rawNewString(((NI) 44));
						fmtRes = resizeString(fmtRes, 29);
appendString(fmtRes, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_22));
						nimln_(260, "strformat.nim");
						fmtRes = resizeString(fmtRes, (key ? key->len : 0) + 0);
appendString(fmtRes, key);
						T52_ = (NimStringDesc*)0;
						T52_ = (*e_3).message; (*e_3).message = copyStringRC1(fmtRes);
						if (T52_) nimGCunrefNoCycle(T52_);
						nimln_(2984, "system.nim");
						asgnRef((void**) (&(*e_3).parent), NIM_NIL);
						nimln_(112, "clib.nim");
						raiseExceptionEx((Exception*)e_3, "CatchableError", "json_to_params", "clib.nim", 112);
					}
					LA38_: ;
					nimln_(2175, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_28 = addInt(res, ((NI) 1));
					if (TM_GqwyQEukm0XJRh6VvuDcmA_28 < (-2147483647 -1) || TM_GqwyQEukm0XJRh6VvuDcmA_28 > 2147483647) raiseOverflow();
					res = (NI32)(TM_GqwyQEukm0XJRh6VvuDcmA_28);
				} LA36: ;
			}
		}
	}
	break;
	default:
	{
		tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA* e_4;
		NimStringDesc* T54_;
		e_4 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*)0;
		nimln_(2989, "system.nim");
		e_4 = (tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA*) newObj((&NTI_gcKyg9bhR5vWTJg3cREMk0Q_), sizeof(tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA));
		new (e_4) tyObject_CatchableError_qrLSDoe2oBoAqNtJ9badtnA;
		(*e_4).m_type = (&NTI_qrLSDoe2oBoAqNtJ9badtnA_);
		nimln_(114, "clib.nim");
		T54_ = (NimStringDesc*)0;
		T54_ = (*e_4).message; (*e_4).message = copyStringRC1(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_29));
		if (T54_) nimGCunrefNoCycle(T54_);
		nimln_(2984, "system.nim");
		asgnRef((void**) (&(*e_4).parent), NIM_NIL);
		nimln_(114, "clib.nim");
		raiseExceptionEx((Exception*)e_4, "CatchableError", "json_to_params", "clib.nim", 114);
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	return result;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3588, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void) {
	NimStringDesc* result;
	nimfr_("getCurrentExceptionMsg", "system.nim");
{	result = (NimStringDesc*)0;
	nimln_(3593, "system.nim");
	Exception* e = getCurrentException();
	nimln_(3594, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3_;
{		result = ((NimStringDesc*) NIM_NIL);
}	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, keepString_NmPLFe10r6PjDoUK2efLMw)(NimStringDesc* x) {
	NimStringDesc* result;
	nimfr_("keepString", "clib.nim");
	result = (NimStringDesc*)0;
	nimln_(25, "clib.nim");
	{
		NI T5_;
		NimStringDesc* T6_;
		nimln_(483, "system.nim");
		if (!!(((x ? x->len : 0) == 0))) goto LA3_;
{		nimln_(26, "clib.nim");
		asgnRef((void**) (&STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA), (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_)));
		T5_ = STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA->len++;
		T6_ = (NimStringDesc*)0;
		T6_ = STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA->data[T5_]; STRINGS_TO_CLEAR_DBBYUAgxDuNmDb14McuEhA->data[T5_] = copyStringRC1(x);
		if (T6_) nimGCunrefNoCycle(T6_);
}	}
	LA3_: ;
	nimln_(27, "clib.nim");
	result = copyString(x);
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING, buckets_db_all_json)(NI budget_handle, NCSTRING query, NCSTRING params_json) {
	NCSTRING result;
	NimStringDesc* res_string;
	TFrame* _nimCurFrame;
	NimStringDesc* T44_;
	nimfr_("buckets_db_all_json", "clib.nim");
	_nimCurFrame = getFrame();
	result = (NCSTRING)0;
	nimln_(120, "clib.nim");
	res_string = ((NimStringDesc*) NIM_NIL);
	nimln_(121, "clib.nim");
	try {
		tySequence_EQ6L4H42GvMcXeqG7p5fZw* params;
		NimStringDesc* T2_;
		nimln_(122, "clib.nim");
		tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db = (*getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ(budget_handle)).db;
		nimln_(123, "clib.nim");
		params = json_to_params_gVVWMJkILSzPVaoeCq1GHg(db, query, params_json);
		nimln_(124, "clib.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = cstrToNimstr(query);
		tyObject_AllResult_U9cP8WGvRKuOoBThSbzXQVQ* res = fetchAll_pXpsWPv7osnhxTUlJNRtlw(db, T2_, params->data, (params ? params->len : 0));
		nimln_(125, "clib.nim");
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
		nimln_(127, "clib.nim");
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jcols = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		{
			NimStringDesc* col;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
			NI T4_;
			col = (NimStringDesc*)0;
			colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			nimln_(128, "clib.nim");
			colontmp_ = (*res).cols;
			nimln_(4010, "system.nim");
			NI i = ((NI) 0);
			nimln_(4011, "system.nim");
			T4_ = (colontmp_ ? colontmp_->len : 0);
			NI L = T4_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					NI TM_GqwyQEukm0XJRh6VvuDcmA_30;
					if (!(i < L)) goto LA6;
					nimln_(128, "clib.nim");
					if ((NU)(i) >= (NU)(colontmp_ ? colontmp_->len : 0)) raiseIndexError2(i,(colontmp_ ? colontmp_->len : 0)-1);
					col = colontmp_->data[i];
					nimln_(129, "clib.nim");
					add_NE4BWkXVxUMFtDmmA5ZcHw(jcols, newJString_8iXO9aRAijCPe58pujCBbuQ_2(col));
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_30 = addInt(i, ((NI) 1));
					i = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_30);
					nimln_(4015, "system.nim");
					{
						NI T9_;
						T9_ = (colontmp_ ? colontmp_->len : 0);
						if (!!((T9_ == L))) goto LA10_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA10_: ;
				} LA6: ;
			}
		}
		nimln_(130, "clib.nim");
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jrows = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		{
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* row;
			tySequence_phjbYJtsbOIAYa9be34hhZg* colontmp__2;
			NI T13_;
			row = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			colontmp__2 = (tySequence_phjbYJtsbOIAYa9be34hhZg*)0;
			nimln_(131, "clib.nim");
			colontmp__2 = (*res).rows;
			nimln_(4010, "system.nim");
			NI i_2 = ((NI) 0);
			nimln_(4011, "system.nim");
			T13_ = (colontmp__2 ? colontmp__2->len : 0);
			NI L_2 = T13_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					NI TM_GqwyQEukm0XJRh6VvuDcmA_32;
					if (!(i_2 < L_2)) goto LA15;
					nimln_(131, "clib.nim");
					if ((NU)(i_2) >= (NU)(colontmp__2 ? colontmp__2->len : 0)) raiseIndexError2(i_2,(colontmp__2 ? colontmp__2->len : 0)-1);
					row = colontmp__2->data[i_2];
					nimln_(132, "clib.nim");
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jrow = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
					{
						NimStringDesc* col_2;
						NI T17_;
						col_2 = (NimStringDesc*)0;
						nimln_(4010, "system.nim");
						NI i_3 = ((NI) 0);
						nimln_(4011, "system.nim");
						T17_ = (row ? row->len : 0);
						NI L_3 = T17_;
						{
							nimln_(4012, "system.nim");
							while (1) {
								NI TM_GqwyQEukm0XJRh6VvuDcmA_31;
								if (!(i_3 < L_3)) goto LA19;
								nimln_(133, "clib.nim");
								if ((NU)(i_3) >= (NU)(row ? row->len : 0)) raiseIndexError2(i_3,(row ? row->len : 0)-1);
								col_2 = row->data[i_3];
								nimln_(134, "clib.nim");
								add_NE4BWkXVxUMFtDmmA5ZcHw(jrow, newJString_8iXO9aRAijCPe58pujCBbuQ_2(col_2));
								nimln_(4014, "system.nim");
								TM_GqwyQEukm0XJRh6VvuDcmA_31 = addInt(i_3, ((NI) 1));
								i_3 = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_31);
								nimln_(4015, "system.nim");
								{
									NI T22_;
									T22_ = (row ? row->len : 0);
									if (!!((T22_ == L_3))) goto LA23_;
{									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}								}
								LA23_: ;
							} LA19: ;
						}
					}
					nimln_(135, "clib.nim");
					add_NE4BWkXVxUMFtDmmA5ZcHw(jrows, jrow);
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_32 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_32);
					nimln_(4015, "system.nim");
					{
						NI T27_;
						T27_ = (colontmp__2 ? colontmp__2->len : 0);
						if (!!((T27_ == L_2))) goto LA28_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA28_: ;
				} LA15: ;
			}
		}
		nimln_(136, "clib.nim");
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jtypes = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		{
			NimStringDesc* t;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp__3;
			NI T31_;
			t = (NimStringDesc*)0;
			colontmp__3 = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			nimln_(137, "clib.nim");
			colontmp__3 = (*res).types;
			nimln_(4010, "system.nim");
			NI i_4 = ((NI) 0);
			nimln_(4011, "system.nim");
			T31_ = (colontmp__3 ? colontmp__3->len : 0);
			NI L_4 = T31_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					NimStringDesc* tstring;
					NI TM_GqwyQEukm0XJRh6VvuDcmA_33;
					if (!(i_4 < L_4)) goto LA33;
					nimln_(137, "clib.nim");
					if ((NU)(i_4) >= (NU)(colontmp__3 ? colontmp__3->len : 0)) raiseIndexError2(i_4,(colontmp__3 ? colontmp__3->len : 0)-1);
					t = colontmp__3->data[i_4];
					nimln_(138, "clib.nim");
					tstring = t;
					nimln_(139, "clib.nim");
					add_NE4BWkXVxUMFtDmmA5ZcHw(jtypes, newJString_8iXO9aRAijCPe58pujCBbuQ_2(tstring));
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_33 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_33);
					nimln_(4015, "system.nim");
					{
						NI T36_;
						T36_ = (colontmp__3 ? colontmp__3->len : 0);
						if (!!((T36_ == L_4))) goto LA37_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA37_: ;
				} LA33: ;
			}
		}
		nimln_(140, "clib.nim");
		add_n3qm2zfwLtoWXXf3UIj9aeg(j, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_34), newJString_8iXO9aRAijCPe58pujCBbuQ_2(((NimStringDesc*) NIM_NIL)));
		nimln_(141, "clib.nim");
		add_n3qm2zfwLtoWXXf3UIj9aeg(j, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_35), jcols);
		nimln_(142, "clib.nim");
		add_n3qm2zfwLtoWXXf3UIj9aeg(j, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_36), jrows);
		nimln_(143, "clib.nim");
		add_n3qm2zfwLtoWXXf3UIj9aeg(j, ((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_37), jtypes);
		nimln_(144, "clib.nim");
		toUgly_5SA9aXRryVJvgoCag29cRzQw(res_string, j);
	}
	catch (...) {
		tyArray_rhtWm6uYOU6da9bZDT6ryDA T40_;
		tySequence_lmmAXZV2yeOkTTvh7ZeG9cA* T41_;
		tySequence_lmmAXZV2yeOkTTvh7ZeG9cA* T42_;
		tySequence_lmmAXZV2yeOkTTvh7ZeG9cA* T43_;
		setFrame(_nimCurFrame);
		nimln_(146, "clib.nim");
		nimZeroMem((void*)T40_, sizeof(tyArray_rhtWm6uYOU6da9bZDT6ryDA));
		T40_[0].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_34));
		nimln_(148, "clib.nim");
		T40_[0].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile());
		T40_[1].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_35));
		nimln_(149, "clib.nim");
		T41_ = (tySequence_lmmAXZV2yeOkTTvh7ZeG9cA*)0;
		T41_ = NIM_NIL;
		T40_[1].Field1 = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T41_->data, (T41_ ? T41_->len : 0));
		T40_[2].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_36));
		nimln_(150, "clib.nim");
		T42_ = (tySequence_lmmAXZV2yeOkTTvh7ZeG9cA*)0;
		T42_ = NIM_NIL;
		T40_[2].Field1 = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T42_->data, (T42_ ? T42_->len : 0));
		T40_[3].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_37));
		nimln_(151, "clib.nim");
		T43_ = (tySequence_lmmAXZV2yeOkTTvh7ZeG9cA*)0;
		T43_ = NIM_NIL;
		T40_[3].Field1 = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T43_->data, (T43_ ? T43_->len : 0));
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j_2 = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T40_, 4);
		nimln_(153, "clib.nim");
		toUgly_5SA9aXRryVJvgoCag29cRzQw(res_string, j_2);
	}
	nimln_(154, "clib.nim");
	T44_ = (NimStringDesc*)0;
	T44_ = keepString_NmPLFe10r6PjDoUK2efLMw(res_string);
	result = nimToCStringConv(T44_);
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING, buckets_db_run_json)(NI budget_handle, NCSTRING query, NCSTRING params_json) {
	NCSTRING result;
	NimStringDesc* res_string;
	TFrame* _nimCurFrame;
	NimStringDesc* T6_;
	nimfr_("buckets_db_run_json", "clib.nim");
	_nimCurFrame = getFrame();
	result = (NCSTRING)0;
	res_string = (NimStringDesc*)0;
	nimln_(162, "clib.nim");
	try {
		tySequence_EQ6L4H42GvMcXeqG7p5fZw* params;
		NimStringDesc* T2_;
		tyArray_rnBfBeuXQMeTae3dUyC1Bw T3_;
		nimln_(164, "clib.nim");
		tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db = (*getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ(budget_handle)).db;
		nimln_(165, "clib.nim");
		params = json_to_params_gVVWMJkILSzPVaoeCq1GHg(db, query, params_json);
		nimln_(166, "clib.nim");
		T2_ = (NimStringDesc*)0;
		T2_ = cstrToNimstr(query);
		tyObject_RunResult_2ojqxKqQnWpNdiqANiRRbA* res = runQuery_ZvHm6eg9bqWl9arKUfiSea6w(db, T2_, params->data, (params ? params->len : 0));
		nimln_(167, "clib.nim");
		nimZeroMem((void*)T3_, sizeof(tyArray_rnBfBeuXQMeTae3dUyC1Bw));
		T3_[0].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_34));
		nimln_(169, "clib.nim");
		T3_[0].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(((NimStringDesc*) NIM_NIL));
		T3_[1].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_38));
		nimln_(170, "clib.nim");
		T3_[1].Field1 = percent__z0g83xvrx4R10lOvgItZ9aQ_2((*res).lastID);
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T3_, 2);
		nimln_(172, "clib.nim");
		toUgly_5SA9aXRryVJvgoCag29cRzQw(res_string, j);
	}
	catch (...) {
		tyArray_rnBfBeuXQMeTae3dUyC1Bw T5_;
		setFrame(_nimCurFrame);
		nimln_(174, "clib.nim");
		nimZeroMem((void*)T5_, sizeof(tyArray_rnBfBeuXQMeTae3dUyC1Bw));
		T5_[0].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_34));
		nimln_(176, "clib.nim");
		T5_[0].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile());
		T5_[1].Field0 = copyString(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_38));
		nimln_(177, "clib.nim");
		T5_[1].Field1 = percent__z0g83xvrx4R10lOvgItZ9aQ_2(IL64(0));
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j_2 = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T5_, 2);
		nimln_(179, "clib.nim");
		toUgly_5SA9aXRryVJvgoCag29cRzQw(res_string, j_2);
	}
	nimln_(180, "clib.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = keepString_NmPLFe10r6PjDoUK2efLMw(res_string);
	result = nimToCStringConv(T6_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, jsonStringToStringSeq_yoZz9aBtjaT9bqb6xITm9cC9bA)(NCSTRING jsonstring) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result;
	NimStringDesc* T1_;
	nimfr_("jsonStringToStringSeq", "clib.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(189, "clib.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = cstrToNimstr(jsonstring);
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node = parseJson_q2jt59czHU4BW88Mb7EJDUA(T1_);
	nimln_(190, "clib.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA4_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_39));
}	}
	LA4_: ;
	{
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* item;
		item = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		nimln_(746, "json.nim");
		{
			if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA9_;
{			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_40));
}		}
		LA9_: ;
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* i;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* colontmp_;
			NI T12_;
			i = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			colontmp_ = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			nimln_(747, "json.nim");
			if (!(((64 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_41));
			colontmp_ = (*node).elems;
			nimln_(4010, "system.nim");
			NI i_2 = ((NI) 0);
			nimln_(4011, "system.nim");
			T12_ = (colontmp_ ? colontmp_->len : 0);
			NI L = T12_;
			{
				nimln_(4012, "system.nim");
				while (1) {
					NimStringDesc* T15_;
					NI T16_;
					NimStringDesc* T17_;
					NI TM_GqwyQEukm0XJRh6VvuDcmA_42;
					if (!(i_2 < L)) goto LA14;
					nimln_(747, "json.nim");
					if ((NU)(i_2) >= (NU)(colontmp_ ? colontmp_->len : 0)) raiseIndexError2(i_2,(colontmp_ ? colontmp_->len : 0)-1);
					i = colontmp_->data[i_2];
					nimln_(191, "clib.nim");
					item = i;
					nimln_(192, "clib.nim");
					T15_ = (NimStringDesc*)0;
					T15_ = getStr_z2Itmc4KJ7uMBtaTVQ09cqw(item, ((NimStringDesc*) NIM_NIL));
					result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(result, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
					T16_ = result->len++;
					T17_ = (NimStringDesc*)0;
					T17_ = result->data[T16_]; result->data[T16_] = copyStringRC1(T15_);
					if (T17_) nimGCunrefNoCycle(T17_);
					nimln_(4014, "system.nim");
					TM_GqwyQEukm0XJRh6VvuDcmA_42 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_GqwyQEukm0XJRh6VvuDcmA_42);
					nimln_(4015, "system.nim");
					{
						NI T20_;
						T20_ = (colontmp_ ? colontmp_->len : 0);
						if (!!((T20_ == L))) goto LA21_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_GqwyQEukm0XJRh6VvuDcmA_5));
}					}
					LA21_: ;
				} LA14: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING, buckets_db_execute_many_json)(NI budget_handle, NCSTRING queries_json) {
	NCSTRING result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* queries;
	NimStringDesc* res_string;
	TFrame* _nimCurFrame;
	NimStringDesc* T6_;
	nimfr_("buckets_db_execute_many_json", "clib.nim");
{	_nimCurFrame = getFrame();
	result = (NCSTRING)0;
	queries = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	nimln_(198, "clib.nim");
	res_string = ((NimStringDesc*) NIM_NIL);
	nimln_(199, "clib.nim");
	try {
		nimln_(200, "clib.nim");
		queries = jsonStringToStringSeq_yoZz9aBtjaT9bqb6xITm9cC9bA(queries_json);
	}
	catch (tyObject_AssertionError_G9cUlLvU4AFC26wbFxLFkFA&) {
		NimStringDesc* T3_;
		setFrame(_nimCurFrame);
		nimln_(202, "clib.nim");
		T3_ = (NimStringDesc*)0;
		T3_ = keepString_NmPLFe10r6PjDoUK2efLMw(getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile());
		result = nimToCStringConv(T3_);
		nimln_(203, "clib.nim");
		goto BeforeRet_;
	}
	nimln_(205, "clib.nim");
	tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db = (*getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ(budget_handle)).db;
	nimln_(206, "clib.nim");
	try {
		nimln_(207, "clib.nim");
		executeMany_WszC4nheyy9bsMXF4tK0v1Q(db, queries->data, (queries ? queries->len : 0));
	}
	catch (...) {
		setFrame(_nimCurFrame);
		nimln_(209, "clib.nim");
		res_string = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile();
	}
	nimln_(210, "clib.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = keepString_NmPLFe10r6PjDoUK2efLMw(res_string);
	result = nimToCStringConv(T6_);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
{		result = NIM_TRUE;
		goto BeforeRet_;
}	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
{		result = NIM_TRUE;
		goto BeforeRet_;
}	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
{		result = NIM_FALSE;
		goto BeforeRet_;
}	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
{		result = NIM_TRUE;
		goto BeforeRet_;
}	}
	LA15_: ;
	result = isObjSlowPath_yEa9cUwzxhGRtg9cspcfCIHg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, log_3UB9b0flreHbZSduHV9cBGOA)(tyObject_LoggercolonObjectType__9bhietBQiofDPLK3sBa0qPQ* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	nimln_(67, "chcks.nim");
	chckNilDisp(logger);
	nimln_(143, "logging.nim");
	{
		if (!((logger) && ((*logger).m_type == (&NTI_RVbeT0aVEu0OfdbVn1KX0g_)))) goto LA3_;
{		if (logger) chckObj((*logger).m_type, (&NTI_RVbeT0aVEu0OfdbVn1KX0g_));
		log_rG6osqE0luZSJUlLifxyVg(((tyObject_RollingFileLoggercolonObjectType__RVbeT0aVEu0OfdbVn1KX0g*) (logger)), level, args, argsLen_0);
}	}
	goto LA1_;
	LA3_: ;
	{
		if (!((logger) && (isObjWithCache((*logger).m_type, (&NTI_IRs4hY6GNcXZ1akep9cf7jA_), Nim_OfCheck_CACHE44)))) goto LA6_;
{		if (logger) chckObj((*logger).m_type, (&NTI_IRs4hY6GNcXZ1akep9cf7jA_));
		log_m2nFIuqvJSzncok28dY8Kg(((tyObject_FileLoggercolonObjectType__IRs4hY6GNcXZ1akep9cf7jA*) (logger)), level, args, argsLen_0);
}	}
	goto LA1_;
	LA6_: ;
	{
		if (!((logger) && ((*logger).m_type == (&NTI_4w707i5soOx7A2LWkxurNA_)))) goto LA9_;
{		if (logger) chckObj((*logger).m_type, (&NTI_4w707i5soOx7A2LWkxurNA_));
		log_A500h04AJ9cHQgD9ad6BzDYw(((tyObject_ConsoleLoggercolonObjectType__4w707i5soOx7A2LWkxurNA*) (logger)), level, args, argsLen_0);
}	}
	goto LA1_;
	LA9_: ;
	{
		if (!((logger) && ((*logger).m_type == (&NTI_pZbUChI2wyLci5Jc82XTOQ_)))) goto LA12_;
{		if (logger) chckObj((*logger).m_type, (&NTI_pZbUChI2wyLci5Jc82XTOQ_));
		log_wsjRFKCkSU1CgTpE6DRsrg(((tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ*) (logger)), level, args, argsLen_0);
}	}
	goto LA1_;
	LA12_: ;
	{
		if (!((logger) && (isObjWithCache((*logger).m_type, (&NTI_9bhietBQiofDPLK3sBa0qPQ_), Nim_OfCheck_CACHE45)))) goto LA15_;
{		log_2EMZHteAOCjvMWyiczAS7w(logger, level, args, argsLen_0);
}	}
	goto LA1_;
	LA15_: ;
	LA1_: ;
	popFrame();
}
void PreMainInner(void) {
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_osInit000();
	stdlib_loggingInit000();
	buckets_dbschemaInit000();
	buckets_budgetfileInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	stdlib_timesDatInit000();
	stdlib_osDatInit000();
	stdlib_loggingDatInit000();
	stdlib_sqlite3DatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_parsejsonDatInit000();
	stdlib_jsonDatInit000();
	stdlib_db_commonDatInit000();
	buckets_dbDatInit000();
	buckets_dbschemaDatInit000();
	buckets_budgetfileDatInit000();
	buckets_bucketsDatInit000();
	clibDatInit000();
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	TFrame FR_; FR_.len = 0;
}
	nimfr_("clib", "clib.nim");
nimRegisterGlobalMarker(TM_GqwyQEukm0XJRh6VvuDcmA_2);
nimRegisterGlobalMarker(TM_GqwyQEukm0XJRh6VvuDcmA_3);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, clibDatInit000)(void) {
static TNimNode TM_GqwyQEukm0XJRh6VvuDcmA_0[1];
NTI_5cp59bim9aJ4WupX5aVaD1Sg_.size = sizeof(tyProc_5cp59bim9aJ4WupX5aVaD1Sg);
NTI_5cp59bim9aJ4WupX5aVaD1Sg_.kind = 25;
NTI_5cp59bim9aJ4WupX5aVaD1Sg_.base = 0;
NTI_5cp59bim9aJ4WupX5aVaD1Sg_.flags = 3;
NTI_AHQ350tguQkj2pXJTiVQzw_.size = sizeof(tySequence_AHQ350tguQkj2pXJTiVQzw*);
NTI_AHQ350tguQkj2pXJTiVQzw_.kind = 24;
NTI_AHQ350tguQkj2pXJTiVQzw_.base = (&NTI_5cp59bim9aJ4WupX5aVaD1Sg_);
NTI_AHQ350tguQkj2pXJTiVQzw_.flags = 2;
NTI_AHQ350tguQkj2pXJTiVQzw_.marker = Marker_tySequence_AHQ350tguQkj2pXJTiVQzw;
NTI_pZbUChI2wyLci5Jc82XTOQ_.size = sizeof(tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ);
NTI_pZbUChI2wyLci5Jc82XTOQ_.kind = 17;
NTI_pZbUChI2wyLci5Jc82XTOQ_.base = (&NTI_9bhietBQiofDPLK3sBa0qPQ_);
TM_GqwyQEukm0XJRh6VvuDcmA_0[0].len = 0; TM_GqwyQEukm0XJRh6VvuDcmA_0[0].kind = 2;
NTI_pZbUChI2wyLci5Jc82XTOQ_.node = &TM_GqwyQEukm0XJRh6VvuDcmA_0[0];
NTI_a1qK8gNpfISO1NXnbbEzHw_.size = sizeof(tyObject_FunctionLoggercolonObjectType__pZbUChI2wyLci5Jc82XTOQ*);
NTI_a1qK8gNpfISO1NXnbbEzHw_.kind = 22;
NTI_a1qK8gNpfISO1NXnbbEzHw_.base = (&NTI_pZbUChI2wyLci5Jc82XTOQ_);
NTI_a1qK8gNpfISO1NXnbbEzHw_.marker = Marker_tyRef_a1qK8gNpfISO1NXnbbEzHw;
NTI_EQ6L4H42GvMcXeqG7p5fZw_.size = sizeof(tySequence_EQ6L4H42GvMcXeqG7p5fZw*);
NTI_EQ6L4H42GvMcXeqG7p5fZw_.kind = 24;
NTI_EQ6L4H42GvMcXeqG7p5fZw_.base = (&NTI_E0cTKF9afYzykvtJvV8SvRA_);
NTI_EQ6L4H42GvMcXeqG7p5fZw_.flags = 2;
NTI_EQ6L4H42GvMcXeqG7p5fZw_.marker = Marker_tySequence_EQ6L4H42GvMcXeqG7p5fZw;
}

