/* Generated by Nim Compiler v0.19.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_Table_VhiYQVROvZwCBgplqpTfWg;
struct tySequence_hC9cYWgGj63WaE3PXFdHUGw;
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ;
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
struct NimStringDesc;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA;
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
struct tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg;
struct Exception;
struct RootObj;
struct tySequence_uB9b75OUPRENsBAu4AnoePA;
struct tyTuple_JQpicjcFqNtYc46PZEVkSg;
struct tySequence_phjbYJtsbOIAYa9be34hhZg;
struct tySequence_5nQuE8Alerr1wffkYjQ9bGg;
struct tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q;
struct tyTuple_eq1RM0xbpgPWPAQamwDgbA;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table_VhiYQVROvZwCBgplqpTfWg {
tySequence_hC9cYWgGj63WaE3PXFdHUGw* data;
NI counter;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR tyUncheckedArray_py3s8sMDoAoBkn8uuh0ZzQ[1];
struct NimStringDesc : public TGenericSeq {
tyUncheckedArray_py3s8sMDoAoBkn8uuh0ZzQ data;
};
struct tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ {
NI id;
tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db;
NimStringDesc* filename;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_8ZvwQIddfpj2THRVPsFzIQ[1];
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw {
char dummy;
};
typedef N_NIMCALL_PTR(void, tyProc_Ct1Mg728R1V16bUJA7EJ8A) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db);
struct tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg {
NimStringDesc* Field0;
tyProc_Ct1Mg728R1V16bUJA7EJ8A Field1;
};
typedef tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg tyArray_3elISlPUynt0R48Wr6G2wg[15];
struct RootObj {
TNimType* m_type;
};
N_NIMCALL(void, popCurrentExceptionEx)(NU id);struct Exception : public RootObj {
virtual void raise() {throw *this;}
~Exception() {if(this->raise_id) popCurrentExceptionEx(this->raise_id);}
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
typedef NU8 tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA;
struct tyTuple_JQpicjcFqNtYc46PZEVkSg {
tySequence_phjbYJtsbOIAYa9be34hhZg* Field0;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field1;
tySequence_5nQuE8Alerr1wffkYjQ9bGg* Field2;
};
typedef tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q* tyArray_BFawqWeXyCCIVrIw1RL02g[1];
struct tyTuple_eq1RM0xbpgPWPAQamwDgbA {
NI Field0;
NI Field1;
tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* Field2;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ : TGenericSeq {
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_phjbYJtsbOIAYa9be34hhZg : TGenericSeq {
  tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data[SEQ_DECL_SIZE];
};
struct tySequence_5nQuE8Alerr1wffkYjQ9bGg : TGenericSeq {
  tyEnum_DataType_WRq6Jv2bvs9b3t9bKN7EgcWA data[SEQ_DECL_SIZE];
};
struct tySequence_hC9cYWgGj63WaE3PXFdHUGw : TGenericSeq {
  tyTuple_eq1RM0xbpgPWPAQamwDgbA data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA : TGenericSeq {
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ)(void* p, NI op);
static N_NIMCALL(void, TM_Q8GDWOFB5uWKFMQFSo1oVw_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, initTable_jqzpDgYBM9aUAc5X3WbaZOA)(NI initialSize, tyObject_Table_VhiYQVROvZwCBgplqpTfWg* Result);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, logLoop_Y1QvvdpC0FmKBCafruMWGQ)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__cWlFtzNs7sAIHXtL02SHCg)(tyObject_Table_VhiYQVROvZwCBgplqpTfWg& t, NI key, tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*, open_SRJkmN7JR2aulOhbafCrYA)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw)(tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg* a, void* p);
static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace_BDp9bawgAP2bl9ay9bR0TJdMg)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, upgradeSchema_LH14cll3kWhgg7HfQbZIzw)(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* bf);
N_LIB_PRIVATE N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*, setupQuery_6EQAJlzQgp6Lnc8upW20sQ)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
extern "C" N_CDECL(NI32, sqlite3_step)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col);
extern "C" N_CDECL(NCSTRING, sqlite3_column_text)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1, NI32 iCol);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
extern "C" N_CDECL(NI32, sqlite3_finalize)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* pStmt);
N_LIB_PRIVATE N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ch0e5PgaoEZEQHhvsLrGJQ)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuAlignString)(NimStringDesc* s, NI count, NIM_CHAR padding);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_NIMCALL(void, popCurrentExceptionEx)(NU id);
static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fetchAll_P7V2Hd84rSYC9cLJeKQt7zQ)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* statement, tyObject_ParamObj_8gVorlB2Rkv7LEix8x9aC0Q** params, NI paramsLen_0, tyTuple_JQpicjcFqNtYc46PZEVkSg* Result);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, reprAny)(void* p, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ**, X5BX5D__9bymmKdwETeROM26iiSEzvw)(tyObject_Table_VhiYQVROvZwCBgplqpTfWg& t, NI key);
NI nextid_qcNG8J33Ctn5H8ycDMTLpA;
tyObject_Table_VhiYQVROvZwCBgplqpTfWg id2BudgetFile_tTZwLExyJdLAlwEEzldPEw;
TNimType NTI_yi1kAYh8kb3f1o4vS0ZTBQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_Ocaq0E9cAGvTovUG5l30IXg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_5PWEcVklnzmjVvFuGsuXhQ_;
extern TNimType NTI_VhiYQVROvZwCBgplqpTfWg_;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyArray_3elISlPUynt0R48Wr6G2wg migrations_XP1BT1YxTzkGsU62UYEcJQ;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI_JQpicjcFqNtYc46PZEVkSg_;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_4, "Opening file ", 13);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_6, "[SYSASSERT] ", 12);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_7, "begin nimGCunrefNoCycle", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Q8GDWOFB5uWKFMQFSo1oVw_5 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_6),
((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_7)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_9, "[GCASSERT] ", 11);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_10, "nimGCunrefNoCycle: isAllocatedPtr", 33);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Q8GDWOFB5uWKFMQFSo1oVw_8 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_9),
((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_10)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_12, "end nimGCunrefNoCycle 2", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Q8GDWOFB5uWKFMQFSo1oVw_11 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_6),
((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_12)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_14, "end nimGCunrefNoCycle 5", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Q8GDWOFB5uWKFMQFSo1oVw_13 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_6),
((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_14)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_16, "Upgrading schema ...", 20);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_15 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_16)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_17, "  CREATE TABLE IF NOT EXISTS _schema_version (\012    id INTEGER P"
"RIMARY KEY,\012    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\012   "
" name TEXT UNIQUE\012  )", 148);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_18, "SELECT name FROM _schema_version", 32);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_19, "Applied patches: ", 17);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_20, "-", 1);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_21, "Patch ", 6);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_22, " already applied.", 17);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_23, "applying patch: ", 16);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_24, "BEGIN", 5);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_25, "INSERT INTO _schema_version (name) VALUES (\?)", 45);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_26, "COMMIT", 6);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_27, "error applying patch ", 21);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_28, ": ", 2);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_29, "ROLLBACK", 8);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_31, "Schema upgrade complete", 23);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_30 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_31)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_32, "SELECT * from _schema_version", 29);
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_34, "Got all of them", 15);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_33 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_34)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_36, "All of them length: hi", 22);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_35 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_36)}
;
STRING_LITERAL(TM_Q8GDWOFB5uWKFMQFSo1oVw_38, "Done opening budget file", 24);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_Q8GDWOFB5uWKFMQFSo1oVw_37 = {((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_38)}
;
static N_NIMCALL(void, Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ)(void* p, NI op) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* a;
	a = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)p;
	nimGCvisit((void*)(*a).filename, op);
}
static N_NIMCALL(void, TM_Q8GDWOFB5uWKFMQFSo1oVw_3)(void) {
	nimGCvisit((void*)id2BudgetFile_tTZwLExyJdLAlwEEzldPEw.data, 0);
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[(*dest).len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).len + ((NI) 1)))));
		(*dest).len += (*src).len;
}	}
	LA3_: ;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	return result;
}

static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void) {
	gch_IcYaEuuWivYAS86vFMTS3Q.recGcLock += ((NI) 1);
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw(gch_IcYaEuuWivYAS86vFMTS3Q.zct, c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	{
		if (!NIM_FALSE) goto LA3_;
{		echoBinSafe(TM_Q8GDWOFB5uWKFMQFSo1oVw_5, 2);
		exit(((NI) 1));
}	}
	LA3_: ;
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T7_)) goto LA8_;
{		echoBinSafe(TM_Q8GDWOFB5uWKFMQFSo1oVw_8, 2);
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		writeStackTrace_BDp9bawgAP2bl9ay9bR0TJdMg();
		exit(((NI) 1));
}	}
	LA8_: ;
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA12_;
{		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system(c);
		{
			if (!NIM_FALSE) goto LA16_;
{			echoBinSafe(TM_Q8GDWOFB5uWKFMQFSo1oVw_11, 2);
			exit(((NI) 1));
}		}
		LA16_: ;
}	}
	LA12_: ;
	{
		if (!NIM_FALSE) goto LA20_;
{		echoBinSafe(TM_Q8GDWOFB5uWKFMQFSo1oVw_13, 2);
		exit(((NI) 1));
}	}
	LA20_: ;
}

static N_INLINE(NimStringDesc*, X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile)(tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row, NI32 col) {
	NimStringDesc* result;
	NCSTRING T1_;
	result = (NimStringDesc*)0;
	T1_ = (NCSTRING)0;
	T1_ = sqlite3_column_text(row, col);
	result = cstrToNimstr(T1_);
	return result;
}

static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	NI alen = (a ? a->len : 0);
	NI blen = (b ? b->len : 0);
	{
		if (!(alen == blen)) goto LA3_;
{		{
			if (!(alen == ((NI) 0))) goto LA7_;
{			result = NIM_TRUE;
			goto BeforeRet_;
}		}
		LA7_: ;
		result = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
}	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
{	result = (NI)0;
	{
		NimStringDesc* i;
		i = (NimStringDesc*)0;
		NI i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < aLen_0)) goto LA3;
				i = a[i_2];
				{
					if (!eqStrings(i, item)) goto LA6_;
{					goto BeforeRet_;
}				}
				LA6_: ;
				result += ((NI) 1);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQbudgetfile(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = (Exception*)0;
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	return result;
}

static N_INLINE(NimStringDesc*, getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile)(void) {
	NimStringDesc* result;
{	result = (NimStringDesc*)0;
	Exception* e = getCurrentException();
	{
		if (!(e == NIM_NIL)) goto LA3_;
{		result = ((NimStringDesc*) NIM_NIL);
}	}
	goto LA1_;
	LA3_: ;
	{
		result = copyString((*e).message);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, upgradeSchema_LH14cll3kWhgg7HfQbZIzw)(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* bf) {
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T5_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* applied;
	tyTuple_JQpicjcFqNtYc46PZEVkSg allofthem;
	tyArray_BFawqWeXyCCIVrIw1RL02g T67_;
	{
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA3_;
{		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_15, 1);
}	}
	LA3_: ;
	nimZeroMem((void*)T5_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
	exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_17), T5_, 0);
	applied = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	{
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* row;
		tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* colontmp_;
		NimStringDesc* colontmp__2;
		tyArray_8ZvwQIddfpj2THRVPsFzIQ T7_;
		row = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
		colontmp_ = (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*)0;
		colontmp__2 = (NimStringDesc*)0;
		colontmp_ = (*bf).db;
		colontmp__2 = copyString(((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_18));
		nimZeroMem((void*)T7_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
		tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* stmt = setupQuery_6EQAJlzQgp6Lnc8upW20sQ(colontmp_, colontmp__2, T7_, 0);
		{
			while (1) {
				NI32 T10_;
				NimStringDesc* T11_;
				NI T12_;
				NimStringDesc* T13_;
				T10_ = (NI32)0;
				T10_ = sqlite3_step(stmt);
				if (!(T10_ == ((NI32) 100))) goto LA9;
				row = stmt;
				T11_ = (NimStringDesc*)0;
				T11_ = X5BX5D__tbPO1SD3BdMzjXgxBZr7Dwbudgetfile(row, ((NI32) 0));
				applied = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3(applied, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
				T12_ = applied->len++;
				T13_ = (NimStringDesc*)0;
				T13_ = applied->data[T12_]; applied->data[T12_] = copyStringRC1(T11_);
				if (T13_) nimGCunrefNoCycle(T13_);
			} LA9: ;
		}
		{
			NI32 T16_;
			T16_ = (NI32)0;
			T16_ = sqlite3_finalize(stmt);
			if (!!((T16_ == ((NI32) 0)))) goto LA17_;
{			dbError_yRzNipQFOsKqLVySy7Je9bw(colontmp_);
}		}
		LA17_: ;
	}
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T23_;
		NimStringDesc* fmtRes;
		NimStringDesc* T24_;
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA21_;
{		nimZeroMem((void*)T23_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		fmtRes = rawNewString(((NI) 36));
		fmtRes = resizeString(fmtRes, 17);
appendString(fmtRes, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_19));
		T24_ = (NimStringDesc*)0;
		T24_ = dollar__ch0e5PgaoEZEQHhvsLrGJQ(applied);
		fmtRes = resizeString(fmtRes, (T24_ ? T24_->len : 0) + 0);
appendString(fmtRes, T24_);
		T23_[0] = copyString(fmtRes);
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T23_, 1);
}	}
	LA21_: ;
	NI order = ((NI) 0);
	{
		tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg migration;
		nimZeroMem((void*)(&migration), sizeof(tyTuple_Pq6tuMv18lwDM9ahYyg9b8Bg));
		NI i = ((NI) 0);
		{
			if (!(((NI) (i)) <= ((NI) 14))) goto LA28_;
{			{
				while (1) {
					migration.Field0 = migrations_XP1BT1YxTzkGsU62UYEcJQ[(i)- 0].Field0;
					migration.Field1 = migrations_XP1BT1YxTzkGsU62UYEcJQ[(i)- 0].Field1;
					{
						NimStringDesc* padded_order;
						NimStringDesc* fullname;
						NimStringDesc* fmtRes_2;
						tyArray_8ZvwQIddfpj2THRVPsFzIQ T47_;
						order += ((NI) 1);
						padded_order = nsuAlignString(nsuIntToStr(order, ((NI) 1)), ((NI) 4), 48);
						fmtRes_2 = rawNewString(((NI) 51));
						fmtRes_2 = resizeString(fmtRes_2, (padded_order ? padded_order->len : 0) + 0);
appendString(fmtRes_2, padded_order);
						fmtRes_2 = resizeString(fmtRes_2, 1);
appendString(fmtRes_2, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_20));
						fmtRes_2 = resizeString(fmtRes_2, (migration.Field0 ? migration.Field0->len : 0) + 0);
appendString(fmtRes_2, migration.Field0);
						fullname = fmtRes_2;
						{
							if (!contains_jPdUhZfr9a8sH2V3ZBDljzwbudgetfile(applied->data, (applied ? applied->len : 0), fullname)) goto LA35_;
{							{
								tyArray_nHXaesL0DJZHyVS07ARPRA T41_;
								NimStringDesc* fmtRes_3;
								if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA39_;
{								nimZeroMem((void*)T41_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
								fmtRes_3 = rawNewString(((NI) 43));
								fmtRes_3 = resizeString(fmtRes_3, 6);
appendString(fmtRes_3, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_21));
								fmtRes_3 = resizeString(fmtRes_3, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_3, fullname);
								fmtRes_3 = resizeString(fmtRes_3, 17);
appendString(fmtRes_3, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_22));
								T41_[0] = copyString(fmtRes_3);
								logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T41_, 1);
}							}
							LA39_: ;
							goto LA32;
}						}
						LA35_: ;
						{
							tyArray_nHXaesL0DJZHyVS07ARPRA T46_;
							NimStringDesc* fmtRes_4;
							if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA44_;
{							nimZeroMem((void*)T46_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
							fmtRes_4 = rawNewString(((NI) 36));
							fmtRes_4 = resizeString(fmtRes_4, 16);
appendString(fmtRes_4, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_23));
							fmtRes_4 = resizeString(fmtRes_4, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_4, fullname);
							T46_[0] = copyString(fmtRes_4);
							logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T46_, 1);
}						}
						LA44_: ;
						nimZeroMem((void*)T47_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
						exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_24), T47_, 0);
						try {
							tyArray_nHXaesL0DJZHyVS07ARPRA T49_;
							tyArray_8ZvwQIddfpj2THRVPsFzIQ T50_;
							migration.Field1((*bf).db);
							nimZeroMem((void*)T49_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
							T49_[0] = copyString(fullname);
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_25), T49_, 1);
							nimZeroMem((void*)T50_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_26), T50_, 0);
						}
						catch (...) {
							tyArray_8ZvwQIddfpj2THRVPsFzIQ T58_;
							{
								tyArray_nHXaesL0DJZHyVS07ARPRA T56_;
								NimStringDesc* fmtRes_5;
								NimStringDesc* T57_;
								if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 5))) goto LA54_;
{								nimZeroMem((void*)T56_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
								fmtRes_5 = rawNewString(((NI) 79));
								fmtRes_5 = resizeString(fmtRes_5, 21);
appendString(fmtRes_5, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_27));
								fmtRes_5 = resizeString(fmtRes_5, (fullname ? fullname->len : 0) + 0);
appendString(fmtRes_5, fullname);
								fmtRes_5 = resizeString(fmtRes_5, 2);
appendString(fmtRes_5, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_28));
								T57_ = (NimStringDesc*)0;
								T57_ = getCurrentExceptionMsg_fOe1OXzHoGbgrd7IEmbp5Qbudgetfile();
								fmtRes_5 = resizeString(fmtRes_5, (T57_ ? T57_->len : 0) + 0);
appendString(fmtRes_5, T57_);
								T56_[0] = copyString(fmtRes_5);
								logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 5), T56_, 1);
}							}
							LA54_: ;
							nimZeroMem((void*)T58_, sizeof(tyArray_8ZvwQIddfpj2THRVPsFzIQ));
							exec_kASFnJjvwTJpKpmn9aQHmPg((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_29), T58_, 0);
							throw;
						}
					} LA32: ;
					{
						if (!(((NI) 14) <= ((NI) (i)))) goto LA61_;
{						goto LA30;
}					}
					LA61_: ;
					i += ((NI) 1);
				}
			} LA30: ;
}		}
		LA28_: ;
	}
	{
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA65_;
{		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_30, 1);
}	}
	LA65_: ;
	nimZeroMem((void*)(&allofthem), sizeof(tyTuple_JQpicjcFqNtYc46PZEVkSg));
	nimZeroMem((void*)T67_, sizeof(tyArray_BFawqWeXyCCIVrIw1RL02g));
	fetchAll_P7V2Hd84rSYC9cLJeKQt7zQ((*bf).db, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_32), T67_, 0, (&allofthem));
	{
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA70_;
{		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_33, 1);
}	}
	LA70_: ;
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T76_;
		NI T77_;
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA74_;
{		nimZeroMem((void*)T76_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T77_ = (allofthem.Field0 ? allofthem.Field0->len : 0);
		T76_[0] = nimIntToStr(T77_);
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T76_, 1);
}	}
	LA74_: ;
	{
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA80_;
{		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_35, 1);
}	}
	LA80_: ;
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T86_;
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA84_;
{		nimZeroMem((void*)T86_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T86_[0] = reprAny((&allofthem), (&NTI_JQpicjcFqNtYc46PZEVkSg_));
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), T86_, 1);
}	}
	LA84_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, openBudgetFile_WkDTJ1JqGfRfDWV2gutrmw)(NimStringDesc* filename) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* result;
	NimStringDesc* T6_;
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)0;
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*) newObj((&NTI_5PWEcVklnzmjVvFuGsuXhQ_), sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ));
	{
		tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
		NimStringDesc* fmtRes;
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2))) goto LA3_;
{		nimZeroMem((void*)T5_, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		fmtRes = rawNewString(((NI) 33));
		fmtRes = resizeString(fmtRes, 13);
appendString(fmtRes, ((NimStringDesc*) &TM_Q8GDWOFB5uWKFMQFSo1oVw_4));
		fmtRes = resizeString(fmtRes, (filename ? filename->len : 0) + 0);
appendString(fmtRes, filename);
		T5_[0] = copyString(fmtRes);
		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 2), T5_, 1);
}	}
	LA3_: ;
	(*result).id = nextid_qcNG8J33Ctn5H8ycDMTLpA;
	nextid_qcNG8J33Ctn5H8ycDMTLpA += ((NI) 1);
	X5BX5Deq__cWlFtzNs7sAIHXtL02SHCg(id2BudgetFile_tTZwLExyJdLAlwEEzldPEw, (*result).id, result);
	(*result).db = open_SRJkmN7JR2aulOhbafCrYA(filename, ((NimStringDesc*) NIM_NIL), ((NimStringDesc*) NIM_NIL), ((NimStringDesc*) NIM_NIL));
	T6_ = (NimStringDesc*)0;
	T6_ = (*result).filename; (*result).filename = copyStringRC1(filename);
	if (T6_) nimGCunrefNoCycle(T6_);
	upgradeSchema_LH14cll3kWhgg7HfQbZIzw(result);
	{
		if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1))) goto LA9_;
{		logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 1), TM_Q8GDWOFB5uWKFMQFSo1oVw_37, 1);
}	}
	LA9_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*, getBudgetFile_gTFKk2LQBdeAwvZ2T4WFpQ)(NI id) {
	tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ* result;
	result = (tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*)0;
	result = (*X5BX5D__9bymmKdwETeROM26iiSEzvw(id2BudgetFile_tTZwLExyJdLAlwEEzldPEw, id));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
}
nimRegisterGlobalMarker(TM_Q8GDWOFB5uWKFMQFSo1oVw_3);
	initTable_jqzpDgYBM9aUAc5X3WbaZOA(((NI) 64), (&id2BudgetFile_tTZwLExyJdLAlwEEzldPEw));
}

N_LIB_PRIVATE N_NIMCALL(void, buckets_budgetfileDatInit000)(void) {
static TNimNode* TM_Q8GDWOFB5uWKFMQFSo1oVw_2[3];
static TNimNode TM_Q8GDWOFB5uWKFMQFSo1oVw_0[4];
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.size = sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ);
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.kind = 18;
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.base = 0;
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.flags = 2;
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[0] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, id);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[1].name = "id";
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[1] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, db);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].typ = (&NTI_Ocaq0E9cAGvTovUG5l30IXg_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[2].name = "db";
TM_Q8GDWOFB5uWKFMQFSo1oVw_2[2] = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3];
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].kind = 1;
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].offset = offsetof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ, filename);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[3].name = "filename";
TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].len = 3; TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].kind = 2; TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0].sons = &TM_Q8GDWOFB5uWKFMQFSo1oVw_2[0];
NTI_yi1kAYh8kb3f1o4vS0ZTBQ_.node = &TM_Q8GDWOFB5uWKFMQFSo1oVw_0[0];
NTI_5PWEcVklnzmjVvFuGsuXhQ_.size = sizeof(tyObject_BudgetFilecolonObjectType__yi1kAYh8kb3f1o4vS0ZTBQ*);
NTI_5PWEcVklnzmjVvFuGsuXhQ_.kind = 22;
NTI_5PWEcVklnzmjVvFuGsuXhQ_.base = (&NTI_yi1kAYh8kb3f1o4vS0ZTBQ_);
NTI_5PWEcVklnzmjVvFuGsuXhQ_.flags = 2;
NTI_5PWEcVklnzmjVvFuGsuXhQ_.marker = Marker_tyRef_5PWEcVklnzmjVvFuGsuXhQ;
}

