/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct TNimType;
struct TNimNode;
struct tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ;
struct RootObj;
struct tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw;
struct NimStringDesc;
struct TGenericSeq;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA;
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc_JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc_3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ : public RootObj {
tyProc_JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc_9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc_3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc_xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc_2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc_2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc_ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc_JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw : public tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ {
NimStringDesc* data;
NI pos;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
static N_NIMCALL(void, Marker_tyRef_1G0jiQbe7KwD5ADza5AZaw)(void* p, NI op);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_Z9cj1NxLXx79cYy9c4gbj6CAA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw)(tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg* a, void* p);
static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeStackTrace_njssp69aa7hvxte9bJ8uuDcg)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w& s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_LIB_PRIVATE N_NIMCALL(void, ssClose_QCxhJhdbGUiB08yc0fBeLg)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(void, asgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isOnStack_dJJW59cIgsBmT59aZrOM71Mg)(void* p);
static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd_Aq3rxetdTkDpVSXU7JqLPQ)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition_KgEn9bmq40bvWqBEE7YUgvQ)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, clamp_RrNgT2340KObgDMnZWSK5A)(NI x, NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition_Om0Yjh3VW2JrNe1mVaOhXA)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData_VwkmV0rE82KHQOm1pQyMKg)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData_VwkmV0rE82KHQOm1pQyMKg_2)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData_OOEfFmc9bLLbcXoH1cApdvA)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
extern TNimType NTI_ytyiCJqK439aF9cIibuRVpAg_;
TNimType NTI_THYguAi9bSgidczZ3ywEIMQ_;
TNimType NTI_JQrsH08b4uPTH9cyFPlVOZg_;
TNimType NTI_9bmhFrLahRsL2hltfRDVtlQ_;
TNimType NTI_3svSoGIUJIsHkaBL7q4DAQ_;
TNimType NTI_xflqkf2D1uVClg70czEDHA_;
TNimType NTI_2VVzVL9bOnKhj1eZKkf9cEuA_;
TNimType NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_;
TNimType NTI_1G0jiQbe7KwD5ADza5AZaw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_Olau5FPRehZBBEB77FHnfw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_5, "[SYSASSERT] ", 12);
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_6, "begin nimGCunrefNoCycle", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_4 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_5),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_6)}
;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_8, "[GCASSERT] ", 11);
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_9, "decRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_7 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_8),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_9)}
;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_11, "decRef", 6);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_10 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_8),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_11)}
;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_13, "end nimGCunrefNoCycle 5", 23);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_12 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_5),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_13)}
;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_15, "asgnRef", 7);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_14 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_8),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_15)}
;
STRING_LITERAL(TM_Ue7tnBcsL67VCiRfvt8q0A_17, "incRef: interiorPtr", 19);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_Ue7tnBcsL67VCiRfvt8q0A_16 = {((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_8),
((NimStringDesc*) &TM_Ue7tnBcsL67VCiRfvt8q0A_17)}
;
static N_NIMCALL(void, Marker_tyRef_1G0jiQbe7KwD5ADza5AZaw)(void* p, NI op) {
	tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* a;
	a = (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, readData_TYaWywfT8qLRVVdONIVhkw)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen) {
	NI result;
	nimfr_("readData", "streams.nim");
	result = (NI)0;
	nimln_(87, "streams.nim");
	result = (*s).readDataImpl(s, buffer, bufLen);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_Xz3YiEzNrT9cUBndwi4hNjw)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s) {
	nimfr_("close", "streams.nim");
	nimln_(66, "streams.nim");
	{
		if (!!(((*s).closeImpl == 0))) goto LA3_;
{		(*s).closeImpl(s);
}	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_Z9cj1NxLXx79cYy9c4gbj6CAA)(void* p, NI op) {
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* a;
	a = (tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*)p;
	nimGCvisit((void*)(*a).data, op);
}

static N_INLINE(void, GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem)(void) {
	gch_IcYaEuuWivYAS86vFMTS3Q.recGcLock += ((NI) 1);
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(187, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw(gch_IcYaEuuWivYAS86vFMTS3Q.zct, c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(190, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(190, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_7, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(191, "gc.nim");
	{
		nimln_(106, "gc.nim");
		nimln_(191, "gc.nim");
		if (!!(((NU64)(((NI) 8)) <= (NU64)((*c).refcount)))) goto LA8_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_10, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA8_: ;
	nimln_(192, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	nimln_(193, "gc.nim");
	{
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA12_;
{		nimln_(194, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_3system(c);
}	}
	LA12_: ;
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(125, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI) 16)))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(218, "gc.nim");
	{
		if (!NIM_FALSE) goto LA3_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_4, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA3_: ;
	nimln_(219, "gc.nim");
	decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p));
	nimln_(220, "gc.nim");
	{
		if (!NIM_FALSE) goto LA7_;
{		nimln_(1628, "system.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_12, 2);
		nimln_(1629, "system.nim");
		exit(((NI) 1));
}	}
	LA7_: ;
	popFrame();
}

static N_INLINE(void, incRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(174, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(174, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isAllocatedPtr_z2vVXV0fNaF6us30VoVfIw((&gch_IcYaEuuWivYAS86vFMTS3Q.region), ((void*) (c)));
		if (!!(T3_)) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_16, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(175, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(227, "gc.nim");
	{
		NIM_BOOL T3_;
		nimln_(106, "gc.nim");
		nimln_(227, "gc.nim");
		T3_ = (NIM_BOOL)0;
		T3_ = isOnStack_dJJW59cIgsBmT59aZrOM71Mg(((void*) (dest)));
		if (!!(!(T3_))) goto LA4_;
{		nimln_(107, "gc.nim");
		echoBinSafe(TM_Ue7tnBcsL67VCiRfvt8q0A_14, 2);
		nimln_(108, "gc.nim");
		GC_disable_neD9cJp4S9clvdaq5qqNFZAQsystem();
		nimln_(109, "gc.nim");
		writeStackTrace_njssp69aa7hvxte9bJ8uuDcg();
		nimln_(112, "gc.nim");
		exit(((NI) 1));
}	}
	LA4_: ;
	nimln_(229, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!((src == NIM_NIL))) goto LA8_;
{		nimln_(229, "gc.nim");
		incRef_MV4BBk6J1qu70IbBxwEn4wsystem(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src));
}	}
	LA8_: ;
	nimln_(230, "gc.nim");
	{
		nimln_(483, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA12_;
{		nimln_(230, "gc.nim");
		decRef_MV4BBk6J1qu70IbBxwEn4w_2system(usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest)));
}	}
	LA12_: ;
	nimln_(231, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, ssClose_QCxhJhdbGUiB08yc0fBeLg)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s) {
	nimfr_("ssClose", "streams.nim");
	nimln_(379, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(381, "streams.nim");
	asgnRef((void**) (&(*s_2).data), ((NimStringDesc*) NIM_NIL));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd_Aq3rxetdTkDpVSXU7JqLPQ)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s) {
	NIM_BOOL result;
	nimfr_("ssAtEnd", "streams.nim");
{	result = (NIM_BOOL)0;
	nimln_(341, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(342, "streams.nim");
	result = (((*s_2).data ? (*s_2).data->len : 0) <= (*s_2).pos);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition_KgEn9bmq40bvWqBEE7YUgvQ)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, NI pos) {
	nimfr_("ssSetPosition", "streams.nim");
	nimln_(345, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(346, "streams.nim");
	(*s_2).pos = clamp_RrNgT2340KObgDMnZWSK5A(pos, ((NI) 0), ((*s_2).data ? (*s_2).data->len : 0));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition_Om0Yjh3VW2JrNe1mVaOhXA)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s) {
	NI result;
	nimfr_("ssGetPosition", "streams.nim");
{	result = (NI)0;
	nimln_(349, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(350, "streams.nim");
	result = (*s_2).pos;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, ssReadData_VwkmV0rE82KHQOm1pQyMKg)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen) {
	NI result;
	NI TM_Ue7tnBcsL67VCiRfvt8q0A_18;
	nimfr_("ssReadData", "streams.nim");
	result = (NI)0;
	nimln_(353, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(354, "streams.nim");
	TM_Ue7tnBcsL67VCiRfvt8q0A_18 = subInt(((*s_2).data ? (*s_2).data->len : 0), (*s_2).pos);
	result = ((bufLen <= (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_18)) ? bufLen : (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_18));
	nimln_(355, "streams.nim");
	{
		NI TM_Ue7tnBcsL67VCiRfvt8q0A_19;
		if (!(((NI) 0) < result)) goto LA3_;
{		nimln_(356, "streams.nim");
		if ((NU)((*s_2).pos) >= (NU)((*s_2).data ? (*s_2).data->len : 0)) raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->len : 0)-1);
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(buffer, ((void*) ((&(*s_2).data->data[(*s_2).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(357, "streams.nim");
		TM_Ue7tnBcsL67VCiRfvt8q0A_19 = addInt((*s_2).pos, result);
		(*s_2).pos = (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_19);
}	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(359, "streams.nim");
		result = ((NI) 0);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData_VwkmV0rE82KHQOm1pQyMKg_2)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen) {
	NI result;
	NI TM_Ue7tnBcsL67VCiRfvt8q0A_20;
	nimfr_("ssPeekData", "streams.nim");
	result = (NI)0;
	nimln_(362, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(363, "streams.nim");
	TM_Ue7tnBcsL67VCiRfvt8q0A_20 = subInt(((*s_2).data ? (*s_2).data->len : 0), (*s_2).pos);
	result = ((bufLen <= (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_20)) ? bufLen : (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_20));
	nimln_(364, "streams.nim");
	{
		if (!(((NI) 0) < result)) goto LA3_;
{		nimln_(365, "streams.nim");
		if ((NU)((*s_2).pos) >= (NU)((*s_2).data ? (*s_2).data->len : 0)) raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->len : 0)-1);
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(buffer, ((void*) ((&(*s_2).data->data[(*s_2).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
}	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(367, "streams.nim");
		result = ((NI) 0);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, ssWriteData_OOEfFmc9bLLbcXoH1cApdvA)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen) {
	NI TM_Ue7tnBcsL67VCiRfvt8q0A_23;
	nimfr_("ssWriteData", "streams.nim");
{	nimln_(370, "streams.nim");
	if (s) chckObj((*s).m_type, (&NTI_Olau5FPRehZBBEB77FHnfw_));
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* s_2 = ((tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) (s));
	nimln_(371, "streams.nim");
	{
		if (!(bufLen <= ((NI) 0))) goto LA3_;
{		nimln_(372, "streams.nim");
		goto BeforeRet_;
}	}
	LA3_: ;
	nimln_(373, "streams.nim");
	{
		NI TM_Ue7tnBcsL67VCiRfvt8q0A_21;
		NI TM_Ue7tnBcsL67VCiRfvt8q0A_22;
		TM_Ue7tnBcsL67VCiRfvt8q0A_21 = addInt((*s_2).pos, bufLen);
		if (!(((*s_2).data ? (*s_2).data->len : 0) < (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_21))) goto LA7_;
{		nimln_(374, "streams.nim");
		TM_Ue7tnBcsL67VCiRfvt8q0A_22 = addInt((*s_2).pos, bufLen);
		asgnRef((void**) (&(*s_2).data), setLengthStr((*s_2).data, ((NI)chckRange((NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_22), ((NI) 0), ((NI) IL64(9223372036854775807))))));
}	}
	LA7_: ;
	nimln_(375, "streams.nim");
	if ((NU)((*s_2).pos) >= (NU)((*s_2).data ? (*s_2).data->len : 0)) raiseIndexError2((*s_2).pos,((*s_2).data ? (*s_2).data->len : 0)-1);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*s_2).data->data[(*s_2).pos]))), buffer, ((NI)chckRange(bufLen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(376, "streams.nim");
	TM_Ue7tnBcsL67VCiRfvt8q0A_23 = addInt((*s_2).pos, bufLen);
	(*s_2).pos = (NI)(TM_Ue7tnBcsL67VCiRfvt8q0A_23);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*, newStringStream_aIf1Q9cTTlEW5dnj9ciC0odg)(NimStringDesc* s) {
	tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw* result;
	NimStringDesc* T1_;
	nimfr_("newStringStream", "streams.nim");
	result = (tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*)0;
	nimln_(387, "streams.nim");
	result = (tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*) newObj((&NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_), sizeof(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw));
	(*result).m_type = (&NTI_Olau5FPRehZBBEB77FHnfw_);
	nimln_(388, "streams.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).data; (*result).data = copyStringRC1(s);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(389, "streams.nim");
	(*result).pos = ((NI) 0);
	nimln_(390, "streams.nim");
	(*result).closeImpl = ssClose_QCxhJhdbGUiB08yc0fBeLg;
	nimln_(391, "streams.nim");
	(*result).atEndImpl = ssAtEnd_Aq3rxetdTkDpVSXU7JqLPQ;
	nimln_(392, "streams.nim");
	(*result).setPositionImpl = ssSetPosition_KgEn9bmq40bvWqBEE7YUgvQ;
	nimln_(393, "streams.nim");
	(*result).getPositionImpl = ssGetPosition_Om0Yjh3VW2JrNe1mVaOhXA;
	nimln_(394, "streams.nim");
	(*result).readDataImpl = ssReadData_VwkmV0rE82KHQOm1pQyMKg;
	nimln_(395, "streams.nim");
	(*result).peekDataImpl = ssPeekData_VwkmV0rE82KHQOm1pQyMKg_2;
	nimln_(396, "streams.nim");
	(*result).writeDataImpl = ssWriteData_OOEfFmc9bLLbcXoH1cApdvA;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_streamsDatInit000)(void) {
static TNimNode* TM_Ue7tnBcsL67VCiRfvt8q0A_2[8];
static TNimNode* TM_Ue7tnBcsL67VCiRfvt8q0A_3[2];
static TNimNode TM_Ue7tnBcsL67VCiRfvt8q0A_0[12];
NTI_THYguAi9bSgidczZ3ywEIMQ_.size = sizeof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ);
NTI_THYguAi9bSgidczZ3ywEIMQ_.kind = 17;
NTI_THYguAi9bSgidczZ3ywEIMQ_.base = (&NTI_ytyiCJqK439aF9cIibuRVpAg_);
NTI_THYguAi9bSgidczZ3ywEIMQ_.flags = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_2[0] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[1];
NTI_JQrsH08b4uPTH9cyFPlVOZg_.size = sizeof(tyProc_JQrsH08b4uPTH9cyFPlVOZg);
NTI_JQrsH08b4uPTH9cyFPlVOZg_.kind = 25;
NTI_JQrsH08b4uPTH9cyFPlVOZg_.base = 0;
NTI_JQrsH08b4uPTH9cyFPlVOZg_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[1].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[1].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, closeImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[1].typ = (&NTI_JQrsH08b4uPTH9cyFPlVOZg_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[1].name = "closeImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[1] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[2];
NTI_9bmhFrLahRsL2hltfRDVtlQ_.size = sizeof(tyProc_9bmhFrLahRsL2hltfRDVtlQ);
NTI_9bmhFrLahRsL2hltfRDVtlQ_.kind = 25;
NTI_9bmhFrLahRsL2hltfRDVtlQ_.base = 0;
NTI_9bmhFrLahRsL2hltfRDVtlQ_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[2].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[2].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, atEndImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[2].typ = (&NTI_9bmhFrLahRsL2hltfRDVtlQ_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[2].name = "atEndImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[2] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[3];
NTI_3svSoGIUJIsHkaBL7q4DAQ_.size = sizeof(tyProc_3svSoGIUJIsHkaBL7q4DAQ);
NTI_3svSoGIUJIsHkaBL7q4DAQ_.kind = 25;
NTI_3svSoGIUJIsHkaBL7q4DAQ_.base = 0;
NTI_3svSoGIUJIsHkaBL7q4DAQ_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[3].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[3].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, setPositionImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[3].typ = (&NTI_3svSoGIUJIsHkaBL7q4DAQ_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[3].name = "setPositionImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[3] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[4];
NTI_xflqkf2D1uVClg70czEDHA_.size = sizeof(tyProc_xflqkf2D1uVClg70czEDHA);
NTI_xflqkf2D1uVClg70czEDHA_.kind = 25;
NTI_xflqkf2D1uVClg70czEDHA_.base = 0;
NTI_xflqkf2D1uVClg70czEDHA_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[4].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[4].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, getPositionImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[4].typ = (&NTI_xflqkf2D1uVClg70czEDHA_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[4].name = "getPositionImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[4] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[5];
NTI_2VVzVL9bOnKhj1eZKkf9cEuA_.size = sizeof(tyProc_2VVzVL9bOnKhj1eZKkf9cEuA);
NTI_2VVzVL9bOnKhj1eZKkf9cEuA_.kind = 25;
NTI_2VVzVL9bOnKhj1eZKkf9cEuA_.base = 0;
NTI_2VVzVL9bOnKhj1eZKkf9cEuA_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[5].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[5].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, readDataImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[5].typ = (&NTI_2VVzVL9bOnKhj1eZKkf9cEuA_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[5].name = "readDataImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[5] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[6];
TM_Ue7tnBcsL67VCiRfvt8q0A_0[6].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[6].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, peekDataImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[6].typ = (&NTI_2VVzVL9bOnKhj1eZKkf9cEuA_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[6].name = "peekDataImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[6] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[7];
NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_.size = sizeof(tyProc_ki6p1QyfOkJLQJ9aw5NI0AQ);
NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_.kind = 25;
NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_.base = 0;
NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_.flags = 3;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[7].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[7].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, writeDataImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[7].typ = (&NTI_ki6p1QyfOkJLQJ9aw5NI0AQ_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[7].name = "writeDataImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_2[7] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[8];
TM_Ue7tnBcsL67VCiRfvt8q0A_0[8].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[8].offset = offsetof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ, flushImpl);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[8].typ = (&NTI_JQrsH08b4uPTH9cyFPlVOZg_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[8].name = "flushImpl";
TM_Ue7tnBcsL67VCiRfvt8q0A_0[0].len = 8; TM_Ue7tnBcsL67VCiRfvt8q0A_0[0].kind = 2; TM_Ue7tnBcsL67VCiRfvt8q0A_0[0].sons = &TM_Ue7tnBcsL67VCiRfvt8q0A_2[0];
NTI_THYguAi9bSgidczZ3ywEIMQ_.node = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[0];
NTI_1G0jiQbe7KwD5ADza5AZaw_.size = sizeof(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ*);
NTI_1G0jiQbe7KwD5ADza5AZaw_.kind = 22;
NTI_1G0jiQbe7KwD5ADza5AZaw_.base = (&NTI_THYguAi9bSgidczZ3ywEIMQ_);
NTI_1G0jiQbe7KwD5ADza5AZaw_.marker = Marker_tyRef_1G0jiQbe7KwD5ADza5AZaw;
NTI_Olau5FPRehZBBEB77FHnfw_.size = sizeof(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw);
NTI_Olau5FPRehZBBEB77FHnfw_.kind = 17;
NTI_Olau5FPRehZBBEB77FHnfw_.base = (&NTI_THYguAi9bSgidczZ3ywEIMQ_);
TM_Ue7tnBcsL67VCiRfvt8q0A_3[0] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[10];
TM_Ue7tnBcsL67VCiRfvt8q0A_0[10].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[10].offset = offsetof(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw, data);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[10].name = "data";
TM_Ue7tnBcsL67VCiRfvt8q0A_3[1] = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[11];
TM_Ue7tnBcsL67VCiRfvt8q0A_0[11].kind = 1;
TM_Ue7tnBcsL67VCiRfvt8q0A_0[11].offset = offsetof(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw, pos);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_Ue7tnBcsL67VCiRfvt8q0A_0[11].name = "pos";
TM_Ue7tnBcsL67VCiRfvt8q0A_0[9].len = 2; TM_Ue7tnBcsL67VCiRfvt8q0A_0[9].kind = 2; TM_Ue7tnBcsL67VCiRfvt8q0A_0[9].sons = &TM_Ue7tnBcsL67VCiRfvt8q0A_3[0];
NTI_Olau5FPRehZBBEB77FHnfw_.node = &TM_Ue7tnBcsL67VCiRfvt8q0A_0[9];
NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_.size = sizeof(tyObject_StringStreamObj_Olau5FPRehZBBEB77FHnfw*);
NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_.kind = 22;
NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_.base = (&NTI_Olau5FPRehZBBEB77FHnfw_);
NTI_Z9cj1NxLXx79cYy9c4gbj6CAA_.marker = Marker_tyRef_Z9cj1NxLXx79cYy9c4gbj6CAA;
}

