/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct TNimType;
struct TNimNode;
struct tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg;
struct RootObj;
struct tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ;
struct NimStringDesc;
struct TGenericSeq;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg : public RootObj {
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, tyProc_JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc_3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ : public RootObj {
tyProc_JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc_9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc_3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc_xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc_2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc_2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc_ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc_JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, memTrackerWrite)(void* address, NI size, NCSTRING file, NI line);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA)(NI size);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, fillBuffer_CbKzA44X2DxZAmasZ72O9ag)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L);
static N_INLINE(void, moveMem_E1xtACub5WcDa3vbrIXbwglexbase)(void* dest, void* source, NI size);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, readData_TYaWywfT8qLRVVdONIVhkw)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_LIB_PRIVATE N_NOCONV(void*, realloc_y4TzCoc3hQhz9cedxS9cbemA)(void* p, NI newSize);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom_C48Lrx2vPoZzafxipbCXsQ)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L);
N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer_06CFAwuLiai9b5aILbOFkBQ_2)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L, NI pos);
N_LIB_PRIVATE N_NOCONV(void, dealloc_RCjNtRnHdRYntrcE7YtwWw)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, close_Xz3YiEzNrT9cUBndwi4hNjw)(tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* s);
extern TNimType NTI_ytyiCJqK439aF9cIibuRVpAg_;
TNimType NTI_MAw8rJZtJ279bVV3TWMtXSg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_S9agCYBinaYZnGWcjTdxclg_;
extern TNimType NTI_1G0jiQbe7KwD5ADza5AZaw_;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw_;
TNimType NTI_HDqWPvEAxZK51ZcfaeQEdg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_3, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(146, 9) `bufLen > 0` ", 62);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_4, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(147, 9) `input != nil`"
" ", 64);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_7, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(60, 9) `L.sentinel < L"
".bufLen` ", 72);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_10, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(62, 9) `toCopy >= 0` ", 62);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_19, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(79, 13) `s < L.bufLen`"
" ", 64);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_24, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(94, 15) `L.bufLen - ol"
"dBufLen == oldBufLen` ", 85);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_32, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(117, 9) `L.buf[pos] =="
" \'\\c\'` ", 70);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_34, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(104, 9) `pos <= L.sent"
"inel` ", 69);
STRING_LITERAL(TM_k6p5NxDJat9aTyZxfZjCDJQ_37, "/Users/matt/lib/Nim/lib/pure/lexbase.nim(128, 9) `L.buf[pos] =="
" \'\\n\'` ", 70);

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, moveMem_E1xtACub5WcDa3vbrIXbwglexbase)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memmove(dest, source, ((size_t) (size)));
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
{		raiseOverflow();
}	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, fillBuffer_CbKzA44X2DxZAmasZ72O9ag)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L) {
	NI charsRead;
	NI toCopy;
	NI s;
	NI oldBufLen;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_8;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_9;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_13;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_14;
	NI T13_;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_15;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_16;
	nimfr_("fillBuffer", "lexbase.nim");
	charsRead = (NI)0;
	toCopy = (NI)0;
	s = (NI)0;
	oldBufLen = (NI)0;
	nimln_(60, "lexbase.nim");
	{
		if (!!((L.sentinel < L.bufLen))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_7));
}	}
	LA3_: ;
	nimln_(61, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_8 = subInt(L.bufLen, L.sentinel);
	TM_k6p5NxDJat9aTyZxfZjCDJQ_9 = subInt((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_8), ((NI) 1));
	toCopy = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_9);
	nimln_(62, "lexbase.nim");
	{
		if (!!((((NI) 0) <= toCopy))) goto LA7_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_10));
}	}
	LA7_: ;
	nimln_(63, "lexbase.nim");
	{
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_11;
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_12;
		if (!(((NI) 0) < toCopy)) goto LA11_;
{		nimln_(68, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_11 = addInt(L.sentinel, ((NI) 1));
		TM_k6p5NxDJat9aTyZxfZjCDJQ_12 = mulInt(toCopy, ((NI) 1));
		moveMem_E1xtACub5WcDa3vbrIXbwglexbase(((void*) (L.buf)), ((void*) ((&L.buf[(NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_11)]))), ((NI)chckRange((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_12), ((NI) 0), ((NI) IL64(9223372036854775807)))));
}	}
	LA11_: ;
	nimln_(70, "lexbase.nim");
	nimln_(69, "lexbase.nim");
	nimln_(70, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_13 = addInt(L.sentinel, ((NI) 1));
	TM_k6p5NxDJat9aTyZxfZjCDJQ_14 = mulInt((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_13), ((NI) 1));
	T13_ = (NI)0;
	T13_ = readData_TYaWywfT8qLRVVdONIVhkw(L.input, ((void*) ((&L.buf[toCopy]))), (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_14));
	TM_k6p5NxDJat9aTyZxfZjCDJQ_15 = divInt(T13_, ((NI) 1));
	charsRead = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_15);
	nimln_(71, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_16 = addInt(toCopy, charsRead);
	s = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_16);
	nimln_(72, "lexbase.nim");
	{
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_17;
		TM_k6p5NxDJat9aTyZxfZjCDJQ_17 = addInt(L.sentinel, ((NI) 1));
		if (!(charsRead < (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_17))) goto LA16_;
{		nimln_(73, "lexbase.nim");
		L.buf[s] = 0;
		memTrackerWrite((void*)(&L.buf[s]), 1, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 73);
		nimln_(74, "lexbase.nim");
		L.sentinel = s;
		memTrackerWrite((void*)(&L.sentinel), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 74);
}	}
	goto LA14_;
	LA16_: ;
	{
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_18;
		nimln_(77, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_18 = subInt(s, ((NI) 1));
		s = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_18);
		{
			nimln_(78, "lexbase.nim");
			while (1) {
				nimln_(79, "lexbase.nim");
				{
					if (!!((s < L.bufLen))) goto LA23_;
{					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_19));
}				}
				LA23_: ;
				{
					nimln_(80, "lexbase.nim");
					while (1) {
						NIM_BOOL T27_;
						NI TM_k6p5NxDJat9aTyZxfZjCDJQ_20;
						T27_ = (NIM_BOOL)0;
						T27_ = (((NI) 0) <= s);
						if (!(T27_)) goto LA28_;
						nimln_(1309, "system.nim");
						T27_ = !(((L.refillChars[(NU)(((NU8)(L.buf[s])))>>3] &(1U<<((NU)(((NU8)(L.buf[s])))&7U)))!=0));
						LA28_: ;
						if (!T27_) goto LA26;
						nimln_(80, "lexbase.nim");
						TM_k6p5NxDJat9aTyZxfZjCDJQ_20 = subInt(s, ((NI) 1));
						s = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_20);
					} LA26: ;
				}
				nimln_(81, "lexbase.nim");
				{
					if (!(((NI) 0) <= s)) goto LA31_;
{					nimln_(83, "lexbase.nim");
					L.sentinel = s;
					memTrackerWrite((void*)(&L.sentinel), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 83);
					nimln_(84, "lexbase.nim");
					goto LA19;
}				}
				goto LA29_;
				LA31_: ;
				{
					NI TM_k6p5NxDJat9aTyZxfZjCDJQ_21;
					NI TM_k6p5NxDJat9aTyZxfZjCDJQ_22;
					void* T34_;
					NI TM_k6p5NxDJat9aTyZxfZjCDJQ_25;
					NI T39_;
					NI TM_k6p5NxDJat9aTyZxfZjCDJQ_26;
					NI TM_k6p5NxDJat9aTyZxfZjCDJQ_29;
					nimln_(88, "lexbase.nim");
					oldBufLen = L.bufLen;
					nimln_(89, "lexbase.nim");
					TM_k6p5NxDJat9aTyZxfZjCDJQ_21 = mulInt(L.bufLen, ((NI) 2));
					L.bufLen = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_21);
					memTrackerWrite((void*)(&L.bufLen), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 89);
					nimln_(93, "lexbase.nim");
					TM_k6p5NxDJat9aTyZxfZjCDJQ_22 = mulInt(L.bufLen, ((NI) 1));
					T34_ = (void*)0;
					T34_ = realloc_y4TzCoc3hQhz9cedxS9cbemA(((void*) (L.buf)), ((NI)chckRange((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_22), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					L.buf = ((NCSTRING) (T34_));
					memTrackerWrite((void*)(&L.buf), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 93);
					nimln_(94, "lexbase.nim");
					{
						NI TM_k6p5NxDJat9aTyZxfZjCDJQ_23;
						TM_k6p5NxDJat9aTyZxfZjCDJQ_23 = subInt(L.bufLen, oldBufLen);
						if (!!(((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_23) == oldBufLen))) goto LA37_;
{						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_24));
}					}
					LA37_: ;
					nimln_(96, "lexbase.nim");
					nimln_(95, "lexbase.nim");
					nimln_(96, "lexbase.nim");
					TM_k6p5NxDJat9aTyZxfZjCDJQ_25 = mulInt(oldBufLen, ((NI) 1));
					T39_ = (NI)0;
					T39_ = readData_TYaWywfT8qLRVVdONIVhkw(L.input, ((void*) ((&L.buf[oldBufLen]))), (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_25));
					TM_k6p5NxDJat9aTyZxfZjCDJQ_26 = divInt(T39_, ((NI) 1));
					charsRead = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_26);
					nimln_(97, "lexbase.nim");
					{
						NI TM_k6p5NxDJat9aTyZxfZjCDJQ_27;
						NI TM_k6p5NxDJat9aTyZxfZjCDJQ_28;
						if (!(charsRead < oldBufLen)) goto LA42_;
{						nimln_(98, "lexbase.nim");
						TM_k6p5NxDJat9aTyZxfZjCDJQ_27 = addInt(oldBufLen, charsRead);
						L.buf[(NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_27)] = 0;
						memTrackerWrite((void*)(&L.buf[(NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_27)]), 1, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 98);
						nimln_(99, "lexbase.nim");
						TM_k6p5NxDJat9aTyZxfZjCDJQ_28 = addInt(oldBufLen, charsRead);
						L.sentinel = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_28);
						memTrackerWrite((void*)(&L.sentinel), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 99);
						nimln_(100, "lexbase.nim");
						goto LA19;
}					}
					LA42_: ;
					nimln_(101, "lexbase.nim");
					TM_k6p5NxDJat9aTyZxfZjCDJQ_29 = subInt(L.bufLen, ((NI) 1));
					s = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_29);
				}
				LA29_: ;
			}
		} LA19: ;
	}
	LA14_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom_C48Lrx2vPoZzafxipbCXsQ)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L) {
	nimfr_("skipUtf8Bom", "lexbase.nim");
	nimln_(139, "lexbase.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_30;
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_31;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = ((NU8)(L.buf[((NI) 0)]) == (NU8)(239));
		if (!(T4_)) goto LA5_;
		T4_ = ((NU8)(L.buf[((NI) 1)]) == (NU8)(187));
		LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		T3_ = ((NU8)(L.buf[((NI) 2)]) == (NU8)(191));
		LA6_: ;
		if (!T3_) goto LA7_;
{		nimln_(140, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_30 = addInt(L.bufpos, ((NI) 3));
		L.bufpos = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_30);
		memTrackerWrite((void*)(&L.bufpos), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 140);
		nimln_(141, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_31 = addInt(L.lineStart, ((NI) 3));
		L.lineStart = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_31);
		memTrackerWrite((void*)(&L.lineStart), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 141);
}	}
	LA7_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, open_0F9asrCjxjKO6tNQQ4Cv3Jg)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L, tyObject_StreamObj_THYguAi9bSgidczZ3ywEIMQ* input, NI bufLen, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars) {
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_5;
	void* T9_;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_6;
	nimfr_("open", "lexbase.nim");
	nimln_(146, "lexbase.nim");
	{
		if (!!((((NI) 0) < bufLen))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_3));
}	}
	LA3_: ;
	nimln_(147, "lexbase.nim");
	{
		if (!!(!((input == NIM_NIL)))) goto LA7_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_4));
}	}
	LA7_: ;
	nimln_(148, "lexbase.nim");
	L.input = input;
	memTrackerWrite((void*)(&L.input), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 148);
	nimln_(149, "lexbase.nim");
	L.bufpos = ((NI) 0);
	memTrackerWrite((void*)(&L.bufpos), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 149);
	nimln_(150, "lexbase.nim");
	L.offsetBase = ((NI) 0);
	memTrackerWrite((void*)(&L.offsetBase), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 150);
	nimln_(151, "lexbase.nim");
	L.bufLen = bufLen;
	memTrackerWrite((void*)(&L.bufLen), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 151);
	nimln_(152, "lexbase.nim");
	nimCopyMem((void*)L.refillChars, (NIM_CONST void*)refillChars, 32);
	memTrackerWrite((void*)L.refillChars, 32, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 152);
	nimln_(156, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_5 = mulInt(bufLen, ((NI) 1));
	T9_ = (void*)0;
	T9_ = alloc_sVm4rDImKK2ZDdylByayiA(((NI)chckRange((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_5), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	L.buf = ((NCSTRING) (T9_));
	memTrackerWrite((void*)(&L.buf), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 156);
	nimln_(157, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_6 = subInt(bufLen, ((NI) 1));
	L.sentinel = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_6);
	memTrackerWrite((void*)(&L.sentinel), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 157);
	nimln_(158, "lexbase.nim");
	L.lineStart = ((NI) 0);
	memTrackerWrite((void*)(&L.lineStart), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 158);
	nimln_(159, "lexbase.nim");
	L.lineNumber = ((NI) 1);
	memTrackerWrite((void*)(&L.lineNumber), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 159);
	nimln_(160, "lexbase.nim");
	fillBuffer_CbKzA44X2DxZAmasZ72O9ag(L);
	nimln_(161, "lexbase.nim");
	skipUtf8Bom_C48Lrx2vPoZzafxipbCXsQ(L);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer_06CFAwuLiai9b5aILbOFkBQ_2)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L, NI pos) {
	NI result;
	nimfr_("fillBaseLexer", "lexbase.nim");
	result = (NI)0;
	nimln_(104, "lexbase.nim");
	{
		if (!!((pos <= L.sentinel))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_34));
}	}
	LA3_: ;
	nimln_(105, "lexbase.nim");
	{
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_35;
		if (!(pos < L.sentinel)) goto LA7_;
{		nimln_(106, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_35 = addInt(pos, ((NI) 1));
		result = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_35);
}	}
	goto LA5_;
	LA7_: ;
	{
		NI TM_k6p5NxDJat9aTyZxfZjCDJQ_36;
		nimln_(108, "lexbase.nim");
		fillBuffer_CbKzA44X2DxZAmasZ72O9ag(L);
		nimln_(109, "lexbase.nim");
		TM_k6p5NxDJat9aTyZxfZjCDJQ_36 = addInt(L.offsetBase, pos);
		L.offsetBase = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_36);
		memTrackerWrite((void*)(&L.offsetBase), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 109);
		nimln_(110, "lexbase.nim");
		L.bufpos = ((NI) 0);
		memTrackerWrite((void*)(&L.bufpos), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 110);
		nimln_(111, "lexbase.nim");
		result = ((NI) 0);
	}
	LA5_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, handleCR_06CFAwuLiai9b5aILbOFkBQ)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L, NI pos) {
	NI result;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_33;
	nimfr_("handleCR", "lexbase.nim");
	result = (NI)0;
	nimln_(117, "lexbase.nim");
	{
		if (!!(((NU8)(L.buf[pos]) == (NU8)(13)))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_32));
}	}
	LA3_: ;
	nimln_(118, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_33 = addInt(L.lineNumber, ((NI) 1));
	L.lineNumber = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_33);
	memTrackerWrite((void*)(&L.lineNumber), 8, "/Users/matt/lib/Nim/lib/system.nim", 740);
	nimln_(119, "lexbase.nim");
	result = fillBaseLexer_06CFAwuLiai9b5aILbOFkBQ_2(L, pos);
	nimln_(120, "lexbase.nim");
	{
		if (!((NU8)(L.buf[result]) == (NU8)(10))) goto LA7_;
{		nimln_(121, "lexbase.nim");
		result = fillBaseLexer_06CFAwuLiai9b5aILbOFkBQ_2(L, result);
}	}
	LA7_: ;
	nimln_(122, "lexbase.nim");
	L.lineStart = result;
	memTrackerWrite((void*)(&L.lineStart), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 122);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, handleLF_06CFAwuLiai9b5aILbOFkBQ_3)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L, NI pos) {
	NI result;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_38;
	nimfr_("handleLF", "lexbase.nim");
	result = (NI)0;
	nimln_(128, "lexbase.nim");
	{
		if (!!(((NU8)(L.buf[pos]) == (NU8)(10)))) goto LA3_;
{		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k6p5NxDJat9aTyZxfZjCDJQ_37));
}	}
	LA3_: ;
	nimln_(129, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_38 = addInt(L.lineNumber, ((NI) 1));
	L.lineNumber = (NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_38);
	memTrackerWrite((void*)(&L.lineNumber), 8, "/Users/matt/lib/Nim/lib/system.nim", 740);
	nimln_(130, "lexbase.nim");
	result = fillBaseLexer_06CFAwuLiai9b5aILbOFkBQ_2(L, pos);
	nimln_(131, "lexbase.nim");
	L.lineStart = result;
	memTrackerWrite((void*)(&L.lineStart), 8, "/Users/matt/lib/Nim/lib/pure/lexbase.nim", 131);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getColNumber_4JlSbzU43eqzH08Ig7q65A)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg* L, NI pos) {
	NI result;
	NI TM_k6p5NxDJat9aTyZxfZjCDJQ_39;
	nimfr_("getColNumber", "lexbase.nim");
	result = (NI)0;
	nimln_(165, "lexbase.nim");
	TM_k6p5NxDJat9aTyZxfZjCDJQ_39 = subInt(pos, (*L).lineStart);
	if ((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_39) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
	result = ((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_39) > 0? ((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_39)) : -((NI)(TM_k6p5NxDJat9aTyZxfZjCDJQ_39)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_CbKzA44X2DxZAmasZ72O9ag_2)(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg& L) {
	nimfr_("close", "lexbase.nim");
	nimln_(49, "lexbase.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(((void*) (L.buf)));
	nimln_(50, "lexbase.nim");
	close_Xz3YiEzNrT9cUBndwi4hNjw(L.input);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_lexbaseDatInit000)(void) {
static TNimNode* TM_k6p5NxDJat9aTyZxfZjCDJQ_2[9];
static TNimNode TM_k6p5NxDJat9aTyZxfZjCDJQ_0[11];
NTI_MAw8rJZtJ279bVV3TWMtXSg_.size = sizeof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg);
NTI_MAw8rJZtJ279bVV3TWMtXSg_.kind = 17;
NTI_MAw8rJZtJ279bVV3TWMtXSg_.base = (&NTI_ytyiCJqK439aF9cIibuRVpAg_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[0] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[1];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[1].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[1].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, bufpos);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[1].name = "bufpos";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[1] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[2];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[2].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[2].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, buf);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[2].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[2].name = "buf";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[2] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[3];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[3].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[3].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, bufLen);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[3].name = "bufLen";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[3] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[4];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[4].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[4].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, input);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[4].typ = (&NTI_1G0jiQbe7KwD5ADza5AZaw_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[4].name = "input";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[4] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[5];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[5].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[5].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, lineNumber);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[5].name = "lineNumber";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[5] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[6];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[6].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[6].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, sentinel);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[6].name = "sentinel";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[6] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[7];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[7].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[7].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, lineStart);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[7].name = "lineStart";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[7] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[8];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[8].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[8].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, offsetBase);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[8].name = "offsetBase";
TM_k6p5NxDJat9aTyZxfZjCDJQ_2[8] = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[9];
NTI_HDqWPvEAxZK51ZcfaeQEdg_.size = sizeof(tySet_tyChar_nmiMWKVIe46vacnhAFrQvw);
NTI_HDqWPvEAxZK51ZcfaeQEdg_.kind = 19;
NTI_HDqWPvEAxZK51ZcfaeQEdg_.base = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
NTI_HDqWPvEAxZK51ZcfaeQEdg_.flags = 3;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[10].len = 0; TM_k6p5NxDJat9aTyZxfZjCDJQ_0[10].kind = 0;
NTI_HDqWPvEAxZK51ZcfaeQEdg_.node = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[10];
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[9].kind = 1;
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[9].offset = offsetof(tyObject_BaseLexer_MAw8rJZtJ279bVV3TWMtXSg, refillChars);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[9].typ = (&NTI_HDqWPvEAxZK51ZcfaeQEdg_);
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[9].name = "refillChars";
TM_k6p5NxDJat9aTyZxfZjCDJQ_0[0].len = 9; TM_k6p5NxDJat9aTyZxfZjCDJQ_0[0].kind = 2; TM_k6p5NxDJat9aTyZxfZjCDJQ_0[0].sons = &TM_k6p5NxDJat9aTyZxfZjCDJQ_2[0];
NTI_MAw8rJZtJ279bVV3TWMtXSg_.node = &TM_k6p5NxDJat9aTyZxfZjCDJQ_0[0];
}

