/* Generated by Nim Compiler v0.19.9 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <time.h>
#include <string.h>
#include <sys/select.h>
#include <sys/types.h>
#include <sys/time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw;
struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ;
struct tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q;
struct NimStringDesc;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct tyTuple_WCz3Z7at9aJyVFSh5OmwJNg;
struct tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ;
struct RootObj;
struct tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw;
struct tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw;
struct tyTuple_XjuGlLf9cyYx66ViXrBCvPQ;
struct tyTuple_47w2DboNEPf69aPgubZdd7Q;
struct tyTuple_pfrdooyxJsC6cg34ebuBag;
struct tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ {
tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time;
NI utcOffset;
NIM_BOOL isDst;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, ClP_0) (tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q x, void* ClE_0);
void* ClE_0;
} tyProc_bs1dgeTxHIjPGTR9axkkHbg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw {
tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromTimeImpl;
tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromAdjTimeImpl;
NimStringDesc* name;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple_WCz3Z7at9aJyVFSh5OmwJNg {
void* Field0;
tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ* Field1;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ : public RootObj {
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw;
typedef NU8 tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg;
struct tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw : public RootObj {
NI nanosecond;
NI second;
NI minute;
NI hour;
NI monthday;
tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month;
NI year;
tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg weekday;
NI yearday;
NIM_BOOL isDst;
tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* timezone;
NI utcOffset;
};
struct tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw {
NI64 seconds;
NI nanosecond;
};
typedef NU8 tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ;
typedef NI64 tyArray_pDfjTbtkTNjmi9bTcaNV32Q[8];
struct tyTuple_XjuGlLf9cyYx66ViXrBCvPQ {
NI Field0;
tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw Field1;
NI Field2;
};
struct tyTuple_47w2DboNEPf69aPgubZdd7Q {
NI Field0;
NI Field1;
NI Field2;
};
typedef NI tyArray_Splpnswz3rudLg9bDsQoDXg[12];
typedef N_CLOSURE_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, TM_6NbDwwj5FY059b1gz2AsAZQ_115) (tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q x);
struct tyTuple_pfrdooyxJsC6cg34ebuBag {
NI Field0;
NIM_BOOL Field1;
};
typedef N_CLOSURE_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, TM_6NbDwwj5FY059b1gz2AsAZQ_127) (tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time, void* ClE_0);
typedef N_CLOSURE_PTR(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, TM_6NbDwwj5FY059b1gz2AsAZQ_133) (tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q adjTime, void* ClE_0);
static N_NIMCALL(void, Marker_tyRef_qs7rcJOE2Bz63jdUEPJtIg)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op);
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_4)(void);
N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_5)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, now_tfUyEAJWC9aO9bQAg4deAWvw)(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result);
N_LIB_PRIVATE N_NIMCALL(void, local_GO0pnrIM1y5cQBpG7t80Hw)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q t, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result);
N_LIB_PRIVATE N_NIMCALL(void, inZone_iGIETwnU9aL9a9azchD7uIsBw)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time, tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result);
N_LIB_PRIVATE N_NIMCALL(void, initDateTime_9cjTDoh0YFNVFpY3GfapxqQ)(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ* zt, tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, ntSubTime)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q a, tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, normalize_MABftnLbgeoJ2YU4meiGug)(NI64 seconds, NI64 nanoseconds);
static N_INLINE(NI64, convert_qLUW0NdF1GYEPO7DWw0ntgtimes)(tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity);
static N_INLINE(NI64, divInt64)(NI64 a, NI64 b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI64, mulInt64)(NI64 a, NI64 b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI64, addInt64)(NI64 a, NI64 b);
static N_INLINE(NI, convert_BaHZhTECbIab21aey78Ozgtimes)(tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity);
static N_INLINE(NI64, modInt64)(NI64 a, NI64 b);
static N_INLINE(NI64, subInt64)(NI64 a, NI64 b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw, initDuration_EjaBAtfRmIw9c8MVpZyLTAg)(NI64 nanoseconds, NI64 microseconds, NI64 milliseconds, NI64 seconds, NI64 minutes, NI64 hours, NI64 days, NI64 weeks);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw, normalize_Zdw9awMN3mWHIiqmlxFaGrw)(NI64 seconds, NI64 nanoseconds);
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv_Nvq3S3GNjkBxHjfOZFJjRw)(NI64 x, NI64 y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_XjuGlLf9cyYx66ViXrBCvPQ, fromEpochDay_mJEaQzDB47WyotCnk4B9c2A)(NI64 epochday);
N_NIMCALL(NI64, chckRange64)(NI64 i, NI64 a, NI64 b);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg, getDayOfWeek_NgjKhNpZaAlscp2jmCchuA)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year);
static N_INLINE(void, assertValidDate_oFHP8g45fJYczB5bgKWFQQtimes)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year);
N_LIB_PRIVATE N_NIMCALL(NI, getDaysInMonth_Du19c9a9bSALs8RVBtDxc7Zjg)(tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLeapYear_yparhddyYdVywEbz0lSrTA)(NI year);
static N_INLINE(NI, modInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NI64, toEpochDay_BB6kKpP0ite6Jp9a5rrEt5w)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, getDayOfYear_MH9agrbA2S9bCWbHnQW6iSgg)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year);
N_NOINLINE(void, raiseIndexError3)(NI i, NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, zonedTimeFromTime_Rxfqncxm2ZLhLZdNFIq9a9bw)(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time);
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*, local_iX2Ltm3Mj5gsgJ5hFxUKgQ)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*, newTimezone_tF9bfmgadDtneoj4dZjS8QQ)(NimStringDesc* name, tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromTimeImpl, tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromAdjTimeImpl);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, localZonedTimeFromTime_ODvPcoZ6jtenmqLq9aVXBvg)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time);
N_LIB_PRIVATE N_NIMCALL(tyTuple_pfrdooyxJsC6cg34ebuBag, getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg)(NI64 unix);
N_LIB_PRIVATE N_NIMCALL(NI64, clamp_QUt10jOE7hoF4h8P6Cgfqg)(NI64 x, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI64, toAdjUnix_VMBhkoIwSpuOXS0EPc9cd1g)(struct tm tm);
N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, localZonedTimeFromAdjTime_09bwaQmOse9czkLeY30l6MIA)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q adjTime);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, initTime_UQc07zVQAYQ0by6TamgL9bQ)(NI64 unix, NI nanosecond);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, getTime_NtnAfG7BP2zKh2DoyUbakQ)(void);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* utcInstance_oeKVHn4dFpBJO35HhEkelw;
TNimType NTI_F8OvqlxXyGXRSiK9c1fCDVw_;
TNimType NTI_bs1dgeTxHIjPGTR9axkkHbg_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_ytyiCJqK439aF9cIibuRVpAg_;
TNimType NTI_4Ve8wOWSE8Hdar7fr5TdwQ_;
TNimType NTI_qs7rcJOE2Bz63jdUEPJtIg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_9a5v4OQPlGqsA25ioN8hFYA_;
tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA;
TNimType NTI_d9cK9cyKZPJJxFXUmx8dSpPw_;
extern TNimType NTI_PpavWgyrx5odXyR89aNlcWA_;
extern TNimType NTI_rUuqTvFmkC6KKRqDAazGEA_;
extern TNimType NTI_LBgXxpmYOpS8xroRZgNvbg_;
extern TNimType NTI_Gz6vwaK0PZQIDIwfuvKsOg_;
extern TNimType NTI_DcZ5N67dL3rBj9bxGtx09bFg_;
TNimType NTI_JS0JuFvCBbC2GL3xXBnPQw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_SVfemTA9aCOyua2TJYa6yBg_;
extern TNimType NTI_g9buja9c9aeh0rkDpqsXOJF9bA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_pDfjTbtkTNjmi9bTcaNV32Q unitWeights_cpugRVHYEC9bUpLa71eZMsQ = {IL64(1),
IL64(1000),
IL64(1000000),
IL64(1000000000),
IL64(60000000000),
IL64(3600000000000),
IL64(86400000000000),
IL64(604800000000000)}
;
STRING_LITERAL(TM_6NbDwwj5FY059b1gz2AsAZQ_84, "/Users/matt/lib/Nim/lib/pure/times.nim(572, 10) `monthday <= ge"
"tDaysInMonth(month, year)` ", 90);
STRING_LITERAL(TM_6NbDwwj5FY059b1gz2AsAZQ_85, "-", 1);
STRING_LITERAL(TM_6NbDwwj5FY059b1gz2AsAZQ_86, " is not a valid date", 20);
NIM_CONST tyArray_Splpnswz3rudLg9bDsQoDXg daysUntilMonthLeap_bWLQu3i9bqoFDTyygQP29aFA = {((NI) 0),
((NI) 31),
((NI) 60),
((NI) 91),
((NI) 121),
((NI) 152),
((NI) 182),
((NI) 213),
((NI) 244),
((NI) 274),
((NI) 305),
((NI) 335)}
;
NIM_CONST tyArray_Splpnswz3rudLg9bDsQoDXg daysUntilMonth_TV2R7Va3CeAXpg6eZUosdg = {((NI) 0),
((NI) 31),
((NI) 59),
((NI) 90),
((NI) 120),
((NI) 151),
((NI) 181),
((NI) 212),
((NI) 243),
((NI) 273),
((NI) 304),
((NI) 334)}
;
STRING_LITERAL(TM_6NbDwwj5FY059b1gz2AsAZQ_116, "LOCAL", 5);
NIM_CONST tyTuple_pfrdooyxJsC6cg34ebuBag TM_6NbDwwj5FY059b1gz2AsAZQ_126 = {((NI) 0),
NIM_FALSE}
;
static N_NIMCALL(void, Marker_tyRef_qs7rcJOE2Bz63jdUEPJtIg)(void* p, NI op) {
	tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ* a;
	a = (tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ*)p;
}
static N_NIMCALL(void, Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA)(void* p, NI op) {
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* a;
	a = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)p;
	nimGCvisit((void*)(*a).zonedTimeFromTimeImpl.ClE_0, op);
	nimGCvisit((void*)(*a).zonedTimeFromAdjTimeImpl.ClE_0, op);
	nimGCvisit((void*)(*a).name, op);
}
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_4)(void) {
	nimGCvisit((void*)utcInstance_oeKVHn4dFpBJO35HhEkelw, 0);
}
static N_NIMCALL(void, TM_6NbDwwj5FY059b1gz2AsAZQ_5)(void) {
	nimGCvisit((void*)localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA, 0);
}

static N_INLINE(void, nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}

static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem_cNwQQ4PlSJsZSwvoN5Uafwsystem(p, ((int) 0), size);
}

static N_INLINE(NI64, divInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	{
		if (!(b == IL64(0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == (IL64(-9223372036854775807) - IL64(1)));
		if (!(T7_)) goto LA8_;
		T7_ = (b == IL64(-1));
		LA8_: ;
		if (!T7_) goto LA9_;
{		raiseOverflow();
}	}
	LA9_: ;
	result = (NI64)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
{		T1_ = ((NI) 0);
}	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) (((NI) 2000))))) goto LA9_;
{		callDepthLimitReached_II46IjNZztN9bmbxUD8dt8g();
}	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI64, convert_qLUW0NdF1GYEPO7DWw0ntgtimes)(tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity) {
	NI64 result;
	nimfr_("convert", "times.nim");
	result = (NI64)0;
	nimln_(417, "times.nim");
	nimln_(423, "times.nim");
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_13;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_14;
		if (!(unitFrom < unitTo)) goto LA3_;
{		nimln_(424, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_13 = divInt64(unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0]);
		TM_6NbDwwj5FY059b1gz2AsAZQ_14 = divInt64(quantity, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_13));
		result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_14);
}	}
	goto LA1_;
	LA3_: ;
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_15;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_16;
		nimln_(426, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_15 = divInt64(unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0]);
		TM_6NbDwwj5FY059b1gz2AsAZQ_16 = mulInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_15), quantity);
		result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_16);
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, addInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, convert_BaHZhTECbIab21aey78Ozgtimes)(tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity) {
	NI result;
	nimfr_("convert", "times.nim");
	result = (NI)0;
	nimln_(417, "times.nim");
	nimln_(423, "times.nim");
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_18;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_19;
		if (!(unitFrom < unitTo)) goto LA3_;
{		nimln_(424, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_18 = divInt64(unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0]);
		TM_6NbDwwj5FY059b1gz2AsAZQ_19 = divInt64(((NI64) (quantity)), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_18));
		result = ((NI) ((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_19)));
}	}
	goto LA1_;
	LA3_: ;
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_20;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_21;
		nimln_(426, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_20 = divInt64(unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights_cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0]);
		TM_6NbDwwj5FY059b1gz2AsAZQ_21 = mulInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_20), ((NI64) (quantity)));
		result = ((NI) ((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_21)));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI64, modInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	{
		if (!(b == IL64(0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	result = (NI64)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI64, subInt64)(NI64 a, NI64 b) {
	NI64 result;
{	result = (NI64)0;
	result = (NI64)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (IL64(0) <= (NI64)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (IL64(0) <= (NI64)(result ^ (NI64)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
{		result = i;
		goto BeforeRet_;
}	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, normalize_MABftnLbgeoJ2YU4meiGug)(NI64 seconds, NI64 nanoseconds) {
	tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q result;
	NI64 T1_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_17;
	NI T2_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_22;
	nimfr_("normalize", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q));
	nimln_(432, "times.nim");
	T1_ = (NI64)0;
	T1_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_17 = addInt64(seconds, T1_);
	result.seconds = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_17);
	nimln_(433, "times.nim");
	T2_ = (NI)0;
	T2_ = convert_BaHZhTECbIab21aey78Ozgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));
	TM_6NbDwwj5FY059b1gz2AsAZQ_22 = modInt64(nanoseconds, ((NI64) (T2_)));
	NI64 nanosecond = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_22);
	nimln_(434, "times.nim");
	{
		NI T7_;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_23;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_24;
		if (!(nanosecond < IL64(0))) goto LA5_;
{		nimln_(435, "times.nim");
		T7_ = (NI)0;
		T7_ = convert_BaHZhTECbIab21aey78Ozgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));
		TM_6NbDwwj5FY059b1gz2AsAZQ_23 = addInt64(nanosecond, ((NI64) (T7_)));
		nanosecond = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_23);
		nimln_(436, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_24 = subInt64(result.seconds, ((NI) 1));
		result.seconds = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_24);
}	}
	LA5_: ;
	nimln_(437, "times.nim");
	result.nanosecond = ((NI)chckRange(((NI) (nanosecond)), ((NI) 0), ((NI) 999999999)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, ntSubTime)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q a, tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw b) {
	tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q result;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_25;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_26;
	nimfr_("-", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q));
	nimln_(817, "times.nim");
	nimln_(820, "times.nim");
	nimln_(641, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_25 = subInt64(a.seconds, b.seconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_26 = subInt(((NI) (a.nanosecond)), ((NI) (b.nanosecond)));
	result = normalize_MABftnLbgeoJ2YU4meiGug((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_25), ((NI64) ((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_26))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw, normalize_Zdw9awMN3mWHIiqmlxFaGrw)(NI64 seconds, NI64 nanoseconds) {
	tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw result;
	NI64 T1_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_39;
	NI T2_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_40;
	nimfr_("normalize", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw));
	nimln_(432, "times.nim");
	T1_ = (NI64)0;
	T1_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_39 = addInt64(seconds, T1_);
	result.seconds = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_39);
	nimln_(433, "times.nim");
	T2_ = (NI)0;
	T2_ = convert_BaHZhTECbIab21aey78Ozgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));
	TM_6NbDwwj5FY059b1gz2AsAZQ_40 = modInt64(nanoseconds, ((NI64) (T2_)));
	NI64 nanosecond = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_40);
	nimln_(434, "times.nim");
	{
		NI T7_;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_41;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_42;
		if (!(nanosecond < IL64(0))) goto LA5_;
{		nimln_(435, "times.nim");
		T7_ = (NI)0;
		T7_ = convert_BaHZhTECbIab21aey78Ozgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));
		TM_6NbDwwj5FY059b1gz2AsAZQ_41 = addInt64(nanosecond, ((NI64) (T7_)));
		nanosecond = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_41);
		nimln_(436, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_42 = subInt64(result.seconds, ((NI) 1));
		result.seconds = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_42);
}	}
	LA5_: ;
	nimln_(437, "times.nim");
	result.nanosecond = ((NI)chckRange(((NI) (nanosecond)), ((NI) 0), ((NI) 999999999)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw, initDuration_EjaBAtfRmIw9c8MVpZyLTAg)(NI64 nanoseconds, NI64 microseconds, NI64 milliseconds, NI64 seconds, NI64 minutes, NI64 hours, NI64 days, NI64 weeks) {
	tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw result;
	NI64 T1_;
	NI64 T2_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_27;
	NI64 T3_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_28;
	NI64 T4_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_29;
	NI64 T5_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_30;
	NI64 T6_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_31;
	NI64 T7_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_32;
	NI64 T8_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_33;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_34;
	NI64 T9_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_35;
	NI64 T10_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_36;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_37;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_38;
	nimfr_("initDuration", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration_lj9ar6Co3fgk6NgGnVaNpJw));
	nimln_(462, "times.nim");
	nimln_(468, "times.nim");
	nimln_(467, "times.nim");
	nimln_(466, "times.nim");
	nimln_(465, "times.nim");
	nimln_(464, "times.nim");
	nimln_(463, "times.nim");
	nimln_(462, "times.nim");
	T1_ = (NI64)0;
	T1_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 7), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), weeks);
	nimln_(463, "times.nim");
	T2_ = (NI64)0;
	T2_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 6), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), days);
	TM_6NbDwwj5FY059b1gz2AsAZQ_27 = addInt64(T1_, T2_);
	nimln_(464, "times.nim");
	T3_ = (NI64)0;
	T3_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 4), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), minutes);
	TM_6NbDwwj5FY059b1gz2AsAZQ_28 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_27), T3_);
	nimln_(465, "times.nim");
	T4_ = (NI64)0;
	T4_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 5), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), hours);
	TM_6NbDwwj5FY059b1gz2AsAZQ_29 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_28), T4_);
	nimln_(466, "times.nim");
	T5_ = (NI64)0;
	T5_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), seconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_30 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_29), T5_);
	nimln_(467, "times.nim");
	T6_ = (NI64)0;
	T6_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), milliseconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_31 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_30), T6_);
	nimln_(468, "times.nim");
	T7_ = (NI64)0;
	T7_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), microseconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_32 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_31), T7_);
	nimln_(469, "times.nim");
	T8_ = (NI64)0;
	T8_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);
	TM_6NbDwwj5FY059b1gz2AsAZQ_33 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_32), T8_);
	NI64 seconds_2 = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_33);
	nimln_(470, "times.nim");
	nimln_(471, "times.nim");
	nimln_(470, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_34 = modInt64(milliseconds, IL64(1000));
	T9_ = (NI64)0;
	T9_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_34));
	nimln_(471, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_35 = modInt64(microseconds, IL64(1000000));
	T10_ = (NI64)0;
	T10_ = convert_qLUW0NdF1GYEPO7DWw0ntgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_35));
	TM_6NbDwwj5FY059b1gz2AsAZQ_36 = addInt64(T9_, T10_);
	nimln_(472, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_37 = modInt64(nanoseconds, IL64(1000000000));
	TM_6NbDwwj5FY059b1gz2AsAZQ_38 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_36), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_37));
	NI nanoseconds_2 = ((NI) ((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_38)));
	nimln_(474, "times.nim");
	result = normalize_Zdw9awMN3mWHIiqmlxFaGrw(seconds_2, ((NI64) (nanoseconds_2)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_XjuGlLf9cyYx66ViXrBCvPQ, fromEpochDay_mJEaQzDB47WyotCnk4B9c2A)(NI64 epochday) {
	tyTuple_XjuGlLf9cyYx66ViXrBCvPQ result;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_51;
	NI64 T1_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_53;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_54;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_55;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_56;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_57;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_58;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_59;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_60;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_61;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_62;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_63;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_64;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_65;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_66;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_67;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_68;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_69;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_70;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_71;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_72;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_73;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_74;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_75;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_76;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_77;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_78;
	NI T7_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_79;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_80;
	nimfr_("fromEpochDay", "times.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple_XjuGlLf9cyYx66ViXrBCvPQ));
	nimln_(598, "times.nim");
	NI64 z = epochday;
	nimln_(599, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_51 = addInt64(z, ((NI) 719468));
	z = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_51);
	nimln_(600, "times.nim");
	T1_ = (NI64)0;
	{
		if (!(IL64(0) <= z)) goto LA4_;
{		T1_ = z;
}	}
	goto LA2_;
	LA4_: ;
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_52;
		TM_6NbDwwj5FY059b1gz2AsAZQ_52 = subInt64(z, IL64(146096));
		T1_ = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_52);
	}
	LA2_: ;
	TM_6NbDwwj5FY059b1gz2AsAZQ_53 = divInt64(T1_, IL64(146097));
	NI64 era = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_53);
	nimln_(601, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_54 = mulInt64(era, IL64(146097));
	TM_6NbDwwj5FY059b1gz2AsAZQ_55 = subInt64(z, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_54));
	NI64 doe = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_55);
	nimln_(602, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_56 = divInt64(doe, IL64(1460));
	TM_6NbDwwj5FY059b1gz2AsAZQ_57 = subInt64(doe, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_56));
	TM_6NbDwwj5FY059b1gz2AsAZQ_58 = divInt64(doe, IL64(36524));
	TM_6NbDwwj5FY059b1gz2AsAZQ_59 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_57), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_58));
	TM_6NbDwwj5FY059b1gz2AsAZQ_60 = divInt64(doe, IL64(146096));
	TM_6NbDwwj5FY059b1gz2AsAZQ_61 = subInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_59), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_60));
	TM_6NbDwwj5FY059b1gz2AsAZQ_62 = divInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_61), IL64(365));
	NI64 yoe = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_62);
	nimln_(603, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_63 = mulInt64(era, IL64(400));
	TM_6NbDwwj5FY059b1gz2AsAZQ_64 = addInt64(yoe, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_63));
	NI64 y = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_64);
	nimln_(604, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_65 = mulInt64(IL64(365), yoe);
	TM_6NbDwwj5FY059b1gz2AsAZQ_66 = divInt64(yoe, IL64(4));
	TM_6NbDwwj5FY059b1gz2AsAZQ_67 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_65), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_66));
	TM_6NbDwwj5FY059b1gz2AsAZQ_68 = divInt64(yoe, IL64(100));
	TM_6NbDwwj5FY059b1gz2AsAZQ_69 = subInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_67), (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_68));
	TM_6NbDwwj5FY059b1gz2AsAZQ_70 = subInt64(doe, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_69));
	NI64 doy = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_70);
	nimln_(605, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_71 = mulInt64(IL64(5), doy);
	TM_6NbDwwj5FY059b1gz2AsAZQ_72 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_71), IL64(2));
	TM_6NbDwwj5FY059b1gz2AsAZQ_73 = divInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_72), IL64(153));
	NI64 mp = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_73);
	nimln_(606, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_74 = mulInt64(IL64(153), mp);
	TM_6NbDwwj5FY059b1gz2AsAZQ_75 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_74), IL64(2));
	TM_6NbDwwj5FY059b1gz2AsAZQ_76 = divInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_75), IL64(5));
	TM_6NbDwwj5FY059b1gz2AsAZQ_77 = subInt64(doy, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_76));
	TM_6NbDwwj5FY059b1gz2AsAZQ_78 = addInt64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_77), IL64(1));
	NI64 d = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_78);
	nimln_(607, "times.nim");
	T7_ = (NI)0;
	{
		if (!(mp < IL64(10))) goto LA10_;
{		T7_ = ((NI) 3);
}	}
	goto LA8_;
	LA10_: ;
	{
		T7_ = ((NI) -9);
	}
	LA8_: ;
	TM_6NbDwwj5FY059b1gz2AsAZQ_79 = addInt64(mp, ((NI64) (T7_)));
	NI64 m = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_79);
	nimln_(608, "times.nim");
	result.Field0 = ((NI)chckRange64(d, ((NI) 1), ((NI) 31)));
	result.Field1 = ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw)chckRange64(m, ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 1), ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 12)));
	TM_6NbDwwj5FY059b1gz2AsAZQ_80 = addInt64(y, ((NI64) ((m <= IL64(2)))));
	result.Field2 = ((NI) ((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_80)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isLeapYear_yparhddyYdVywEbz0lSrTA)(NI year) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_81;
	NIM_BOOL T3_;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_82;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_83;
	nimfr_("isLeapYear", "times.nim");
	result = (NIM_BOOL)0;
	nimln_(555, "times.nim");
	nimln_(556, "times.nim");
	T1_ = (NIM_BOOL)0;
	TM_6NbDwwj5FY059b1gz2AsAZQ_81 = modInt(year, ((NI) 4));
	T1_ = ((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_81) == ((NI) 0));
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	nimln_(483, "system.nim");
	nimln_(556, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_82 = modInt(year, ((NI) 100));
	T3_ = !(((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_82) == ((NI) 0)));
	if (T3_) goto LA4_;
	TM_6NbDwwj5FY059b1gz2AsAZQ_83 = modInt(year, ((NI) 400));
	T3_ = ((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_83) == ((NI) 0));
	LA4_: ;
	T1_ = T3_;
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getDaysInMonth_Du19c9a9bSALs8RVBtDxc7Zjg)(tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year) {
	NI result;
	nimfr_("getDaysInMonth", "times.nim");
	result = (NI)0;
	nimln_(561, "times.nim");
	switch (month) {
	case ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 2):
	{
		nimln_(562, "times.nim");
		{
			if (!isLeapYear_yparhddyYdVywEbz0lSrTA(year)) goto LA4_;
{			result = ((NI) 29);
}		}
		goto LA2_;
		LA4_: ;
		{
			result = ((NI) 28);
		}
		LA2_: ;
	}
	break;
	case ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 4):
	case ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 6):
	case ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 9):
	case ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 11):
	{
		nimln_(563, "times.nim");
		result = ((NI) 30);
	}
	break;
	default:
	{
		nimln_(564, "times.nim");
		result = ((NI) 31);
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
{		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[(*dest).len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).len + ((NI) 1)))));
		(*dest).len += (*src).len;
}	}
	LA3_: ;
}

static N_INLINE(void, assertValidDate_oFHP8g45fJYczB5bgKWFQQtimes)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year) {
	nimfr_("assertValidDate", "times.nim");
	nimln_(572, "times.nim");
	{
		NI T3_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		NimStringDesc* T9_;
		T3_ = (NI)0;
		T3_ = getDaysInMonth_Du19c9a9bSALs8RVBtDxc7Zjg(month, year);
		if (!!((((NI) (monthday)) <= T3_))) goto LA4_;
{		T6_ = (NimStringDesc*)0;
		T7_ = (NimStringDesc*)0;
		T7_ = nimIntToStr(year);
		T8_ = (NimStringDesc*)0;
		T8_ = nsuIntToStr(month, ((NI) 2));
		T9_ = (NimStringDesc*)0;
		T9_ = nimIntToStr(((NI) (monthday)));
		T6_ = rawNewString((T7_ ? T7_->len : 0) + (T8_ ? T8_->len : 0) + (T9_ ? T9_->len : 0) + 112);
appendString(T6_, ((NimStringDesc*) &TM_6NbDwwj5FY059b1gz2AsAZQ_84));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_6NbDwwj5FY059b1gz2AsAZQ_85));
appendString(T6_, T8_);
appendString(T6_, ((NimStringDesc*) &TM_6NbDwwj5FY059b1gz2AsAZQ_85));
appendString(T6_, T9_);
appendString(T6_, ((NimStringDesc*) &TM_6NbDwwj5FY059b1gz2AsAZQ_86));
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(T6_);
}	}
	LA4_: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
{		raiseDivByZero();
}	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
{		raiseOverflow();
}	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
{		goto BeforeRet_;
}	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, toEpochDay_BB6kKpP0ite6Jp9a5rrEt5w)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year) {
	NI64 result;
	tyTuple_47w2DboNEPf69aPgubZdd7Q T1_;
	NI y;
	NI m;
	NI d;
	NI T6_;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_89;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_90;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_91;
	NI T12_;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_92;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_93;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_94;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_95;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_96;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_97;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_98;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_99;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_100;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_101;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_102;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_103;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_104;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_105;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_106;
	nimfr_("toEpochDay", "times.nim");
{	result = (NI64)0;
	nimln_(581, "times.nim");
	assertValidDate_oFHP8g45fJYczB5bgKWFQQtimes(monthday, month, year);
	nimln_(582, "times.nim");
	T1_.Field0 = year;
	T1_.Field1 = month;
	T1_.Field2 = ((NI) (monthday));
	y = T1_.Field0;
	m = T1_.Field1;
	d = T1_.Field2;
	nimln_(583, "times.nim");
	{
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_87;
		if (!(m <= ((NI) 2))) goto LA4_;
{		nimln_(584, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_87 = subInt(y, ((NI) 1));
		y = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_87);
}	}
	LA4_: ;
	nimln_(586, "times.nim");
	T6_ = (NI)0;
	{
		if (!(((NI) 0) <= y)) goto LA9_;
{		T6_ = y;
}	}
	goto LA7_;
	LA9_: ;
	{
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_88;
		TM_6NbDwwj5FY059b1gz2AsAZQ_88 = subInt(y, ((NI) 399));
		T6_ = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_88);
	}
	LA7_: ;
	TM_6NbDwwj5FY059b1gz2AsAZQ_89 = divInt(T6_, ((NI) 400));
	NI era = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_89);
	nimln_(587, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_90 = mulInt(era, ((NI) 400));
	TM_6NbDwwj5FY059b1gz2AsAZQ_91 = subInt(y, (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_90));
	NI yoe = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_91);
	nimln_(588, "times.nim");
	T12_ = (NI)0;
	{
		if (!(((NI) 2) < m)) goto LA15_;
{		T12_ = ((NI) -3);
}	}
	goto LA13_;
	LA15_: ;
	{
		T12_ = ((NI) 9);
	}
	LA13_: ;
	TM_6NbDwwj5FY059b1gz2AsAZQ_92 = addInt(m, T12_);
	TM_6NbDwwj5FY059b1gz2AsAZQ_93 = mulInt(((NI) 153), (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_92));
	TM_6NbDwwj5FY059b1gz2AsAZQ_94 = addInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_93), ((NI) 2));
	TM_6NbDwwj5FY059b1gz2AsAZQ_95 = divInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_94), ((NI) 5));
	TM_6NbDwwj5FY059b1gz2AsAZQ_96 = addInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_95), d);
	TM_6NbDwwj5FY059b1gz2AsAZQ_97 = subInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_96), ((NI) 1));
	NI doy = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_97);
	nimln_(589, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_98 = mulInt(yoe, ((NI) 365));
	TM_6NbDwwj5FY059b1gz2AsAZQ_99 = divInt(yoe, ((NI) 4));
	TM_6NbDwwj5FY059b1gz2AsAZQ_100 = addInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_98), (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_99));
	TM_6NbDwwj5FY059b1gz2AsAZQ_101 = divInt(yoe, ((NI) 100));
	TM_6NbDwwj5FY059b1gz2AsAZQ_102 = subInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_100), (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_101));
	TM_6NbDwwj5FY059b1gz2AsAZQ_103 = addInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_102), doy);
	NI doe = (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_103);
	nimln_(590, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_104 = mulInt(era, ((NI) 146097));
	TM_6NbDwwj5FY059b1gz2AsAZQ_105 = addInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_104), doe);
	TM_6NbDwwj5FY059b1gz2AsAZQ_106 = subInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_105), ((NI) 719468));
	result = ((NI64) ((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_106)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg, getDayOfWeek_NgjKhNpZaAlscp2jmCchuA)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year) {
	tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg result;
	NI64 T1_;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_107;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_108;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_109;
	nimfr_("getDayOfWeek", "times.nim");
	result = (tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg)0;
	nimln_(629, "times.nim");
	assertValidDate_oFHP8g45fJYczB5bgKWFQQtimes(monthday, month, year);
	nimln_(631, "times.nim");
	T1_ = (NI64)0;
	T1_ = toEpochDay_BB6kKpP0ite6Jp9a5rrEt5w(monthday, month, year);
	TM_6NbDwwj5FY059b1gz2AsAZQ_107 = subInt64(T1_, IL64(3));
	NI64 days = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_107);
	nimln_(632, "times.nim");
	NI64 weeks = floorDiv_Nvq3S3GNjkBxHjfOZFJjRw(days, ((NI) 7));
	nimln_(633, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_108 = mulInt64(weeks, IL64(7));
	TM_6NbDwwj5FY059b1gz2AsAZQ_109 = subInt64(days, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_108));
	NI64 wd = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_109);
	nimln_(636, "times.nim");
	{
		if (!(wd == IL64(0))) goto LA4_;
{		result = ((tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg) 6);
}	}
	goto LA2_;
	LA4_: ;
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_110;
		TM_6NbDwwj5FY059b1gz2AsAZQ_110 = subInt64(wd, IL64(1));
		result = ((tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg)chckRange64((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_110), ((tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg) 0), ((tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg) 6)));
	}
	LA2_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getDayOfYear_MH9agrbA2S9bCWbHnQW6iSgg)(NI monthday, tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw month, NI year) {
	NI result;
	nimfr_("getDayOfYear", "times.nim");
	result = (NI)0;
	nimln_(614, "times.nim");
	assertValidDate_oFHP8g45fJYczB5bgKWFQQtimes(monthday, month, year);
	nimln_(620, "times.nim");
	{
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_111;
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_112;
		if (!isLeapYear_yparhddyYdVywEbz0lSrTA(year)) goto LA3_;
{		nimln_(621, "times.nim");
		if (month < 1 || month > 12) raiseIndexError3(month, 1, 12);
		TM_6NbDwwj5FY059b1gz2AsAZQ_111 = addInt(daysUntilMonthLeap_bWLQu3i9bqoFDTyygQP29aFA[(month)- 1], ((NI) (monthday)));
		TM_6NbDwwj5FY059b1gz2AsAZQ_112 = subInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_111), ((NI) 1));
		result = ((NI)chckRange((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_112), ((NI) 0), ((NI) 365)));
}	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_113;
		NI TM_6NbDwwj5FY059b1gz2AsAZQ_114;
		nimln_(623, "times.nim");
		if (month < 1 || month > 12) raiseIndexError3(month, 1, 12);
		TM_6NbDwwj5FY059b1gz2AsAZQ_113 = addInt(daysUntilMonth_TV2R7Va3CeAXpg6eZUosdg[(month)- 1], ((NI) (monthday)));
		TM_6NbDwwj5FY059b1gz2AsAZQ_114 = subInt((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_113), ((NI) 1));
		result = ((NI)chckRange((NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_114), ((NI) 0), ((NI) 365)));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initDateTime_9cjTDoh0YFNVFpY3GfapxqQ)(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ* zt, tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result) {
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_43;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_44;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_45;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_46;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_47;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_48;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_49;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_50;
	tyTuple_XjuGlLf9cyYx66ViXrBCvPQ T1_;
	NI d;
	tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw m;
	NI y;
	nimfr_("initDateTime", "times.nim");
	nimln_(865, "times.nim");
	nimln_(866, "times.nim");
	tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q adjTime = ntSubTime((*zt).time, initDuration_EjaBAtfRmIw9c8MVpZyLTAg(IL64(0), IL64(0), IL64(0), ((NI64) ((*zt).utcOffset)), IL64(0), IL64(0), IL64(0), IL64(0)));
	nimln_(867, "times.nim");
	NI64 s = adjTime.seconds;
	nimln_(868, "times.nim");
	NI64 epochday = floorDiv_Nvq3S3GNjkBxHjfOZFJjRw(s, ((NI) 86400));
	nimln_(869, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_43 = mulInt64(epochday, IL64(86400));
	TM_6NbDwwj5FY059b1gz2AsAZQ_44 = subInt64(s, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_43));
	NI64 rem = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_44);
	nimln_(870, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_45 = divInt64(rem, IL64(3600));
	NI64 hour = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_45);
	nimln_(871, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_46 = mulInt64(hour, IL64(3600));
	TM_6NbDwwj5FY059b1gz2AsAZQ_47 = subInt64(rem, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_46));
	rem = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_47);
	nimln_(872, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_48 = divInt64(rem, IL64(60));
	NI64 minute = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_48);
	nimln_(873, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_49 = mulInt64(minute, IL64(60));
	TM_6NbDwwj5FY059b1gz2AsAZQ_50 = subInt64(rem, (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_49));
	rem = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_50);
	nimln_(874, "times.nim");
	NI64 second = rem;
	nimln_(876, "times.nim");
	T1_ = fromEpochDay_mJEaQzDB47WyotCnk4B9c2A(epochday);
	d = T1_.Field0;
	m = T1_.Field1;
	y = T1_.Field2;
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_d9cK9cyKZPJJxFXUmx8dSpPw_));
	(*Result).m_type = (&NTI_d9cK9cyKZPJJxFXUmx8dSpPw_);
	(*Result).year = y;
	(*Result).month = m;
	(*Result).monthday = d;
	(*Result).hour = ((NI)chckRange64(hour, ((NI) 0), ((NI) 23)));
	(*Result).minute = ((NI)chckRange64(minute, ((NI) 0), ((NI) 59)));
	(*Result).second = ((NI)chckRange64(second, ((NI) 0), ((NI) 60)));
	(*Result).nanosecond = (*zt).time.nanosecond;
	nimln_(886, "times.nim");
	(*Result).weekday = getDayOfWeek_NgjKhNpZaAlscp2jmCchuA(d, m, y);
	nimln_(887, "times.nim");
	(*Result).yearday = getDayOfYear_MH9agrbA2S9bCWbHnQW6iSgg(d, m, y);
	(*Result).isDst = (*zt).isDst;
	(*Result).timezone = zone;
	(*Result).utcOffset = (*zt).utcOffset;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, zonedTimeFromTime_Rxfqncxm2ZLhLZdNFIq9a9bw)(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time) {
	tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ result;
	nimfr_("zonedTimeFromTime", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ));
	nimln_(934, "times.nim");
	nimln_(935, "times.nim");
	result = (*zone).zonedTimeFromTimeImpl.ClE_0? (*zone).zonedTimeFromTimeImpl.ClP_0(time, (*zone).zonedTimeFromTimeImpl.ClE_0):((TM_6NbDwwj5FY059b1gz2AsAZQ_115)((*zone).zonedTimeFromTimeImpl.ClP_0))(time);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, inZone_iGIETwnU9aL9a9azchD7uIsBw)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time, tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* zone, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result) {
	tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ T1_;
	nimfr_("inZone", "times.nim");
	nimln_(964, "times.nim");
	T1_ = zonedTimeFromTime_Rxfqncxm2ZLhLZdNFIq9a9bw(zone, time);
	initDateTime_9cjTDoh0YFNVFpY3GfapxqQ((&T1_), zone, Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*, newTimezone_tF9bfmgadDtneoj4dZjS8QQ)(NimStringDesc* name, tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromTimeImpl, tyProc_bs1dgeTxHIjPGTR9axkkHbg zonedTimeFromAdjTimeImpl) {
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* result;
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* T1_;
	nimfr_("newTimezone", "times.nim");
	result = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)0;
	nimln_(900, "times.nim");
	T1_ = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)0;
	T1_ = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*) newObj((&NTI_9a5v4OQPlGqsA25ioN8hFYA_), sizeof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw));
	(*T1_).name = copyString(name);
	(*T1_).zonedTimeFromTimeImpl.ClE_0 = zonedTimeFromTimeImpl.ClE_0;
	(*T1_).zonedTimeFromTimeImpl.ClP_0 = zonedTimeFromTimeImpl.ClP_0;
	(*T1_).zonedTimeFromAdjTimeImpl.ClE_0 = zonedTimeFromAdjTimeImpl.ClE_0;
	(*T1_).zonedTimeFromAdjTimeImpl.ClP_0 = zonedTimeFromAdjTimeImpl.ClP_0;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI64, toAdjUnix_VMBhkoIwSpuOXS0EPc9cd1g)(struct tm tm) {
	NI64 result;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_117;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_118;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_119;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_120;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_121;
	NI TM_6NbDwwj5FY059b1gz2AsAZQ_122;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_123;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_124;
	nimfr_("toAdjUnix", "times.nim");
	result = (NI64)0;
	nimln_(1007, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_117 = addInt(tm.tm_mon, ((NI32) 1));
	if (TM_6NbDwwj5FY059b1gz2AsAZQ_117 < (-2147483647 -1) || TM_6NbDwwj5FY059b1gz2AsAZQ_117 > 2147483647) raiseOverflow();
	nimln_(1008, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_118 = addInt(((NI) (tm.tm_year)), ((NI) 1900));
	NI64 epochDay = toEpochDay_BB6kKpP0ite6Jp9a5rrEt5w(((NI)chckRange(tm.tm_mday, ((NI) 1), ((NI) 31))), ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw)chckRange((NI32)(TM_6NbDwwj5FY059b1gz2AsAZQ_117), ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 1), ((tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw) 12))), (NI)(TM_6NbDwwj5FY059b1gz2AsAZQ_118));
	nimln_(1009, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_119 = mulInt64(epochDay, IL64(86400));
	result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_119);
	nimln_(1010, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_120 = mulInt(tm.tm_hour, ((NI32) 3600));
	if (TM_6NbDwwj5FY059b1gz2AsAZQ_120 < (-2147483647 -1) || TM_6NbDwwj5FY059b1gz2AsAZQ_120 > 2147483647) raiseOverflow();
	TM_6NbDwwj5FY059b1gz2AsAZQ_121 = addInt64(result, ((NI) ((NI32)(TM_6NbDwwj5FY059b1gz2AsAZQ_120))));
	result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_121);
	nimln_(1011, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_122 = mulInt(tm.tm_min, ((NI32) 60));
	if (TM_6NbDwwj5FY059b1gz2AsAZQ_122 < (-2147483647 -1) || TM_6NbDwwj5FY059b1gz2AsAZQ_122 > 2147483647) raiseOverflow();
	TM_6NbDwwj5FY059b1gz2AsAZQ_123 = addInt64(result, ((NI) ((NI32)(TM_6NbDwwj5FY059b1gz2AsAZQ_122))));
	result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_123);
	nimln_(1012, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_124 = addInt64(result, ((NI) (tm.tm_sec)));
	result = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_124);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_pfrdooyxJsC6cg34ebuBag, getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg)(NI64 unix) {
	tyTuple_pfrdooyxJsC6cg34ebuBag result;
	NI64 T1_;
	nimfr_("getLocalOffsetAndDst", "times.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple_pfrdooyxJsC6cg34ebuBag));
	nimln_(1028, "times.nim");
	T1_ = (NI64)0;
	T1_ = clamp_QUt10jOE7hoF4h8P6Cgfqg(unix, (IL64(-9223372036854775807) - IL64(1)), IL64(9223372036854775807));
	long a = ((long) (T1_));
	nimln_(1029, "times.nim");
	struct tm* tmPtr = localtime((&a));
	nimln_(1030, "times.nim");
	{
		NI64 T6_;
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_125;
		if (!!((tmPtr == 0))) goto LA4_;
{		nimln_(1031, "times.nim");
		struct tm tm = (*tmPtr);
		nimln_(1032, "times.nim");
		T6_ = (NI64)0;
		T6_ = toAdjUnix_VMBhkoIwSpuOXS0EPc9cd1g(tm);
		TM_6NbDwwj5FY059b1gz2AsAZQ_125 = subInt64(((NI64) (a)), T6_);
		result.Field0 = ((NI) ((NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_125)));
		result.Field1 = (((NI32) 0) < tm.tm_isdst);
		goto BeforeRet_;
}	}
	LA4_: ;
	nimln_(1033, "times.nim");
	result = TM_6NbDwwj5FY059b1gz2AsAZQ_126;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, localZonedTimeFromTime_ODvPcoZ6jtenmqLq9aVXBvg)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q time) {
	tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ result;
	tyTuple_pfrdooyxJsC6cg34ebuBag T1_;
	NI offset;
	NIM_BOOL dst;
	nimfr_("localZonedTimeFromTime", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ));
	nimln_(1036, "times.nim");
	T1_ = getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg(time.seconds);
	offset = T1_.Field0;
	dst = T1_.Field1;
	nimln_(1037, "times.nim");
	result.time = time;
	nimln_(1038, "times.nim");
	result.utcOffset = offset;
	nimln_(1039, "times.nim");
	result.isDst = dst;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, initTime_UQc07zVQAYQ0by6TamgL9bQ)(NI64 unix, NI nanosecond) {
	tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q result;
	nimfr_("initTime", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q));
	nimln_(803, "times.nim");
	result.seconds = unix;
	nimln_(804, "times.nim");
	result.nanosecond = nanosecond;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ, localZonedTimeFromAdjTime_09bwaQmOse9czkLeY30l6MIA)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q adjTime) {
	tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ result;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_128;
	tyTuple_pfrdooyxJsC6cg34ebuBag T1_;
	NI pastOffset;
	NIM_BOOL _;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_129;
	tyTuple_pfrdooyxJsC6cg34ebuBag T2_;
	NI futureOffset;
	NIM_BOOL __2;
	NI utcOffset;
	NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_132;
	tyTuple_pfrdooyxJsC6cg34ebuBag T13_;
	NI finalOffset;
	NIM_BOOL dst;
	nimfr_("localZonedTimeFromAdjTime", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_ZonedTime_WigfH9apQAxJ69bBPh3wB8RQ));
	nimln_(1042, "times.nim");
	NI64 adjUnix = adjTime.seconds;
	nimln_(1043, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_128 = subInt64(adjUnix, IL64(86400));
	NI64 past = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_128);
	nimln_(1044, "times.nim");
	T1_ = getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg(past);
	pastOffset = T1_.Field0;
	_ = T1_.Field1;
	nimln_(1046, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_129 = addInt64(adjUnix, IL64(86400));
	NI64 future = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_129);
	nimln_(1047, "times.nim");
	T2_ = getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg(future);
	futureOffset = T2_.Field0;
	__2 = T2_.Field1;
	utcOffset = (NI)0;
	nimln_(1050, "times.nim");
	{
		if (!(pastOffset == futureOffset)) goto LA5_;
{		nimln_(1051, "times.nim");
		utcOffset = pastOffset;
}	}
	goto LA3_;
	LA5_: ;
	{
		NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_131;
		tyTuple_pfrdooyxJsC6cg34ebuBag T12_;
		nimln_(1053, "times.nim");
		{
			NI64 TM_6NbDwwj5FY059b1gz2AsAZQ_130;
			if (!(futureOffset < pastOffset)) goto LA10_;
{			nimln_(1054, "times.nim");
			TM_6NbDwwj5FY059b1gz2AsAZQ_130 = subInt64(adjUnix, ((NI) 3600));
			adjUnix = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_130);
}		}
		LA10_: ;
		nimln_(1056, "times.nim");
		TM_6NbDwwj5FY059b1gz2AsAZQ_131 = addInt64(adjUnix, ((NI64) (pastOffset)));
		adjUnix = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_131);
		nimln_(1057, "times.nim");
		T12_ = getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg(adjUnix);
		utcOffset = T12_.Field0;
	}
	LA3_: ;
	nimln_(1061, "times.nim");
	TM_6NbDwwj5FY059b1gz2AsAZQ_132 = addInt64(adjTime.seconds, ((NI64) (utcOffset)));
	NI64 utcUnix = (NI64)(TM_6NbDwwj5FY059b1gz2AsAZQ_132);
	nimln_(1062, "times.nim");
	T13_ = getLocalOffsetAndDst_w68ypwRG9bbkkhRUMagB8hg(utcUnix);
	finalOffset = T13_.Field0;
	dst = T13_.Field1;
	nimln_(1063, "times.nim");
	result.time = initTime_UQc07zVQAYQ0by6TamgL9bQ(utcUnix, adjTime.nanosecond);
	nimln_(1064, "times.nim");
	result.utcOffset = finalOffset;
	nimln_(1065, "times.nim");
	result.isDst = dst;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*, local_iX2Ltm3Mj5gsgJ5hFxUKgQ)(void) {
	tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw* result;
	nimfr_("local", "times.nim");
	result = (tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*)0;
	nimln_(1087, "times.nim");
	{
		tyProc_bs1dgeTxHIjPGTR9axkkHbg T5_;
		tyProc_bs1dgeTxHIjPGTR9axkkHbg T6_;
		if (!(localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA == 0)) goto LA3_;
{		nimln_(1088, "times.nim");
		nimZeroMem((void*)(&T5_), sizeof(tyProc_bs1dgeTxHIjPGTR9axkkHbg));
		T5_.ClP_0 = ((TM_6NbDwwj5FY059b1gz2AsAZQ_127) (localZonedTimeFromTime_ODvPcoZ6jtenmqLq9aVXBvg)); T5_.ClE_0 = NIM_NIL;
		nimZeroMem((void*)(&T6_), sizeof(tyProc_bs1dgeTxHIjPGTR9axkkHbg));
		T6_.ClP_0 = ((TM_6NbDwwj5FY059b1gz2AsAZQ_133) (localZonedTimeFromAdjTime_09bwaQmOse9czkLeY30l6MIA)); T6_.ClE_0 = NIM_NIL;
		localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA = newTimezone_tF9bfmgadDtneoj4dZjS8QQ(((NimStringDesc*) &TM_6NbDwwj5FY059b1gz2AsAZQ_116), T5_, T6_);
}	}
	LA3_: ;
	nimln_(1090, "times.nim");
	result = localInstance_cLtN9cK9bCe6IPhJ3UFNLNKA;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, local_GO0pnrIM1y5cQBpG7t80Hw)(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q t, tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result) {
	nimfr_("local", "times.nim");
	nimln_(1105, "times.nim");
	nimln_(1106, "times.nim");
	inZone_iGIETwnU9aL9a9azchD7uIsBw(t, local_iX2Ltm3Mj5gsgJ5hFxUKgQ(), Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q, getTime_NtnAfG7BP2zKh2DoyUbakQ)(void) {
	tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q result;
	struct timeval a;
	NI T1_;
	nimfr_("getTime", "times.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Time_3y2ZpqsTJLqdZvpC9a0rU2Q));
	nimZeroMem((void*)(&a), sizeof(struct timeval));
	nimln_(1119, "times.nim");
	gettimeofday((&a), NIM_NIL);
	nimln_(1120, "times.nim");
	nimln_(1121, "times.nim");
	T1_ = (NI)0;
	T1_ = convert_BaHZhTECbIab21aey78Ozgtimes(((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit_52alPn04ElUUbqLeok9b3PQ) 0), a.tv_usec);
	result = initTime_UQc07zVQAYQ0by6TamgL9bQ(((NI64) (a.tv_sec)), ((NI)chckRange(T1_, ((NI) 0), ((NI) 999999999))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, now_tfUyEAJWC9aO9bQAg4deAWvw)(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw* Result) {
	nimfr_("now", "times.nim");
	nimln_(1132, "times.nim");
	nimln_(1135, "times.nim");
	local_GO0pnrIM1y5cQBpG7t80Hw(getTime_NtnAfG7BP2zKh2DoyUbakQ(), Result);
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[(*dest).len] = c;
	(*dest).data[(NI)((*dest).len + ((NI) 1))] = 0;
	(*dest).len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw dt;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("getDateStr", "times.nim");
	result = (NimStringDesc*)0;
	nimZeroMem((void*)(&dt), sizeof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw));
	dt.m_type = (&NTI_d9cK9cyKZPJJxFXUmx8dSpPw_);
	nimln_(1209, "times.nim");
	now_tfUyEAJWC9aO9bQAg4deAWvw((&dt));
	nimln_(1211, "times.nim");
	T1_ = (NimStringDesc*)0;
	nimln_(1210, "times.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = nimIntToStr(dt.year);
	T3_ = (NimStringDesc*)0;
	T3_ = nsuIntToStr(dt.month, ((NI) 2));
	nimln_(1211, "times.nim");
	T4_ = (NimStringDesc*)0;
	T4_ = nsuIntToStr(((NI) (dt.monthday)), ((NI) 2));
	T1_ = rawNewString((T2_ ? T2_->len : 0) + (T3_ ? T3_->len : 0) + (T4_ ? T4_->len : 0) + 2);
appendString(T1_, T2_);
appendChar(T1_, 45);
appendString(T1_, T3_);
appendChar(T1_, 45);
appendString(T1_, T4_);
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw dt;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("getClockStr", "times.nim");
	result = (NimStringDesc*)0;
	nimZeroMem((void*)(&dt), sizeof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw));
	dt.m_type = (&NTI_d9cK9cyKZPJJxFXUmx8dSpPw_);
	nimln_(1215, "times.nim");
	now_tfUyEAJWC9aO9bQAg4deAWvw((&dt));
	nimln_(1217, "times.nim");
	T1_ = (NimStringDesc*)0;
	nimln_(1216, "times.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = nsuIntToStr(((NI) (dt.hour)), ((NI) 2));
	T3_ = (NimStringDesc*)0;
	T3_ = nsuIntToStr(((NI) (dt.minute)), ((NI) 2));
	nimln_(1217, "times.nim");
	T4_ = (NimStringDesc*)0;
	T4_ = nsuIntToStr(((NI) (dt.second)), ((NI) 2));
	T1_ = rawNewString((T2_ ? T2_->len : 0) + (T3_ ? T3_->len : 0) + (T4_ ? T4_->len : 0) + 2);
appendString(T1_, T2_);
appendChar(T1_, 58);
appendString(T1_, T3_);
appendChar(T1_, 58);
appendString(T1_, T4_);
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
}
	nimfr_("times", "times.nim");
nimRegisterThreadLocalMarker(TM_6NbDwwj5FY059b1gz2AsAZQ_4);
nimRegisterThreadLocalMarker(TM_6NbDwwj5FY059b1gz2AsAZQ_5);
	nimln_(233, "times.nim");
	tzset();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_timesDatInit000)(void) {
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_2[3];
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_3[2];
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_6[12];
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_7[12];
NI TM_6NbDwwj5FY059b1gz2AsAZQ_9;
static char* NIM_CONST TM_6NbDwwj5FY059b1gz2AsAZQ_8[12] = {
"January", 
"February", 
"March", 
"April", 
"May", 
"June", 
"July", 
"August", 
"September", 
"October", 
"November", 
"December"};
static TNimNode* TM_6NbDwwj5FY059b1gz2AsAZQ_10[7];
NI TM_6NbDwwj5FY059b1gz2AsAZQ_12;
static char* NIM_CONST TM_6NbDwwj5FY059b1gz2AsAZQ_11[7] = {
"Monday", 
"Tuesday", 
"Wednesday", 
"Thursday", 
"Friday", 
"Saturday", 
"Sunday"};
static TNimNode TM_6NbDwwj5FY059b1gz2AsAZQ_0[42];
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.size = sizeof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw);
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.kind = 18;
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.base = 0;
TM_6NbDwwj5FY059b1gz2AsAZQ_2[0] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[1];
NTI_bs1dgeTxHIjPGTR9axkkHbg_.size = sizeof(tyTuple_WCz3Z7at9aJyVFSh5OmwJNg);
NTI_bs1dgeTxHIjPGTR9axkkHbg_.kind = 18;
NTI_bs1dgeTxHIjPGTR9axkkHbg_.base = 0;
TM_6NbDwwj5FY059b1gz2AsAZQ_3[0] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[3];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].offset = offsetof(tyTuple_WCz3Z7at9aJyVFSh5OmwJNg, Field0);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[3].name = "Field0";
TM_6NbDwwj5FY059b1gz2AsAZQ_3[1] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[4];
NTI_4Ve8wOWSE8Hdar7fr5TdwQ_.size = sizeof(tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ);
NTI_4Ve8wOWSE8Hdar7fr5TdwQ_.kind = 17;
NTI_4Ve8wOWSE8Hdar7fr5TdwQ_.base = (&NTI_ytyiCJqK439aF9cIibuRVpAg_);
NTI_4Ve8wOWSE8Hdar7fr5TdwQ_.flags = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[5].len = 0; TM_6NbDwwj5FY059b1gz2AsAZQ_0[5].kind = 2;
NTI_4Ve8wOWSE8Hdar7fr5TdwQ_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[5];
NTI_qs7rcJOE2Bz63jdUEPJtIg_.size = sizeof(tyObject_Env_dotdotslashdotdotslashdotdotslashdotdotslashdotdotslashlibslashNimslashlibslashpureslashtimesdotnim__4Ve8wOWSE8Hdar7fr5TdwQ*);
NTI_qs7rcJOE2Bz63jdUEPJtIg_.kind = 22;
NTI_qs7rcJOE2Bz63jdUEPJtIg_.base = (&NTI_4Ve8wOWSE8Hdar7fr5TdwQ_);
NTI_qs7rcJOE2Bz63jdUEPJtIg_.marker = Marker_tyRef_qs7rcJOE2Bz63jdUEPJtIg;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].offset = offsetof(tyTuple_WCz3Z7at9aJyVFSh5OmwJNg, Field1);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].typ = (&NTI_qs7rcJOE2Bz63jdUEPJtIg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[4].name = "Field1";
TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].len = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[2].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_3[0];
NTI_bs1dgeTxHIjPGTR9axkkHbg_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[2];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromTimeImpl);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].typ = (&NTI_bs1dgeTxHIjPGTR9axkkHbg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[1].name = "zonedTimeFromTimeImpl";
TM_6NbDwwj5FY059b1gz2AsAZQ_2[1] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[6];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, zonedTimeFromAdjTimeImpl);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].typ = (&NTI_bs1dgeTxHIjPGTR9axkkHbg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[6].name = "zonedTimeFromAdjTimeImpl";
TM_6NbDwwj5FY059b1gz2AsAZQ_2[2] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[7];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].offset = offsetof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw, name);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[7].name = "name";
TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].len = 3; TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[0].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_2[0];
NTI_F8OvqlxXyGXRSiK9c1fCDVw_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[0];
NTI_9a5v4OQPlGqsA25ioN8hFYA_.size = sizeof(tyObject_TimezonecolonObjectType__F8OvqlxXyGXRSiK9c1fCDVw*);
NTI_9a5v4OQPlGqsA25ioN8hFYA_.kind = 22;
NTI_9a5v4OQPlGqsA25ioN8hFYA_.base = (&NTI_F8OvqlxXyGXRSiK9c1fCDVw_);
NTI_9a5v4OQPlGqsA25ioN8hFYA_.marker = Marker_tyRef_9a5v4OQPlGqsA25ioN8hFYA;
NTI_d9cK9cyKZPJJxFXUmx8dSpPw_.size = sizeof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw);
NTI_d9cK9cyKZPJJxFXUmx8dSpPw_.kind = 17;
NTI_d9cK9cyKZPJJxFXUmx8dSpPw_.base = (&NTI_ytyiCJqK439aF9cIibuRVpAg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_6[0] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[9];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[9].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[9].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, nanosecond);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[9].typ = (&NTI_PpavWgyrx5odXyR89aNlcWA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[9].name = "nanosecond";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[1] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[10];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[10].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[10].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, second);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[10].typ = (&NTI_rUuqTvFmkC6KKRqDAazGEA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[10].name = "second";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[2] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[11];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[11].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[11].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, minute);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[11].typ = (&NTI_LBgXxpmYOpS8xroRZgNvbg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[11].name = "minute";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[3] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[12];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[12].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[12].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, hour);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[12].typ = (&NTI_Gz6vwaK0PZQIDIwfuvKsOg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[12].name = "hour";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[4] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[13];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[13].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[13].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, monthday);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[13].typ = (&NTI_DcZ5N67dL3rBj9bxGtx09bFg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[13].name = "monthday";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[5] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[14];
NTI_JS0JuFvCBbC2GL3xXBnPQw_.size = sizeof(tyEnum_Month_JS0JuFvCBbC2GL3xXBnPQw);
NTI_JS0JuFvCBbC2GL3xXBnPQw_.kind = 14;
NTI_JS0JuFvCBbC2GL3xXBnPQw_.base = 0;
NTI_JS0JuFvCBbC2GL3xXBnPQw_.flags = 3;
for (TM_6NbDwwj5FY059b1gz2AsAZQ_9 = 0; TM_6NbDwwj5FY059b1gz2AsAZQ_9 < 12; TM_6NbDwwj5FY059b1gz2AsAZQ_9++) {
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_9+15].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_9+15].offset = TM_6NbDwwj5FY059b1gz2AsAZQ_9;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_9+15].name = TM_6NbDwwj5FY059b1gz2AsAZQ_8[TM_6NbDwwj5FY059b1gz2AsAZQ_9];
TM_6NbDwwj5FY059b1gz2AsAZQ_7[TM_6NbDwwj5FY059b1gz2AsAZQ_9] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_9+15];
}
TM_6NbDwwj5FY059b1gz2AsAZQ_0[15].offset = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[16].offset = 2;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[17].offset = 3;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[18].offset = 4;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[19].offset = 5;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[20].offset = 6;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[21].offset = 7;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[22].offset = 8;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[23].offset = 9;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[24].offset = 10;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[25].offset = 11;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[26].offset = 12;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[27].len = 12; TM_6NbDwwj5FY059b1gz2AsAZQ_0[27].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[27].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_7[0];
NTI_JS0JuFvCBbC2GL3xXBnPQw_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[27];
NTI_JS0JuFvCBbC2GL3xXBnPQw_.flags = 1<<2;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[14].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[14].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, month);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[14].typ = (&NTI_JS0JuFvCBbC2GL3xXBnPQw_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[14].name = "month";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[6] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[28];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[28].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[28].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, year);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[28].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[28].name = "year";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[7] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[29];
NTI_SVfemTA9aCOyua2TJYa6yBg_.size = sizeof(tyEnum_WeekDay_SVfemTA9aCOyua2TJYa6yBg);
NTI_SVfemTA9aCOyua2TJYa6yBg_.kind = 14;
NTI_SVfemTA9aCOyua2TJYa6yBg_.base = 0;
NTI_SVfemTA9aCOyua2TJYa6yBg_.flags = 3;
for (TM_6NbDwwj5FY059b1gz2AsAZQ_12 = 0; TM_6NbDwwj5FY059b1gz2AsAZQ_12 < 7; TM_6NbDwwj5FY059b1gz2AsAZQ_12++) {
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_12+30].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_12+30].offset = TM_6NbDwwj5FY059b1gz2AsAZQ_12;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_12+30].name = TM_6NbDwwj5FY059b1gz2AsAZQ_11[TM_6NbDwwj5FY059b1gz2AsAZQ_12];
TM_6NbDwwj5FY059b1gz2AsAZQ_10[TM_6NbDwwj5FY059b1gz2AsAZQ_12] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[TM_6NbDwwj5FY059b1gz2AsAZQ_12+30];
}
TM_6NbDwwj5FY059b1gz2AsAZQ_0[37].len = 7; TM_6NbDwwj5FY059b1gz2AsAZQ_0[37].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[37].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_10[0];
NTI_SVfemTA9aCOyua2TJYa6yBg_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[37];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[29].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[29].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, weekday);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[29].typ = (&NTI_SVfemTA9aCOyua2TJYa6yBg_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[29].name = "weekday";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[8] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[38];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[38].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[38].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, yearday);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[38].typ = (&NTI_g9buja9c9aeh0rkDpqsXOJF9bA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[38].name = "yearday";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[9] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[39];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[39].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[39].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, isDst);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[39].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[39].name = "isDst";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[10] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[40];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[40].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[40].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, timezone);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[40].typ = (&NTI_9a5v4OQPlGqsA25ioN8hFYA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[40].name = "timezone";
TM_6NbDwwj5FY059b1gz2AsAZQ_6[11] = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[41];
TM_6NbDwwj5FY059b1gz2AsAZQ_0[41].kind = 1;
TM_6NbDwwj5FY059b1gz2AsAZQ_0[41].offset = offsetof(tyObject_DateTime_d9cK9cyKZPJJxFXUmx8dSpPw, utcOffset);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[41].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_6NbDwwj5FY059b1gz2AsAZQ_0[41].name = "utcOffset";
TM_6NbDwwj5FY059b1gz2AsAZQ_0[8].len = 12; TM_6NbDwwj5FY059b1gz2AsAZQ_0[8].kind = 2; TM_6NbDwwj5FY059b1gz2AsAZQ_0[8].sons = &TM_6NbDwwj5FY059b1gz2AsAZQ_6[0];
NTI_d9cK9cyKZPJJxFXUmx8dSpPw_.node = &TM_6NbDwwj5FY059b1gz2AsAZQ_0[8];
}

