version: '2'
services:
  web:
    build:
      context: .
      dockerfile: dev/web.Dockerfile
    command: /code/main.py --host 0.0.0.0 --port 5000
    volumes:
    - .:/code
    working_dir: /code
    ports:
    - "80:5000"
    environment:
      DEBUG:
      FLASK_SECRET_KEY:
      STRIPE_API_KEY:
      STRIPE_PUBLIC_KEY:
      SENTRY_DSN:
      BUCKETS_LICENSE_KEY:
