version: '2'
services:
  web:
    build:
      context: .
      dockerfile: dev/web.Dockerfile
    command: /code/main.py --host 0.0.0.0 --port 5000
    volumes:
    - .:/code
    working_dir: /code
    ports:
    - "80:5000"
    links:
    - postgres
    environment:
      DEBUG:
      FLASK_SECRET_KEY:
      STRIPE_API_KEY:
      STRIPE_PUBLIC_KEY:
      SENTRY_DSN:
      BUCKETS_LICENSE_KEY:
      PAYPAL_CLIENT_ID:
      PAYPAL_CLIENT_SECRET:
      STATIC_SITE_URL: http://192.168.99.100:8080
      DATABASE_URL: "postgres://postgres:postgres@postgres"
  static:
    image: python:2.7.16
    volumes:
    - ../staticweb/_dev:/code
    command: python -m SimpleHTTPServer 8080
    working_dir: /code
    ports:
    - "8080:8080"
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "foobar"